import { extractEntitlementKeyData, getProductEntitlement, canonicalizeProse } from '../extractKeyData';
import { detectLicenseKeyFormat, isEntitlementKey } from '../detectFormat';
import { sha512 } from '../sha512';
import { stringToUtf8Bytes } from '../encoding';
import { buildTestKey } from './buildTestKey';
import {
  SUBSCRIPTION_KEY,
  ACCENTED_HOLDER_KEY,
  CJK_HOLDER_KEY,
  SUBSCRIPTION_EXTERNAL_KEY,
  TRIAL_KEY,
  PERPETUAL_KEY,
  HF_ONLY_KEY,
  MIXED_KEY,
  SUBSCRIPTION_UNTIL,
  TRIAL_UNTIL,
} from './fixtures';

/**
 * A well-formed Handsontable product entry, with the fields a test does not care about filled in.
 *
 * @param {object} [overrides] The fields to change.
 * @returns {object}
 */
function handsontableEntry(overrides = {}) {
  return {
    capabilities: ['core'],
    usage_until: SUBSCRIPTION_UNTIL,
    notice: 60,
    grace: 90,
    flags: [],
    ...overrides,
  };
}

/**
 * Returns the machine-readable `[...]` block of a key, without the prose in front of it.
 *
 * @param {string} key The whole key.
 * @returns {string}
 */
function blockOf(key) {
  return key.slice(key.lastIndexOf('['));
}

/**
 * Returns the prose of a key - everything in front of its block.
 *
 * @param {string} key The whole key.
 * @returns {string}
 */
function proseOf(key) {
  return key.slice(0, key.lastIndexOf('['));
}

describe('entitlementLicenseKey/sha512', () => {
  // Known-answer vectors from the SHA-512 specification (FIPS 180-4).
  it('should hash the empty input', () => {
    expect(sha512([])).toBe(
      'cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce' +
      '47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e'
    );
  });

  it('should hash "abc"', () => {
    expect(sha512(stringToUtf8Bytes('abc'))).toBe(
      'ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a' +
      '2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f'
    );
  });
});

describe('entitlementLicenseKey/detectFormat', () => {
  it('should recognize an entitlement key by its trailing block', () => {
    expect(detectLicenseKeyFormat(SUBSCRIPTION_KEY)).toBe('entitlement');
    expect(isEntitlementKey(SUBSCRIPTION_KEY)).toBe(true);
    // The shape test does not validate: the bare block still routes to the entitlement reader,
    // which then rejects it.
    expect(isEntitlementKey(blockOf(SUBSCRIPTION_KEY))).toBe(true);
  });

  it('should tell the other key formats apart without validating them', () => {
    expect(detectLicenseKeyFormat('852a2-94216-cca54-21009-14a44')).toBe('legacy');
    expect(detectLicenseKeyFormat('00000-00000-00000-00000-00000')).toBe('legacy');
    expect(detectLicenseKeyFormat('non-commercial-and-evaluation')).toBe('non-commercial-and-evaluation');
    expect(detectLicenseKeyFormat('NON-COMMERCIAL-AND-EVALUATION')).toBe('non-commercial-and-evaluation');
    // `gpl-v3` is NOT a Handsontable format - the specification's legacy list covers HyperFormula
    // too, and the frozen validator has never recognized it. It reads as an unknown string.
    expect(detectLicenseKeyFormat('gpl-v3')).toBe('unknown');
    expect(detectLicenseKeyFormat('')).toBe('unknown');
    expect(detectLicenseKeyFormat(undefined)).toBe('unknown');
    expect(detectLicenseKeyFormat(12345)).toBe('unknown');
  });

  it('should not route any non-entitlement key to the entitlement reader', () => {
    ['852a2-94216-cca54-21009-14a44', 'non-commercial-and-evaluation', 'gpl-v3', '', undefined, null]
      .forEach((key) => {
        expect(isEntitlementKey(key)).toBe(false);
      });
  });
});

describe('entitlementLicenseKey/extractKeyData', () => {
  describe('reading a key generated by the license-key package', () => {
    it('should read a subscription key', () => {
      const data = extractEntitlementKeyData(SUBSCRIPTION_KEY);

      expect(getProductEntitlement(data, 'handsontable')).toEqual({
        capabilities: ['core'],
        usage_until: SUBSCRIPTION_UNTIL,
        notice: 60,
        grace: 90,
        flags: [],
      });
    });

    it('should read a trial key', () => {
      const entitlement = getProductEntitlement(extractEntitlementKeyData(TRIAL_KEY), 'handsontable');

      expect(entitlement.usage_until).toBe(TRIAL_UNTIL);
      expect(entitlement.notice).toBe(45);
      expect(entitlement.grace).toBe(15);
      expect(entitlement.flags).toEqual(['trial']);
    });

    it('should read a perpetual key as a maintenance date, never as an expiry', () => {
      const entitlement = getProductEntitlement(extractEntitlementKeyData(PERPETUAL_KEY), 'handsontable');

      expect(entitlement.release_until).toBe('2027-08-12');
      expect(entitlement.usage_until).toBeUndefined();
    });

    it('should read the silencing flags of an externally-used key', () => {
      const entitlement = getProductEntitlement(extractEntitlementKeyData(SUBSCRIPTION_EXTERNAL_KEY), 'handsontable');

      expect(entitlement.flags).toEqual(['no-console-warns', 'no-ui-warns']);
    });

    it('should read every product of a key granting two, each on its own terms', () => {
      const data = extractEntitlementKeyData(MIXED_KEY);

      expect(getProductEntitlement(data, 'handsontable').usage_until).toBe(SUBSCRIPTION_UNTIL);
      expect(getProductEntitlement(data, 'hyperformula').release_until).toBe('2025-03-31');
    });

    it('should read a key whose product map is empty, granting nothing (H5)', () => {
      const data = extractEntitlementKeyData(buildTestKey({ products: {} }));

      expect(data).toEqual({ products: {} });
      expect(getProductEntitlement(data, 'handsontable')).toBeNull();
    });

    it('should read a key that grants no Handsontable license, leaving the verdict to the caller', () => {
      const data = extractEntitlementKeyData(HF_ONLY_KEY);

      expect(data).not.toBeNull();
      expect(getProductEntitlement(data, 'handsontable')).toBeNull();
      expect(getProductEntitlement(data, 'hyperformula')).not.toBeNull();
    });
  });

  describe('the prose layer', () => {
    const expected = () => extractEntitlementKeyData(SUBSCRIPTION_KEY);

    it('should reject the bare block - the checksum covers the prose', () => {
      expect(extractEntitlementKeyData(blockOf(SUBSCRIPTION_KEY))).toBeNull();
      expect(extractEntitlementKeyData(` \n${blockOf(SUBSCRIPTION_KEY)}\n`)).toBeNull();
    });

    it('should reject a bare block whose checksum was computed over empty prose', () => {
      const key = buildTestKey({ products: { handsontable: handsontableEntry() } }, { prose: '' });

      expect(key.startsWith('[')).toBe(true);
      expect(extractEntitlementKeyData(key)).toBeNull();
      // Whitespace alone is empty prose, too.
      expect(extractEntitlementKeyData(` \n\t${key}`)).toBeNull();
    });

    it('should reject a key whose prose was edited, added to, or replaced', () => {
      const prose = proseOf(SUBSCRIPTION_KEY);
      const block = blockOf(SUBSCRIPTION_KEY);

      [
        prose.replace('2027-08-12 (UTC)', '2099-08-12 (UTC)'), // one sentence changed
        prose.replace('internal use', 'external use'),
        prose.replace('Test Fixture', 'Test Fixturf'), // one letter changed
        `${prose.split('\n\n')[0]}\n\n`, // the license sentence removed
        `Anything at all.\n\n${prose}`, // text added in front
        'Anything at all.\n\n', // replaced entirely
        `${prose.replace(/\.$/m, '')}`, // a period dropped
      ].forEach((edited) => {
        expect(edited).not.toBe(prose);
        expect(extractEntitlementKeyData(edited + block)).toBeNull();
      });
    });

    it('should reject a key with text other than whitespace after the block', () => {
      ['x', ' x', '\n.', '"', ']', '[]', '\\', '\\x', '\\n x'].forEach((suffix) => {
        expect(extractEntitlementKeyData(SUBSCRIPTION_KEY + suffix)).toBeNull();
      });
    });

    it('should accept whitespace after the block', () => {
      [' ', '\n', '\r\n', '\t', '\n\n  \n'].forEach((suffix) => {
        expect(extractEntitlementKeyData(SUBSCRIPTION_KEY + suffix)).toEqual(expected());
      });
    });

    it('should read a key that was rewrapped, put on one line, or had its whitespace changed', () => {
      const prose = proseOf(SUBSCRIPTION_KEY);
      const block = blockOf(SUBSCRIPTION_KEY);

      [
        SUBSCRIPTION_KEY.replace(/\s+/g, ' '), // the one-line form the generator prints
        prose.replace(/\s+/g, '') + block, // every whitespace character removed
        prose.replace(/ /g, '\n') + block, // every space turned into a line break
        prose.replace(/\n/g, '\r\n') + block, // Windows line endings
        prose.replace(/\n/g, '\r') + block, // old Mac line endings
        prose.replace(/\n\n/g, '\n') + block, // the blank lines collapsed
        prose.replace(/^/gm, '\t') + block, // every line indented with a tab
        prose.replace(/ /g, '\u00a0') + block, // non-breaking spaces from a word processor
        prose.replace(/ /g, '\u3000') + block, // ideographic spaces
        prose.replace('Handsontable', 'Hands\nontable') + block, // a line break inside a word
        `\ufeff${SUBSCRIPTION_KEY}`, // a byte order mark from a file
      ].forEach((variant) => {
        expect(variant).not.toBe(SUBSCRIPTION_KEY);
        expect(extractEntitlementKeyData(variant)).toEqual(expected());
      });
    });

    it('should read a key whose line breaks were saved as text, as some .env files and CI secrets do', () => {
      const prose = proseOf(SUBSCRIPTION_KEY);
      const block = blockOf(SUBSCRIPTION_KEY);

      [
        prose.replace(/\n/g, '\\n') + block, // "\n" as two characters
        prose.replace(/\n/g, '\\r\\n') + block, // "\r\n" as four characters
        prose.replace(/\n/g, '\\n').replace(/ /g, '\\t') + block, // "\t" as two characters
        `${prose.replace(/\n/g, '\\n') + block}\n`, // and a real trailing newline
        `${prose.replace(/\n/g, '\\n') + block}\\n`, // and a trailing newline saved as text, too
        `${prose.replace(/\n/g, '\\r\\n') + block}\\r\\n`,
      ].forEach((variant) => {
        expect(variant).not.toContain('\n\n');
        expect(extractEntitlementKeyData(variant)).toEqual(expected());
      });
    });

    it('should reject a key that a store changed instead of only rewrapping it', () => {
      const prose = proseOf(SUBSCRIPTION_KEY);
      const block = blockOf(SUBSCRIPTION_KEY);

      [
        prose.replace(/\n/g, '\\\\n') + block, // line breaks escaped twice ("\\n") - a backslash is left
        prose.replace(/\n/g, '/n') + block, // a wrong escape
        prose.replace(/"/g, '') + block, // the quotes around the project name removed
        prose.replace(/"/g, '\'') + block, // ... or swapped for apostrophes
        prose.replace('"Fixture Project"', '\u201cFixture Project\u201d') + block, // curly quotes
        `"${SUBSCRIPTION_KEY}"`, // the key kept inside its JSON quotes
        `'${SUBSCRIPTION_KEY}'`,
        prose.split('\n')[0] + block, // a store that kept the first line only
      ].forEach((variant) => {
        expect(extractEntitlementKeyData(variant)).toBeNull();
      });
    });

    it('should reject a key whose block was broken by a line wrap', () => {
      const block = blockOf(SUBSCRIPTION_KEY);
      const prose = proseOf(SUBSCRIPTION_KEY);

      ['\n', '\r\n', ' ', '\\n'].forEach((separator) => {
        const wrapped = `${prose}${block.slice(0, 60)}${separator}${block.slice(60)}`;

        expect(extractEntitlementKeyData(wrapped)).toBeNull();
      });
    });

    it('should read a key whose prose has composed characters, also when it is stored decomposed (NFD)', () => {
      const decomposed = ACCENTED_HOLDER_KEY.normalize('NFD');

      expect(ACCENTED_HOLDER_KEY).toBe(ACCENTED_HOLDER_KEY.normalize('NFC'));
      expect(decomposed).not.toBe(ACCENTED_HOLDER_KEY);
      expect(extractEntitlementKeyData(ACCENTED_HOLDER_KEY)).toEqual(expected());
      expect(extractEntitlementKeyData(decomposed)).toEqual(expected());
      expect(extractEntitlementKeyData(ACCENTED_HOLDER_KEY.replace('\u00fc', 'u'))).toBeNull();
    });

    it('should read a key whose CJK prose was wrapped between two CJK characters', () => {
      const prose = proseOf(CJK_HOLDER_KEY);
      const block = blockOf(CJK_HOLDER_KEY);
      const holder = '\u682a\u5f0f\u4f1a\u793e\u30c6\u30b9\u30c8\u30d5\u30a3\u30af\u30b9\u30c1\u30e3';

      expect(prose).toContain(holder);
      expect(extractEntitlementKeyData(CJK_HOLDER_KEY)).toEqual(expected());

      for (let i = 1; i < holder.length; i++) {
        const wrapped = prose.replace(holder, `${holder.slice(0, i)}\n${holder.slice(i)}`);

        expect(extractEntitlementKeyData(wrapped + block)).toEqual(expected());
      }

      expect(extractEntitlementKeyData(prose.replace(holder, holder.slice(1)) + block)).toBeNull();
    });

    it('should never let the prose and the payload trade characters across the boundary', () => {
      // The canonical prose has no whitespace and no "\n", so the "\n" the checksum puts between the
      // two parts cannot be forged from either side.
      expect(canonicalizeProse(proseOf(SUBSCRIPTION_KEY))).not.toMatch(/\s/);
      expect(canonicalizeProse('a \\n b\n\tc\u3000d')).toBe('abcd');
    });
  });

  describe('integrity', () => {
    it('should reject a key whose checksum does not match its payload', () => {
      const key = buildTestKey({ products: { handsontable: handsontableEntry() } });

      expect(extractEntitlementKeyData(key)).not.toBeNull();
      expect(extractEntitlementKeyData(`${key.slice(0, -2)}00]`)).toBeNull();
    });

    it('should reject a key whose payload was edited under an intact-looking block', () => {
      // The last character of the encoded payload, one position before the 128-character checksum.
      const payloadEnd = SUBSCRIPTION_KEY.length - 1 - 128;
      const tampered = `${SUBSCRIPTION_KEY.slice(0, payloadEnd - 1)}X${SUBSCRIPTION_KEY.slice(payloadEnd)}`;

      expect(tampered).not.toBe(SUBSCRIPTION_KEY);
      expect(extractEntitlementKeyData(tampered)).toBeNull();
    });

    it('should reject a key with no block, an unterminated block, or an empty one', () => {
      expect(extractEntitlementKeyData('This is a Handsontable license key for Test Fixture.')).toBeNull();
      // The closing bracket dropped, so the block never terminates.
      expect(extractEntitlementKeyData(SUBSCRIPTION_KEY.slice(0, -1))).toBeNull();
      expect(extractEntitlementKeyData('[]')).toBeNull();
      expect(extractEntitlementKeyData('')).toBeNull();
    });

    it('should reject a block whose content is not base64url plus a hex checksum', () => {
      const key = buildTestKey({ products: { handsontable: handsontableEntry() } });

      // A character outside the base64url alphabet, injected at the head of the block.
      const blockStart = key.lastIndexOf('[') + 1;

      expect(extractEntitlementKeyData(`${key.slice(0, blockStart)}!${key.slice(blockStart)}`)).toBeNull();
      expect(extractEntitlementKeyData(buildTestKey(
        { products: { handsontable: handsontableEntry() } },
        { checksum: 'Z'.repeat(128) },
      ))).toBeNull();
    });

    it('should reject a payload that is not JSON, or not a product map', () => {
      expect(extractEntitlementKeyData(buildTestKey('not an object'))).toBeNull();
      expect(extractEntitlementKeyData(buildTestKey({ products: [] }))).toBeNull();
      expect(extractEntitlementKeyData(buildTestKey({}))).toBeNull();
    });
  });

  describe('shape - strict', () => {
    it('should reject a product carrying both dates (J10)', () => {
      expect(extractEntitlementKeyData(buildTestKey({
        products: { handsontable: handsontableEntry({ release_until: SUBSCRIPTION_UNTIL }) },
      }))).toBeNull();
    });

    it('should reject a product carrying neither date (J10)', () => {
      const entry = handsontableEntry();

      delete entry.usage_until;

      expect(extractEntitlementKeyData(buildTestKey({ products: { handsontable: entry } }))).toBeNull();
    });

    it('should reject every date spelling that is not a real bare YYYY-MM-DD (J6)', () => {
      ['2027-8-12', '12-08-2027', '2027-08-12T00:00:00Z', 1786455012, '2027-02-30', '', null]
        .forEach((date) => {
          expect(extractEntitlementKeyData(buildTestKey({
            products: { handsontable: handsontableEntry({ usage_until: date }) },
          }))).toBeNull();
        });
    });

    it('should accept a real leap day (J7)', () => {
      expect(extractEntitlementKeyData(buildTestKey({
        products: { handsontable: handsontableEntry({ usage_until: '2028-02-29' }) },
      }))).not.toBeNull();
    });

    it('should reject a window that is not a non-negative integer', () => {
      [-1, 1.5, '60', null].forEach((notice) => {
        expect(extractEntitlementKeyData(buildTestKey({
          products: { handsontable: handsontableEntry({ notice }) },
        }))).toBeNull();
      });
    });

    it('should reject a window that decodes to Infinity', () => {
      // `1e999` is valid JSON and parses to Infinity, which would make every date computed from it
      // non-finite. It cannot be written as a literal here (it loses precision at parse time), so
      // the payload JSON is handed over raw.
      const rawPayloadJson = '{"products":{"handsontable":{"capabilities":["core"],' +
        '"usage_until":"2027-08-12","notice":60,"grace":1e999,"flags":[]}}}';

      expect(extractEntitlementKeyData(buildTestKey(null, { rawPayloadJson }))).toBeNull();
    });

    it('should reject a product with no capability list', () => {
      const entry = handsontableEntry();

      delete entry.capabilities;

      expect(extractEntitlementKeyData(buildTestKey({ products: { handsontable: entry } }))).toBeNull();
    });

    it('should reject the whole key when any product entry is malformed', () => {
      expect(extractEntitlementKeyData(buildTestKey({
        products: {
          handsontable: handsontableEntry(),
          hyperformula: { capabilities: ['functions_1'] },
        },
      }))).toBeNull();
    });
  });

  describe('vocabulary - lenient', () => {
    it('should keep an unrecognized capability token instead of failing (E6)', () => {
      const data = extractEntitlementKeyData(buildTestKey({
        products: { handsontable: handsontableEntry({ capabilities: ['core', 'solver'] }) },
      }));

      expect(getProductEntitlement(data, 'handsontable').capabilities).toEqual(['core', 'solver']);
    });

    it('should keep an unrecognized flag instead of failing (E6)', () => {
      const data = extractEntitlementKeyData(buildTestKey({
        products: { handsontable: handsontableEntry({ flags: ['custom', 'not-a-flag'] }) },
      }));

      expect(getProductEntitlement(data, 'handsontable').flags).toEqual(['custom', 'not-a-flag']);
    });

    it('should keep an unrecognized product instead of failing', () => {
      const data = extractEntitlementKeyData(buildTestKey({
        products: {
          handsontable: handsontableEntry(),
          spreadsheet_viewer: handsontableEntry({ capabilities: ['viewer'] }),
        },
      }));

      expect(Object.keys(data.products)).toEqual(['handsontable', 'spreadsheet_viewer']);
    });

    it('should keep a field the format grows later', () => {
      const data = extractEntitlementKeyData(buildTestKey({
        products: { handsontable: handsontableEntry({ seats: 25 }) },
      }));

      expect(getProductEntitlement(data, 'handsontable').seats).toBe(25);
    });

    it('should read an absent flags array exactly as an empty one (E8)', () => {
      const entry = handsontableEntry();

      delete entry.flags;

      const data = extractEntitlementKeyData(buildTestKey({ products: { handsontable: entry } }));

      expect(getProductEntitlement(data, 'handsontable').flags).toEqual([]);
    });
  });

  describe('hardening', () => {
    it('should not let a product named "__proto__" reach the prototype chain', () => {
      const products = { handsontable: handsontableEntry() };

      // Defined, not assigned: a plain `__proto__:` in an object literal sets the prototype instead
      // of adding the property, so it would never reach the serialized payload at all.
      Object.defineProperty(products, '__proto__', {
        value: handsontableEntry(), enumerable: true, writable: true, configurable: true,
      });

      const data = extractEntitlementKeyData(buildTestKey({ products }));

      expect(data).not.toBeNull();
      expect(Object.prototype.hasOwnProperty.call(data.products, '__proto__')).toBe(true);
      expect({}.capabilities).toBeUndefined();
    });

    it('should not trust a product entry that overrides hasOwnProperty', () => {
      const data = extractEntitlementKeyData(buildTestKey({
        products: { handsontable: handsontableEntry({ hasOwnProperty: 'nope' }) },
      }));

      expect(getProductEntitlement(data, 'handsontable')).not.toBeNull();
      expect(getProductEntitlement(data, 'hyperformula')).toBeNull();
    });

    it('should return the same object for a repeated read of the same key', () => {
      expect(extractEntitlementKeyData(SUBSCRIPTION_KEY)).toBe(extractEntitlementKeyData(SUBSCRIPTION_KEY));
    });

    it('should re-read when the key changes', () => {
      const first = extractEntitlementKeyData(SUBSCRIPTION_KEY);

      extractEntitlementKeyData(TRIAL_KEY);

      expect(extractEntitlementKeyData(SUBSCRIPTION_KEY)).not.toBe(first);
      expect(extractEntitlementKeyData(SUBSCRIPTION_KEY)).toEqual(first);
    });
  });
});
