import { extractEntitlementKeyData, getProductEntitlement } from '../extractKeyData';
import { detectLicenseKeyFormat, isEntitlementKey } from '../detectFormat';
import { sha512 } from '../sha512';
import { stringToUtf8Bytes } from '../encoding';
import { buildTestKey } from './buildTestKey';
import {
  SUBSCRIPTION_KEY,
  SUBSCRIPTION_KEY_WITH_PROSE,
  SUBSCRIPTION_EXTERNAL_KEY,
  TRIAL_KEY,
  PERPETUAL_KEY,
  HF_ONLY_KEY,
  MIXED_KEY,
  SUBSCRIPTION_UNTIL,
  TRIAL_UNTIL,
} from './fixtures';

/**
 * A well-formed Handsontable product entry, with the fields a test does not care about filled in.
 *
 * @param {object} [overrides] The fields to change.
 * @returns {object}
 */
function handsontableEntry(overrides = {}) {
  return {
    capabilities: ['core'],
    usage_until: SUBSCRIPTION_UNTIL,
    notice: 60,
    grace: 90,
    flags: [],
    ...overrides,
  };
}

describe('entitlementLicenseKey/sha512', () => {
  // Known-answer vectors from the SHA-512 specification (FIPS 180-4).
  it('should hash the empty input', () => {
    expect(sha512([])).toBe(
      'cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce' +
      '47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e'
    );
  });

  it('should hash "abc"', () => {
    expect(sha512(stringToUtf8Bytes('abc'))).toBe(
      'ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a' +
      '2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f'
    );
  });
});

describe('entitlementLicenseKey/detectFormat', () => {
  it('should recognize an entitlement key by its trailing block', () => {
    expect(detectLicenseKeyFormat(SUBSCRIPTION_KEY)).toBe('entitlement');
    expect(detectLicenseKeyFormat(SUBSCRIPTION_KEY_WITH_PROSE)).toBe('entitlement');
    expect(isEntitlementKey(SUBSCRIPTION_KEY_WITH_PROSE)).toBe(true);
  });

  it('should tell the other key formats apart without validating them', () => {
    expect(detectLicenseKeyFormat('852a2-94216-cca54-21009-14a44')).toBe('legacy');
    expect(detectLicenseKeyFormat('00000-00000-00000-00000-00000')).toBe('legacy');
    expect(detectLicenseKeyFormat('non-commercial-and-evaluation')).toBe('non-commercial-and-evaluation');
    expect(detectLicenseKeyFormat('NON-COMMERCIAL-AND-EVALUATION')).toBe('non-commercial-and-evaluation');
    // `gpl-v3` is NOT a Handsontable format - the specification's legacy list covers HyperFormula
    // too, and the frozen validator has never recognized it. It reads as an unknown string.
    expect(detectLicenseKeyFormat('gpl-v3')).toBe('unknown');
    expect(detectLicenseKeyFormat('')).toBe('unknown');
    expect(detectLicenseKeyFormat(undefined)).toBe('unknown');
    expect(detectLicenseKeyFormat(12345)).toBe('unknown');
  });

  it('should not route any non-entitlement key to the entitlement reader', () => {
    ['852a2-94216-cca54-21009-14a44', 'non-commercial-and-evaluation', 'gpl-v3', '', undefined, null]
      .forEach((key) => {
        expect(isEntitlementKey(key)).toBe(false);
      });
  });
});

describe('entitlementLicenseKey/extractKeyData', () => {
  describe('reading a key generated by the license-key package', () => {
    it('should read a subscription key', () => {
      const data = extractEntitlementKeyData(SUBSCRIPTION_KEY);

      expect(getProductEntitlement(data, 'handsontable')).toEqual({
        capabilities: ['core'],
        usage_until: SUBSCRIPTION_UNTIL,
        notice: 60,
        grace: 90,
        flags: [],
      });
    });

    it('should read a trial key', () => {
      const entitlement = getProductEntitlement(extractEntitlementKeyData(TRIAL_KEY), 'handsontable');

      expect(entitlement.usage_until).toBe(TRIAL_UNTIL);
      expect(entitlement.notice).toBe(45);
      expect(entitlement.grace).toBe(15);
      expect(entitlement.flags).toEqual(['trial']);
    });

    it('should read a perpetual key as a maintenance date, never as an expiry', () => {
      const entitlement = getProductEntitlement(extractEntitlementKeyData(PERPETUAL_KEY), 'handsontable');

      expect(entitlement.release_until).toBe('2027-08-12');
      expect(entitlement.usage_until).toBeUndefined();
    });

    it('should read the silencing flags of an externally-used key', () => {
      const entitlement = getProductEntitlement(extractEntitlementKeyData(SUBSCRIPTION_EXTERNAL_KEY), 'handsontable');

      expect(entitlement.flags).toEqual(['no-console-warns', 'no-ui-warns']);
    });

    it('should read every product of a key granting two, each on its own terms', () => {
      const data = extractEntitlementKeyData(MIXED_KEY);

      expect(getProductEntitlement(data, 'handsontable').usage_until).toBe(SUBSCRIPTION_UNTIL);
      expect(getProductEntitlement(data, 'hyperformula').release_until).toBe('2025-03-31');
    });

    it('should read a key whose product map is empty, granting nothing (H5)', () => {
      const data = extractEntitlementKeyData(buildTestKey({ products: {} }));

      expect(data).toEqual({ products: {} });
      expect(getProductEntitlement(data, 'handsontable')).toBeNull();
    });

    it('should read a key that grants no Handsontable license, leaving the verdict to the caller', () => {
      const data = extractEntitlementKeyData(HF_ONLY_KEY);

      expect(data).not.toBeNull();
      expect(getProductEntitlement(data, 'handsontable')).toBeNull();
      expect(getProductEntitlement(data, 'hyperformula')).not.toBeNull();
    });
  });

  describe('the prose layer', () => {
    it('should read the complete artifact exactly as the block on its own', () => {
      expect(extractEntitlementKeyData(SUBSCRIPTION_KEY_WITH_PROSE))
        .toEqual(extractEntitlementKeyData(SUBSCRIPTION_KEY));
    });

    it('should survive prose that was rewritten, rewrapped, or replaced entirely', () => {
      const block = SUBSCRIPTION_KEY;

      ['Anything at all.\n\n', 'Line one\nline two\n\n', '   ', '[not a block] '].forEach((prose) => {
        expect(extractEntitlementKeyData(prose + block)).not.toBeNull();
      });
    });

    it('should reject a key whose block was broken by a line wrap', () => {
      const block = SUBSCRIPTION_KEY;
      const wrapped = `${block.slice(0, 60)}\n${block.slice(60)}`;

      expect(extractEntitlementKeyData(wrapped)).toBeNull();
    });
  });

  describe('integrity', () => {
    it('should reject a key whose checksum does not match its payload', () => {
      const key = buildTestKey({ products: { handsontable: handsontableEntry() } });

      expect(extractEntitlementKeyData(key)).not.toBeNull();
      expect(extractEntitlementKeyData(`${key.slice(0, -2)}00]`)).toBeNull();
    });

    it('should reject a key whose payload was edited under an intact-looking block', () => {
      // The last character of the encoded payload, one position before the 128-character checksum.
      const payloadEnd = SUBSCRIPTION_KEY.length - 1 - 128;
      const tampered = `${SUBSCRIPTION_KEY.slice(0, payloadEnd - 1)}X${SUBSCRIPTION_KEY.slice(payloadEnd)}`;

      expect(tampered).not.toBe(SUBSCRIPTION_KEY);
      expect(extractEntitlementKeyData(tampered)).toBeNull();
    });

    it('should reject a key with no block, an unterminated block, or an empty one', () => {
      expect(extractEntitlementKeyData('This is a Handsontable license key for Test Fixture.')).toBeNull();
      // The closing bracket dropped, so the block never terminates.
      expect(extractEntitlementKeyData(SUBSCRIPTION_KEY.slice(0, -1))).toBeNull();
      expect(extractEntitlementKeyData('[]')).toBeNull();
      expect(extractEntitlementKeyData('')).toBeNull();
    });

    it('should reject a block whose content is not base64url plus a hex checksum', () => {
      const key = buildTestKey({ products: { handsontable: handsontableEntry() } });

      // A character outside the base64url alphabet, injected at the head of the block.
      expect(extractEntitlementKeyData(`[!${key.slice(1)}`)).toBeNull();
      expect(extractEntitlementKeyData(buildTestKey(
        { products: { handsontable: handsontableEntry() } },
        { checksum: 'Z'.repeat(128) },
      ))).toBeNull();
    });

    it('should reject a payload that is not JSON, or not a product map', () => {
      expect(extractEntitlementKeyData(buildTestKey('not an object'))).toBeNull();
      expect(extractEntitlementKeyData(buildTestKey({ products: [] }))).toBeNull();
      expect(extractEntitlementKeyData(buildTestKey({}))).toBeNull();
    });
  });

  describe('shape - strict', () => {
    it('should reject a product carrying both dates (J10)', () => {
      expect(extractEntitlementKeyData(buildTestKey({
        products: { handsontable: handsontableEntry({ release_until: SUBSCRIPTION_UNTIL }) },
      }))).toBeNull();
    });

    it('should reject a product carrying neither date (J10)', () => {
      const entry = handsontableEntry();

      delete entry.usage_until;

      expect(extractEntitlementKeyData(buildTestKey({ products: { handsontable: entry } }))).toBeNull();
    });

    it('should reject every date spelling that is not a real bare YYYY-MM-DD (J6)', () => {
      ['2027-8-12', '12-08-2027', '2027-08-12T00:00:00Z', 1786455012, '2027-02-30', '', null]
        .forEach((date) => {
          expect(extractEntitlementKeyData(buildTestKey({
            products: { handsontable: handsontableEntry({ usage_until: date }) },
          }))).toBeNull();
        });
    });

    it('should accept a real leap day (J7)', () => {
      expect(extractEntitlementKeyData(buildTestKey({
        products: { handsontable: handsontableEntry({ usage_until: '2028-02-29' }) },
      }))).not.toBeNull();
    });

    it('should reject a window that is not a non-negative integer', () => {
      [-1, 1.5, '60', null].forEach((notice) => {
        expect(extractEntitlementKeyData(buildTestKey({
          products: { handsontable: handsontableEntry({ notice }) },
        }))).toBeNull();
      });
    });

    it('should reject a window that decodes to Infinity', () => {
      // `1e999` is valid JSON and parses to Infinity, which would make every date computed from it
      // non-finite. It cannot be written as a literal here (it loses precision at parse time), so
      // the payload JSON is handed over raw.
      const rawPayloadJson = '{"products":{"handsontable":{"capabilities":["core"],' +
        '"usage_until":"2027-08-12","notice":60,"grace":1e999,"flags":[]}}}';

      expect(extractEntitlementKeyData(buildTestKey(null, { rawPayloadJson }))).toBeNull();
    });

    it('should reject a product with no capability list', () => {
      const entry = handsontableEntry();

      delete entry.capabilities;

      expect(extractEntitlementKeyData(buildTestKey({ products: { handsontable: entry } }))).toBeNull();
    });

    it('should reject the whole key when any product entry is malformed', () => {
      expect(extractEntitlementKeyData(buildTestKey({
        products: {
          handsontable: handsontableEntry(),
          hyperformula: { capabilities: ['functions_1'] },
        },
      }))).toBeNull();
    });
  });

  describe('vocabulary - lenient', () => {
    it('should keep an unrecognized capability token instead of failing (E6)', () => {
      const data = extractEntitlementKeyData(buildTestKey({
        products: { handsontable: handsontableEntry({ capabilities: ['core', 'solver'] }) },
      }));

      expect(getProductEntitlement(data, 'handsontable').capabilities).toEqual(['core', 'solver']);
    });

    it('should keep an unrecognized flag instead of failing (E6)', () => {
      const data = extractEntitlementKeyData(buildTestKey({
        products: { handsontable: handsontableEntry({ flags: ['custom', 'not-a-flag'] }) },
      }));

      expect(getProductEntitlement(data, 'handsontable').flags).toEqual(['custom', 'not-a-flag']);
    });

    it('should keep an unrecognized product instead of failing', () => {
      const data = extractEntitlementKeyData(buildTestKey({
        products: {
          handsontable: handsontableEntry(),
          spreadsheet_viewer: handsontableEntry({ capabilities: ['viewer'] }),
        },
      }));

      expect(Object.keys(data.products)).toEqual(['handsontable', 'spreadsheet_viewer']);
    });

    it('should keep a field the format grows later', () => {
      const data = extractEntitlementKeyData(buildTestKey({
        products: { handsontable: handsontableEntry({ seats: 25 }) },
      }));

      expect(getProductEntitlement(data, 'handsontable').seats).toBe(25);
    });

    it('should read an absent flags array exactly as an empty one (E8)', () => {
      const entry = handsontableEntry();

      delete entry.flags;

      const data = extractEntitlementKeyData(buildTestKey({ products: { handsontable: entry } }));

      expect(getProductEntitlement(data, 'handsontable').flags).toEqual([]);
    });
  });

  describe('hardening', () => {
    it('should not let a product named "__proto__" reach the prototype chain', () => {
      const products = { handsontable: handsontableEntry() };

      // Defined, not assigned: a plain `__proto__:` in an object literal sets the prototype instead
      // of adding the property, so it would never reach the serialized payload at all.
      Object.defineProperty(products, '__proto__', {
        value: handsontableEntry(), enumerable: true, writable: true, configurable: true,
      });

      const data = extractEntitlementKeyData(buildTestKey({ products }));

      expect(data).not.toBeNull();
      expect(Object.prototype.hasOwnProperty.call(data.products, '__proto__')).toBe(true);
      expect({}.capabilities).toBeUndefined();
    });

    it('should not trust a product entry that overrides hasOwnProperty', () => {
      const data = extractEntitlementKeyData(buildTestKey({
        products: { handsontable: handsontableEntry({ hasOwnProperty: 'nope' }) },
      }));

      expect(getProductEntitlement(data, 'handsontable')).not.toBeNull();
      expect(getProductEntitlement(data, 'hyperformula')).toBeNull();
    });

    it('should return the same object for a repeated read of the same key', () => {
      expect(extractEntitlementKeyData(SUBSCRIPTION_KEY)).toBe(extractEntitlementKeyData(SUBSCRIPTION_KEY));
    });

    it('should re-read when the key changes', () => {
      const first = extractEntitlementKeyData(SUBSCRIPTION_KEY);

      extractEntitlementKeyData(TRIAL_KEY);

      expect(extractEntitlementKeyData(SUBSCRIPTION_KEY)).not.toBe(first);
      expect(extractEntitlementKeyData(SUBSCRIPTION_KEY)).toEqual(first);
    });
  });
});
