/**
 * Entitlement license key fixtures for the reader, classifier and grants unit tests.
 *
 * Every key here is generated by the AUTHORITATIVE `license-key` package (a different codebase from
 * the reader under test), so they prove cross-implementation format compatibility: a reader and a
 * hand-rolled builder that share the same misunderstanding of the format would agree with each
 * other, and only a fixture from the real generator catches it. For adversarial and edge cases,
 * forge keys with the in-test builder (`./buildTestKey`) instead.
 *
 * The holder is the obviously-fake "Test Fixture" on purpose, and every fixture mirrors one of the
 * worked examples of the license specification (the example id is named on each).
 *
 * Each `*_KEY` constant is the whole key, the text and the block. Every key except the `V1_*` ones
 * is in the current format, which protects its text, so the block on its own is not a valid key.
 * They were generated by the `license-key` generator released as 5.1.0 (the same output as its
 * pre-release commit 4c166fd) from the same records as the earlier fixtures, so the text and the
 * products are unchanged; the reader matches the canonical reader of `license-key` 5.1.0. The
 * `V1_*` keys were generated by `license-key` 4.0.1, in the earlier format - the one
 * the trial keys already issued use. Handsontable 18.1 reads both formats.
 *
 * Pin `Date.now` in tests; never rely on the real clock.
 */

/* eslint-disable max-len */

/**
 * The dates the fixtures are issued against, as the bare strings the payload carries.
 *
 * @type {string}
 */
export const SUBSCRIPTION_UNTIL = '2027-08-12';
export const TRIAL_UNTIL = '2026-09-26';
export const MAINTENANCE_UNTIL = '2027-08-12';

/**
 * Handsontable, `usage_until` 2027-08-12, notice 60, grace 90, no flags (example A1).
 *
 * @type {string}
 */
export const SUBSCRIPTION_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Subscription license under Handsontable Subscription License Agreement 2.0 of 2022-05-21, for Handsontable on the Enterprise package, for internal use, valid until 2027-08-12 (UTC). Use after that date is not permitted. To renew, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI3LTA4LTEyIiwibm90aWNlIjo2MCwiZ3JhY2UiOjkwLCJmbGFncyI6W119fSwidiI6MiwicHJvc2UiOiIwNjIzNWUxYjY5ZmQ1YjNmNjg2NjdhNTcxNmU5YWY5YWU5YTkxYjNkNzc5ZTBlY2FkODIyMjQ2NDU1YjUxZTA0In0e9c5c2a5838f3daf149124a7ad1a4e30710d8367b4814bb1a0092032677fa10fb605cb4325db23ae9078a30024d5df992c12074ab7a31321ef237d22573316fc]`;

/**
 * As above, issued for external use, so both silencing flags are set (example A2).
 *
 * @type {string}
 */
export const SUBSCRIPTION_EXTERNAL_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Subscription license under Handsontable Subscription License Agreement 2.0 of 2022-05-21, for Handsontable on the Enterprise package, for external use, valid until 2027-08-12 (UTC). Use after that date is not permitted. To renew, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI3LTA4LTEyIiwibm90aWNlIjo2MCwiZ3JhY2UiOjkwLCJmbGFncyI6WyJuby1jb25zb2xlLXdhcm5zIiwibm8tdWktd2FybnMiXX19LCJ2IjoyLCJwcm9zZSI6IjM1MTdlM2I0OTcyN2Q4MTRlZThlYzY5YWZlOWIwZjJjMWE3YWFmOTYwODc5ZTJlYTNlOTI3NzRhMjg5NDcwNmYifQd5c0390306d9214d72e9d2fe4cb70b658e29c92084b0be19ef2cf00fb79f02c408532752361d68c43e596701f0d56f7f5b41670f37f511fbf43e175b868a6c6e]`;

/**
 * Handsontable trial, `usage_until` 2026-09-26, notice 45, grace 15, flag `trial` (example A3).
 *
 * @type {string}
 */
export const TRIAL_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Trial license under Handsontable Evaluation License Agreement 4.0 of 2026-03-02, for Handsontable on the Enterprise package, for internal use, valid until 2026-09-26 (UTC). Not licensed for production use. To purchase a license, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI2LTA5LTI2Iiwibm90aWNlIjo0NSwiZ3JhY2UiOjE1LCJmbGFncyI6WyJ0cmlhbCJdfX0sInYiOjIsInByb3NlIjoiMzg3MzYxOTE5Yzc1YTQ0NTA4NGZmNmM1MmYwMmM0ZDJjNmMyMTVhYzc2YjFkMGRiYTZiMDkzODFmMDkwNjg1YSJ973a630de3fb4f97dd3d82647b57149489e48114b83ac7d5ca92d370a0be18246eecfedca9c2671de91a39840c8c2b6964b5756bf3fc2b7adbe0718167ea55b50]`;

/**
 * Handsontable, `release_until` 2027-08-12, notice 0, grace 0 (example A4).
 *
 * @type {string}
 */
export const PERPETUAL_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Perpetual license under Handsontable Perpetual License Agreement 2.0 of 2022-05-21, for Handsontable on the Enterprise package, for internal use. Maintenance and access to new versions both end on 2027-08-12. Versions released on or before that date may be used indefinitely. To renew maintenance, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwicmVsZWFzZV91bnRpbCI6IjIwMjctMDgtMTIiLCJub3RpY2UiOjAsImdyYWNlIjowLCJmbGFncyI6W119fSwidiI6MiwicHJvc2UiOiI2MzMwZWI1MWVjODdjNGI5Y2ZkY2JkZTFjZmFjNjE4M2RlZDYxZTgyY2Q1ODBhMzY5YWNkNDYzYzZkMDE0MWE0In076eaf0a9391b25029afb0aaacc9f109493fdd0aaaa9aff762c90f14dab1b327d7520ea3683a3585d497c8115d595c5d4787ba4194ab742a935815a0d66c8ba3d]`;

/**
 * A1 with the console silenced by request, the UI left alone (example A7).
 *
 * @type {string}
 */
export const NO_CONSOLE_WARNS_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Subscription license under Handsontable Subscription License Agreement 2.0 of 2022-05-21, for Handsontable on the Enterprise package, for internal use, valid until 2027-08-12 (UTC). Use after that date is not permitted. To renew, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI3LTA4LTEyIiwibm90aWNlIjo2MCwiZ3JhY2UiOjkwLCJmbGFncyI6WyJuby1jb25zb2xlLXdhcm5zIl19fSwidiI6MiwicHJvc2UiOiIwNjIzNWUxYjY5ZmQ1YjNmNjg2NjdhNTcxNmU5YWY5YWU5YTkxYjNkNzc5ZTBlY2FkODIyMjQ2NDU1YjUxZTA0In06005e380b7b82f3475a32465e3fc733cf9fc1fd837eb52576c4fb6032f8de01f5ac267593d1b4ed44a0305de62f584ab918752a2d9854fa15928cfa53727087f]`;

/**
 * A1 with the UI silenced by request, the console left alone (example A8).
 *
 * @type {string}
 */
export const NO_UI_WARNS_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Subscription license under Handsontable Subscription License Agreement 2.0 of 2022-05-21, for Handsontable on the Enterprise package, for internal use, valid until 2027-08-12 (UTC). Use after that date is not permitted. To renew, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI3LTA4LTEyIiwibm90aWNlIjo2MCwiZ3JhY2UiOjkwLCJmbGFncyI6WyJuby11aS13YXJucyJdfX0sInYiOjIsInByb3NlIjoiMDYyMzVlMWI2OWZkNWIzZjY4NjY3YTU3MTZlOWFmOWFlOWE5MWIzZDc3OWUwZWNhZDgyMjI0NjQ1NWI1MWUwNCJ91abdd30b6a6d8b5a5750e84cd843acea803b8500be07f46ff237b11abd4c23eb9223f4e5d1a9bb7f6ca168cb89e406a9bef9ef976af31e1f3138ea8dabf0a613]`;

/**
 * HyperFormula only - a checksum-valid key that is not a Handsontable license (example B1).
 *
 * @type {string}
 */
export const HF_ONLY_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Subscription license under Handsontable Subscription License Agreement 2.0 of 2022-05-21, for HyperFormula on the Essential package, for internal use, valid until 2027-08-12 (UTC). Use after that date is not permitted. To renew, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoeXBlcmZvcm11bGEiOnsiY2FwYWJpbGl0aWVzIjpbImZ1bmN0aW9uc18xIl0sInVzYWdlX3VudGlsIjoiMjAyNy0wOC0xMiIsIm5vdGljZSI6NjAsImdyYWNlIjo5MCwiZmxhZ3MiOltdfX0sInYiOjIsInByb3NlIjoiYzhjYmI0NzcyOGM2NGMyMzYwY2UxMDIyYTY2ZjZiMjUyN2JiNzljZmU3NmU2ODExNzQyMzc4Njk2ZmRjMTliMCJ90241b947442f6333b333ecf5fd30b069af1d3b4770813f53d7d617af8297b2a2766bd7270ee9b4160f9ab1585330cbd8761b4604eddd16e581038b2134dbdcac]`;

/**
 * Handsontable on `usage_until` 2027-08-12 plus HyperFormula on `release_until` 2025-03-31 (example C4).
 *
 * @type {string}
 */
export const MIXED_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 2 licenses:

> 1. Subscription license under Handsontable Subscription License Agreement 2.0 of 2022-05-21, for Handsontable on the Enterprise package, for internal use, valid until 2027-08-12 (UTC). Use after that date is not permitted. To renew, contact sales@handsontable.com.

> 2. Perpetual license under Handsontable Perpetual License Agreement 2.0 of 2022-05-21, for HyperFormula on the Pro package, for internal use. Maintenance and access to new versions both end on 2025-03-31. Versions released on or before that date may be used indefinitely. To renew maintenance, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI3LTA4LTEyIiwibm90aWNlIjo2MCwiZ3JhY2UiOjkwLCJmbGFncyI6W119LCJoeXBlcmZvcm11bGEiOnsiY2FwYWJpbGl0aWVzIjpbImZ1bmN0aW9uc18xIiwiZnVuY3Rpb25zXzIiXSwicmVsZWFzZV91bnRpbCI6IjIwMjUtMDMtMzEiLCJub3RpY2UiOjAsImdyYWNlIjowLCJmbGFncyI6W119fSwidiI6MiwicHJvc2UiOiI5NTQ5MGIzY2E1ZTEwZTVjMzdiYWM1NDc2NjQ1ZDI5NmYxNDA2MWEwZTUyZTY0M2VlM2Q3NmZmOGQ2MWVhYWVhIn059d68de72a5dbf77997715f328757fda1709ea9439d86491b86f795aa7c160914393013891ee0a724ef2b1123ead9bfc5821978d6c3703b20f440c42f39e31c7]`;

/**
 * A1 with `notice: 0` - quiet before expiry, loud after (example E2).
 *
 * @type {string}
 */
export const NO_NOTICE_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Subscription license under Handsontable Subscription License Agreement 2.0 of 2022-05-21, for Handsontable on the Enterprise package, for internal use, valid until 2027-08-12 (UTC). Use after that date is not permitted. To renew, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI3LTA4LTEyIiwibm90aWNlIjowLCJncmFjZSI6OTAsImZsYWdzIjpbXX19LCJ2IjoyLCJwcm9zZSI6IjA2MjM1ZTFiNjlmZDViM2Y2ODY2N2E1NzE2ZTlhZjlhZTlhOTFiM2Q3NzllMGVjYWQ4MjIyNDY0NTViNTFlMDQifQ54932996ff4ab4803f0fe24bec4329c534e541fe3b1e95f27dbc8f2faaf03fbe9f06d536cdcba6f8e0df22536279f6070ee1b7f695c24ea2d8a4a791f3f31384]`;

/**
 * Individually negotiated terms: `usage_until` 2029-12-31, notice 180, grace 180, flag `custom` (example E4).
 *
 * @type {string}
 */
export const CUSTOM_FLAG_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Subscription license under Handsontable Subscription License Agreement 2.0 of 2022-05-21, for Handsontable on the Enterprise package, for internal use, valid until 2029-12-31 (UTC). Use after that date is not permitted. To renew, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI5LTEyLTMxIiwibm90aWNlIjoxODAsImdyYWNlIjoxODAsImZsYWdzIjpbImN1c3RvbSJdfX0sInYiOjIsInByb3NlIjoiYTdiZmU2NjVlYzUzMzc4NjdiNmE0ZDJmMTBjYmUyZTE0ZTI3MjAyNDU1NTI1M2FmOGEwMGFmMjFkOTM1NWI5MiJ9e3d94a0ed95e3174788f0ee8a568f751d063c720b049840ae60c60c844c7787062e6ebd9ae4b41f4625d123e0751f476ba92ba94784ee4ac0fab9637c3d81e24]`;

/**
 * A trial with the console silenced by request - the badge, popover and bar stay (examples A3 + A7).
 *
 * @type {string}
 */
export const TRIAL_NO_CONSOLE_WARNS_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Trial license under Handsontable Evaluation License Agreement 4.0 of 2026-03-02, for Handsontable on the Enterprise package, for internal use, valid until 2026-09-26 (UTC). Not licensed for production use. To purchase a license, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI2LTA5LTI2Iiwibm90aWNlIjo0NSwiZ3JhY2UiOjE1LCJmbGFncyI6WyJ0cmlhbCIsIm5vLWNvbnNvbGUtd2FybnMiXX19LCJ2IjoyLCJwcm9zZSI6IjM4NzM2MTkxOWM3NWE0NDUwODRmZjZjNTJmMDJjNGQyYzZjMjE1YWM3NmIxZDBkYmE2YjA5MzgxZjA5MDY4NWEifQ52ae9c2cd1063dedd87ca7150a534436c56a5eabbd4daca4f85054527dfd21f1a58210a218e60b8bde8b5640cce1ebe5d29abc3771673ae2aed25b7586892a86]`;

/**
 * A trial with the UI silenced by request - only the console speaks (examples A3 + A8).
 *
 * @type {string}
 */
export const TRIAL_NO_UI_WARNS_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Trial license under Handsontable Evaluation License Agreement 4.0 of 2026-03-02, for Handsontable on the Enterprise package, for internal use, valid until 2026-09-26 (UTC). Not licensed for production use. To purchase a license, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI2LTA5LTI2Iiwibm90aWNlIjo0NSwiZ3JhY2UiOjE1LCJmbGFncyI6WyJ0cmlhbCIsIm5vLXVpLXdhcm5zIl19fSwidiI6MiwicHJvc2UiOiIzODczNjE5MTljNzVhNDQ1MDg0ZmY2YzUyZjAyYzRkMmM2YzIxNWFjNzZiMWQwZGJhNmIwOTM4MWYwOTA2ODVhIn0c1dccd7855f9004db2a062d37bdec85f616193de27387b34733659025c4b89e39d18db26e78546db6a8406bc791ae32ecdca985330896764429cc1cf4b1b80b5]`;

/**
 * A perpetual license with the UI silenced, so a lapsed maintenance date shows no bar (example A5).
 *
 * @type {string}
 */
export const PERPETUAL_NO_UI_WARNS_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Perpetual license under Handsontable Perpetual License Agreement 2.0 of 2022-05-21, for Handsontable on the Enterprise package, for internal use. Maintenance and access to new versions both end on 2027-08-12. Versions released on or before that date may be used indefinitely. To renew maintenance, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwicmVsZWFzZV91bnRpbCI6IjIwMjctMDgtMTIiLCJub3RpY2UiOjAsImdyYWNlIjowLCJmbGFncyI6WyJuby11aS13YXJucyJdfX0sInYiOjIsInByb3NlIjoiNjMzMGViNTFlYzg3YzRiOWNmZGNiZGUxY2ZhYzYxODNkZWQ2MWU4MmNkNTgwYTM2OWFjZDQ2M2M2ZDAxNDFhNCJ91e1cd7ca48909536fe8f7b4af70a2103e82b5803d9ca31509de3c825f69e0671d3a881fce825093b714d6aa05e97faed08f90ca5784e7e5fb6a5034d2cd911ec]`;

/**
 * A1 issued to a holder whose name has composed (NFC) characters - "\u00fc", "\u00d6", "\u0141" and
 * others. The checksum covers the prose in NFC, so this key proves that the reader normalizes the
 * prose the same way the generator does, and that a decomposed (NFD) copy still reads.
 *
 * @type {string}
 */
export const ACCENTED_HOLDER_KEY = `This is a Handsontable license key for Z\u00fcrich \u00d6d\u00f6n \u0141\u00f3d\u017a Ltd., issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Subscription license under Handsontable Subscription License Agreement 2.0 of 2022-05-21, for Handsontable on the Enterprise package, for internal use, valid until 2027-08-12 (UTC). Use after that date is not permitted. To renew, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI3LTA4LTEyIiwibm90aWNlIjo2MCwiZ3JhY2UiOjkwLCJmbGFncyI6W119fSwidiI6MiwicHJvc2UiOiJlZTIwZGRlOTMyMjJlNGYyNTYwMTg2MGE5ZmE5ZjhmYjI2MTg0ZDA0NzE1NTFjZTU1ZDQ3NDI3NDQ0MGUyODk5In0a4cec1a5c59b02b17dc516e79159179c02688586173ca9dbef4d9423b1e5a60f0e962b5dc0ac208f58d38689b09d48340e90a330e19a9073470019f66ecd485a]`;

/**
 * A1 issued to a holder whose name is written in Japanese, so the prose has runs of CJK characters
 * with no spaces between them - the text a mail client may break at any character.
 *
 * @type {string}
 */
export const CJK_HOLDER_KEY = `This is a Handsontable license key for \u682a\u5f0f\u4f1a\u793e\u30c6\u30b9\u30c8\u30d5\u30a3\u30af\u30b9\u30c1\u30e3, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Subscription license under Handsontable Subscription License Agreement 2.0 of 2022-05-21, for Handsontable on the Enterprise package, for internal use, valid until 2027-08-12 (UTC). Use after that date is not permitted. To renew, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI3LTA4LTEyIiwibm90aWNlIjo2MCwiZ3JhY2UiOjkwLCJmbGFncyI6W119fSwidiI6MiwicHJvc2UiOiJjZmI4YThiNDhlMmJiYzk3MjQ5YzI0MWY4ZjAyZDlkMWEzYzNhZGY1M2Y5ZTBmZTk2MjBhNTM1NWZmYzRhN2NjIn0d7b7438cd13b8426d4118d1699812ab19dfad443a15b21b5253453c5c94b0f24af92426b0e9461393b65e1496961bdae03ba7e03d0c295b99e03f929b40dae7b]`;

/**
 * The SUBSCRIPTION_KEY record as `license-key` 4.0.1 issued it, in the earlier format (example A1).
 *
 * @type {string}
 */
export const V1_SUBSCRIPTION_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Subscription license under Handsontable Subscription License Agreement 2.0 of 2022-05-21, for Handsontable on the Enterprise package, for internal use, valid until 2027-08-12 (UTC). Use after that date is not permitted. To renew, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI3LTA4LTEyIiwibm90aWNlIjo2MCwiZ3JhY2UiOjkwLCJmbGFncyI6W119fX03de5d59e480be17d3c8cd340cb242cab64cac7888cbfba6c975c194f6613b8103792a6929f66852d18c7ac27c8c25fa9ab8a25b5e25f331669746c833a4f8361]`;

/**
 * The TRIAL_KEY record as `license-key` 4.0.1 issued it - the shape of the trial keys the website
 * form still issues (example A3).
 *
 * @type {string}
 */
export const V1_TRIAL_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Trial license under Handsontable Evaluation License Agreement 4.0 of 2026-03-02, for Handsontable on the Enterprise package, for internal use, valid until 2026-09-26 (UTC). Not licensed for production use. To purchase a license, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI2LTA5LTI2Iiwibm90aWNlIjo0NSwiZ3JhY2UiOjE1LCJmbGFncyI6WyJ0cmlhbCJdfX19a687a9f4d0d496c1ec86d97d58e971b458995f1a68ca117a6b406fa2f179923dcd42a789e3c56426690cf12c89e70abfbb6f45b96ba55fe49386d9e1b0080f2c]`;
