/**
 * Entitlement license key fixtures for the reader, classifier and grants unit tests.
 *
 * Every key here is generated by the AUTHORITATIVE `license-key` package (a different codebase from
 * the reader under test), so they prove cross-implementation format compatibility: a reader and a
 * hand-rolled builder that share the same misunderstanding of the format would agree with each
 * other, and only a fixture from the real generator catches it. For adversarial and edge cases,
 * forge keys with the in-test builder (`./buildTestKey`) instead.
 *
 * The holder is the obviously-fake "Test Fixture" on purpose, and every fixture mirrors one of the
 * worked examples of the license specification (the example id is named on each).
 *
 * The `*_KEY` constants are the machine-readable block on its own, which reads exactly like the
 * whole artifact - the prose is not covered by the checksum. `SUBSCRIPTION_KEY_WITH_PROSE` is the
 * one complete key, kept so the prose-tolerance rule stays covered.
 *
 * Pin `Date.now` in tests; never rely on the real clock.
 */

/* eslint-disable max-len */

/**
 * The dates the fixtures are issued against, as the bare strings the payload carries.
 *
 * @type {string}
 */
export const SUBSCRIPTION_UNTIL = '2027-08-12';
export const TRIAL_UNTIL = '2026-09-26';
export const MAINTENANCE_UNTIL = '2027-08-12';

/**
 * Handsontable, `usage_until` 2027-08-12, notice 60, grace 90, no flags (example A1).
 *
 * @type {string}
 */
export const SUBSCRIPTION_KEY = '[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI3LTA4LTEyIiwibm90aWNlIjo2MCwiZ3JhY2UiOjkwLCJmbGFncyI6W119fX03de5d59e480be17d3c8cd340cb242cab64cac7888cbfba6c975c194f6613b8103792a6929f66852d18c7ac27c8c25fa9ab8a25b5e25f331669746c833a4f8361]';

/**
 * As above, issued for external use, so both silencing flags are set (example A2).
 *
 * @type {string}
 */
export const SUBSCRIPTION_EXTERNAL_KEY = '[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI3LTA4LTEyIiwibm90aWNlIjo2MCwiZ3JhY2UiOjkwLCJmbGFncyI6WyJuby1jb25zb2xlLXdhcm5zIiwibm8tdWktd2FybnMiXX19fQbf6f3e8356a12fe1b2553ccd263dbc9a6f94c1fdc1aab949b3550865cb150c79027aa06a11c7618d5cbd1e14c4b73dc35f6bb81cd8c33c474194d082e2951106]';

/**
 * Handsontable trial, `usage_until` 2026-09-26, notice 45, grace 15, flag `trial` (example A3).
 *
 * @type {string}
 */
export const TRIAL_KEY = '[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI2LTA5LTI2Iiwibm90aWNlIjo0NSwiZ3JhY2UiOjE1LCJmbGFncyI6WyJ0cmlhbCJdfX19a687a9f4d0d496c1ec86d97d58e971b458995f1a68ca117a6b406fa2f179923dcd42a789e3c56426690cf12c89e70abfbb6f45b96ba55fe49386d9e1b0080f2c]';

/**
 * Handsontable, `release_until` 2027-08-12, notice 0, grace 0 (example A4).
 *
 * @type {string}
 */
export const PERPETUAL_KEY = '[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwicmVsZWFzZV91bnRpbCI6IjIwMjctMDgtMTIiLCJub3RpY2UiOjAsImdyYWNlIjowLCJmbGFncyI6W119fX00065b06ae41f7d6a7eba9552db7dc97a1c2c9aa809d58fe31ce5474541fed536fe018324cb8e1cf56ca86a39e1b193a005a0d5e16298e065f9424b97e1262e3a]';

/**
 * A1 with the console silenced by request, the UI left alone (example A7).
 *
 * @type {string}
 */
export const NO_CONSOLE_WARNS_KEY = '[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI3LTA4LTEyIiwibm90aWNlIjo2MCwiZ3JhY2UiOjkwLCJmbGFncyI6WyJuby1jb25zb2xlLXdhcm5zIl19fX0e8024d8aa137ea69d18125485c53f8e014e6910059383a657fec7193de59e456b55865c91bc04fe2cd0e93260fc8b398cf9352908011ffa18eaa66665e54bd02]';

/**
 * A1 with the UI silenced by request, the console left alone (example A8).
 *
 * @type {string}
 */
export const NO_UI_WARNS_KEY = '[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI3LTA4LTEyIiwibm90aWNlIjo2MCwiZ3JhY2UiOjkwLCJmbGFncyI6WyJuby11aS13YXJucyJdfX190428756425f781d2cc83b29ddac1ba2072c9414e94f1abdcbd55e14c024f8fd6cdbcd07ba2a6cd35e5686be525e914b9293bc9685206f261e39a323fb6edf1fa]';

/**
 * HyperFormula only - a checksum-valid key that is not a Handsontable license (example B1).
 *
 * @type {string}
 */
export const HF_ONLY_KEY = '[eyJwcm9kdWN0cyI6eyJoeXBlcmZvcm11bGEiOnsiY2FwYWJpbGl0aWVzIjpbImZ1bmN0aW9uc18xIl0sInVzYWdlX3VudGlsIjoiMjAyNy0wOC0xMiIsIm5vdGljZSI6NjAsImdyYWNlIjo5MCwiZmxhZ3MiOltdfX1950c11d5d71342f92b041a2429c9f40e40b14738d6920d01df955c551701197c39ff659872d1341a3d3d8aec098495a1676143880291dc4ca4f072396ad8dc42b]';

/**
 * Handsontable on `usage_until` 2027-08-12 plus HyperFormula on `release_until` 2025-03-31 (example C4).
 *
 * @type {string}
 */
export const MIXED_KEY = '[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI3LTA4LTEyIiwibm90aWNlIjo2MCwiZ3JhY2UiOjkwLCJmbGFncyI6W119LCJoeXBlcmZvcm11bGEiOnsiY2FwYWJpbGl0aWVzIjpbImZ1bmN0aW9uc18xIiwiZnVuY3Rpb25zXzIiXSwicmVsZWFzZV91bnRpbCI6IjIwMjUtMDMtMzEiLCJub3RpY2UiOjAsImdyYWNlIjowLCJmbGFncyI6W119fX0fc27742ba8bd686d2d9a8edc93e99730ee30d46c4406299140a3682e0c3c36f0d681a57b894d0480ff282f128ce1acfc4fd704914ae651616265c91a2c8bee03]';

/**
 * A1 with `notice: 0` - quiet before expiry, loud after (example E2).
 *
 * @type {string}
 */
export const NO_NOTICE_KEY = '[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI3LTA4LTEyIiwibm90aWNlIjowLCJncmFjZSI6OTAsImZsYWdzIjpbXX19fQ0d5cd3b6b00d7c6e77e4d03fcd3b609a1b17d2ee1f04afc6d0d3246aaaaae28f06629e83a4bb9309bd891bbb83e20f720ae65fef9c123b89b5c047b7c55a4a3f]';

/**
 * Individually negotiated terms: `usage_until` 2029-12-31, notice 180, grace 180, flag `custom` (example E4).
 *
 * @type {string}
 */
export const CUSTOM_FLAG_KEY = '[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI5LTEyLTMxIiwibm90aWNlIjoxODAsImdyYWNlIjoxODAsImZsYWdzIjpbImN1c3RvbSJdfX196c74d52c783f41f16150492eeebf09806f6fdae81a1f4617eb755bf5fcfd303afd18df4e957ca4585269188f0c3d3d628560e313c0b0bc99d96a1d0be3fa8b62]';

/**
 * A trial with the console silenced by request - the badge, popover and bar stay (examples A3 + A7).
 *
 * @type {string}
 */
export const TRIAL_NO_CONSOLE_WARNS_KEY = '[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI2LTA5LTI2Iiwibm90aWNlIjo0NSwiZ3JhY2UiOjE1LCJmbGFncyI6WyJ0cmlhbCIsIm5vLWNvbnNvbGUtd2FybnMiXX19fQd46b908f88f5bb066023835791d733bfcfe080b5b455157207d2e47d8afee20ba225b795f67e64b4030f2d30e7d42bff20afbb38380dcc1b65357461f7a24c19]';

/**
 * A trial with the UI silenced by request - only the console speaks (examples A3 + A8).
 *
 * @type {string}
 */
export const TRIAL_NO_UI_WARNS_KEY = '[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI2LTA5LTI2Iiwibm90aWNlIjo0NSwiZ3JhY2UiOjE1LCJmbGFncyI6WyJ0cmlhbCIsIm5vLXVpLXdhcm5zIl19fX0dbeff87ec565b90d59175cd5aa86b93abd4164fc2967f9156e289f5db90f0b8c19ddfb44efd92a165b2d1c568c0097c78c243701acf200487372dc8b45a0f1be]';

/**
 * A perpetual license with the UI silenced, so a lapsed maintenance date shows no bar (example A5).
 *
 * @type {string}
 */
export const PERPETUAL_NO_UI_WARNS_KEY = '[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwicmVsZWFzZV91bnRpbCI6IjIwMjctMDgtMTIiLCJub3RpY2UiOjAsImdyYWNlIjowLCJmbGFncyI6WyJuby11aS13YXJucyJdfX19f99c791278f85a3af95d7af29340f3a6660d2067e193e3dc879c54a7467087c8e0ec2b849129b7c2835c9d580b225c69f64503d3851ecdcb06dd487550fae047]';

/**
 * A perpetual license with the console silenced, so a lapsed maintenance date speaks only
 * through the bar (examples A4 + A7).
 *
 * @type {string}
 */
export const PERPETUAL_NO_CONSOLE_WARNS_KEY = '[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwicmVsZWFzZV91bnRpbCI6IjIwMjctMDgtMTIiLCJub3RpY2UiOjAsImdyYWNlIjowLCJmbGFncyI6WyJuby1jb25zb2xlLXdhcm5zIl19fX0bb952faf3cbaae6d8c70ca8c1242eb2cfd71476d0882f2860f193891b8f592de3627580ba3786ba9636fa4c219830ad4523aa2a257bf06487b336e70eec0c24d]';

/**
 * The complete A1 artifact - the prose the customer reads, then the block. It reads identically to
 * `SUBSCRIPTION_KEY`, which is the point: the prose is neither parsed nor checksummed.
 *
 * @type {string}
 */
export const SUBSCRIPTION_KEY_WITH_PROSE = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Subscription license under Handsontable Subscription License Agreement 2.0 of 2022-05-21, for Handsontable on the Enterprise package, for internal use, valid until 2027-08-12 (UTC). Use after that date is not permitted. To renew, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI3LTA4LTEyIiwibm90aWNlIjo2MCwiZ3JhY2UiOjkwLCJmbGFncyI6W119fX03de5d59e480be17d3c8cd340cb242cab64cac7888cbfba6c975c194f6613b8103792a6929f66852d18c7ac27c8c25fa9ab8a25b5e25f331669746c833a4f8361]`;
