/**
 * Entitlement license key fixtures for the reader, classifier and grants unit tests.
 *
 * Every key here is generated by the AUTHORITATIVE `license-key` package (a different codebase from
 * the reader under test), so they prove cross-implementation format compatibility: a reader and a
 * hand-rolled builder that share the same misunderstanding of the format would agree with each
 * other, and only a fixture from the real generator catches it. For adversarial and edge cases,
 * forge keys with the in-test builder (`./buildTestKey`) instead.
 *
 * The holder is the obviously-fake "Test Fixture" on purpose, and every fixture mirrors one of the
 * worked examples of the license specification (the example id is named on each).
 *
 * Each `*_KEY` constant is the whole key, the prose and the block, because the checksum covers both:
 * the block on its own is not a valid key. The keys were generated by `license-key` at commit
 * 7ca2899 (DEV-3253, before the 5.0.0 tag) and carry exactly the payloads of the earlier 4.x
 * fixtures. The checksum rules of the reader here match bc03d89, and every key below still
 * validates there. Regenerate them if the checksum recipe changes before that release.
 *
 * Pin `Date.now` in tests; never rely on the real clock.
 */

/* eslint-disable max-len */

/**
 * The dates the fixtures are issued against, as the bare strings the payload carries.
 *
 * @type {string}
 */
export const SUBSCRIPTION_UNTIL = '2027-08-12';
export const TRIAL_UNTIL = '2026-09-26';
export const MAINTENANCE_UNTIL = '2027-08-12';

/**
 * Handsontable, `usage_until` 2027-08-12, notice 60, grace 90, no flags (example A1).
 *
 * @type {string}
 */
export const SUBSCRIPTION_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Subscription license under Handsontable Subscription License Agreement 2.0 of 2022-05-21, for Handsontable on the Enterprise package, for internal use, valid until 2027-08-12 (UTC). Use after that date is not permitted. To renew, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI3LTA4LTEyIiwibm90aWNlIjo2MCwiZ3JhY2UiOjkwLCJmbGFncyI6W119fX0c4401c19afaf11f9c2f8df05b6aa3dc4bad6cdbbf7a535e77d4e3d95c137cf9d59a05bbc73ec35f6bdce3e3a1cfc18170c9662c877ee0477e2615fe32ab1b044]`;

/**
 * As above, issued for external use, so both silencing flags are set (example A2).
 *
 * @type {string}
 */
export const SUBSCRIPTION_EXTERNAL_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Subscription license under Handsontable Subscription License Agreement 2.0 of 2022-05-21, for Handsontable on the Enterprise package, for external use, valid until 2027-08-12 (UTC). Use after that date is not permitted. To renew, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI3LTA4LTEyIiwibm90aWNlIjo2MCwiZ3JhY2UiOjkwLCJmbGFncyI6WyJuby1jb25zb2xlLXdhcm5zIiwibm8tdWktd2FybnMiXX19fQ54053e73eda38c08afbd0554d564ecf1d7b03bb93ea2ca739e4cd441049667a256a3b28f595e2e265373356f2a065aa70721a6594ff1441c13e400cc3a093c37]`;

/**
 * Handsontable trial, `usage_until` 2026-09-26, notice 45, grace 15, flag `trial` (example A3).
 *
 * @type {string}
 */
export const TRIAL_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Trial license under Handsontable Evaluation License Agreement 4.0 of 2026-03-02, for Handsontable on the Enterprise package, for internal use, valid until 2026-09-26 (UTC). Not licensed for production use. To purchase a license, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI2LTA5LTI2Iiwibm90aWNlIjo0NSwiZ3JhY2UiOjE1LCJmbGFncyI6WyJ0cmlhbCJdfX195f2c28b185a0f34f2c85b97568c44f8930d30dd58f4901815807d550bc45716c98c6e9d01ea036efb6cfda123b7dfb7904cb5e946e0a407c0f5329e72691d715]`;

/**
 * Handsontable, `release_until` 2027-08-12, notice 0, grace 0 (example A4).
 *
 * @type {string}
 */
export const PERPETUAL_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Perpetual license under Handsontable Perpetual License Agreement 2.0 of 2022-05-21, for Handsontable on the Enterprise package, for internal use. Maintenance and access to new versions both end on 2027-08-12. Versions released on or before that date may be used indefinitely. To renew maintenance, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwicmVsZWFzZV91bnRpbCI6IjIwMjctMDgtMTIiLCJub3RpY2UiOjAsImdyYWNlIjowLCJmbGFncyI6W119fX0d902bff803f72b705792c547d303a24f7d3142775f6e3c3f4e6aa583a0b3b80caab85380dfa7478f89f53948895e4497454fe2537d7b29ce9a6136066d236e02]`;

/**
 * A1 with the console silenced by request, the UI left alone (example A7).
 *
 * @type {string}
 */
export const NO_CONSOLE_WARNS_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Subscription license under Handsontable Subscription License Agreement 2.0 of 2022-05-21, for Handsontable on the Enterprise package, for internal use, valid until 2027-08-12 (UTC). Use after that date is not permitted. To renew, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI3LTA4LTEyIiwibm90aWNlIjo2MCwiZ3JhY2UiOjkwLCJmbGFncyI6WyJuby1jb25zb2xlLXdhcm5zIl19fX07781e15b303d299085f1762bc862e80e0971ce057cb0cb07047169dddcd8f97b09e70762bd79cdb86a94ffbdb1b4e3445578f25c2ed99ca652de73f5a44d09be]`;

/**
 * A1 with the UI silenced by request, the console left alone (example A8).
 *
 * @type {string}
 */
export const NO_UI_WARNS_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Subscription license under Handsontable Subscription License Agreement 2.0 of 2022-05-21, for Handsontable on the Enterprise package, for internal use, valid until 2027-08-12 (UTC). Use after that date is not permitted. To renew, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI3LTA4LTEyIiwibm90aWNlIjo2MCwiZ3JhY2UiOjkwLCJmbGFncyI6WyJuby11aS13YXJucyJdfX1934a26b98650bca363a77bd859bb921d34d7c213a58355e5aac1a4eaa812ecf07468d66644ea22ff7f0db15b636fca5cd4ddf30ec2116cbae32ff6b110b50e623]`;

/**
 * HyperFormula only - a checksum-valid key that is not a Handsontable license (example B1).
 *
 * @type {string}
 */
export const HF_ONLY_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Subscription license under Handsontable Subscription License Agreement 2.0 of 2022-05-21, for HyperFormula on the Essential package, for internal use, valid until 2027-08-12 (UTC). Use after that date is not permitted. To renew, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoeXBlcmZvcm11bGEiOnsiY2FwYWJpbGl0aWVzIjpbImZ1bmN0aW9uc18xIl0sInVzYWdlX3VudGlsIjoiMjAyNy0wOC0xMiIsIm5vdGljZSI6NjAsImdyYWNlIjo5MCwiZmxhZ3MiOltdfX198d51a20a9654df523103eabaa27f595b0988b1872d45306da91ff13102ac148e2f69b65e27160b54eb8e9e99521135c1c4d375c449af456af3084fdd0e5779ac]`;

/**
 * Handsontable on `usage_until` 2027-08-12 plus HyperFormula on `release_until` 2025-03-31 (example C4).
 *
 * @type {string}
 */
export const MIXED_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 2 licenses:

> 1. Subscription license under Handsontable Subscription License Agreement 2.0 of 2022-05-21, for Handsontable on the Enterprise package, for internal use, valid until 2027-08-12 (UTC). Use after that date is not permitted. To renew, contact sales@handsontable.com.

> 2. Perpetual license under Handsontable Perpetual License Agreement 2.0 of 2022-05-21, for HyperFormula on the Pro package, for internal use. Maintenance and access to new versions both end on 2025-03-31. Versions released on or before that date may be used indefinitely. To renew maintenance, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI3LTA4LTEyIiwibm90aWNlIjo2MCwiZ3JhY2UiOjkwLCJmbGFncyI6W119LCJoeXBlcmZvcm11bGEiOnsiY2FwYWJpbGl0aWVzIjpbImZ1bmN0aW9uc18xIiwiZnVuY3Rpb25zXzIiXSwicmVsZWFzZV91bnRpbCI6IjIwMjUtMDMtMzEiLCJub3RpY2UiOjAsImdyYWNlIjowLCJmbGFncyI6W119fX08d2f8c57c2d22a6afecdc2a09d549990cb2bec927492e031143e536f84fb454c2c543b74444ad379fb22bee7102e54b99fb1997e3617c28c63480c6865a5402d]`;

/**
 * A1 with `notice: 0` - quiet before expiry, loud after (example E2).
 *
 * @type {string}
 */
export const NO_NOTICE_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Subscription license under Handsontable Subscription License Agreement 2.0 of 2022-05-21, for Handsontable on the Enterprise package, for internal use, valid until 2027-08-12 (UTC). Use after that date is not permitted. To renew, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI3LTA4LTEyIiwibm90aWNlIjowLCJncmFjZSI6OTAsImZsYWdzIjpbXX19fQaa757b0e8f41d9b642f9d4816af9177a4f16b00ae1ccff0359b87795e1a5169d3d1facdee644cd56026e9e96e743c528cac973cf3814a4d680b8924449844773]`;

/**
 * Individually negotiated terms: `usage_until` 2029-12-31, notice 180, grace 180, flag `custom` (example E4).
 *
 * @type {string}
 */
export const CUSTOM_FLAG_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Subscription license under Handsontable Subscription License Agreement 2.0 of 2022-05-21, for Handsontable on the Enterprise package, for internal use, valid until 2029-12-31 (UTC). Use after that date is not permitted. To renew, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI5LTEyLTMxIiwibm90aWNlIjoxODAsImdyYWNlIjoxODAsImZsYWdzIjpbImN1c3RvbSJdfX196a8ea38761d51d49dbbf59c526765d77b6dcc7d44358ac068073a2dd132ff9155ecb6ae751f6e0851cbcccfa23465c6278622b8ddf4b184bfa0b946527826d16]`;

/**
 * A trial with the console silenced by request - the badge, popover and bar stay (examples A3 + A7).
 *
 * @type {string}
 */
export const TRIAL_NO_CONSOLE_WARNS_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Trial license under Handsontable Evaluation License Agreement 4.0 of 2026-03-02, for Handsontable on the Enterprise package, for internal use, valid until 2026-09-26 (UTC). Not licensed for production use. To purchase a license, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI2LTA5LTI2Iiwibm90aWNlIjo0NSwiZ3JhY2UiOjE1LCJmbGFncyI6WyJ0cmlhbCIsIm5vLWNvbnNvbGUtd2FybnMiXX19fQ9a0b1fb7f72971a4abf34ff5320f33a3f828849f6aa0a3e8bfaae0d0ee2bfc322a4035a42ae048fe790d026fb17b40b876f4b38553c44abac1bb6a0398734486]`;

/**
 * A trial with the UI silenced by request - only the console speaks (examples A3 + A8).
 *
 * @type {string}
 */
export const TRIAL_NO_UI_WARNS_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Trial license under Handsontable Evaluation License Agreement 4.0 of 2026-03-02, for Handsontable on the Enterprise package, for internal use, valid until 2026-09-26 (UTC). Not licensed for production use. To purchase a license, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI2LTA5LTI2Iiwibm90aWNlIjo0NSwiZ3JhY2UiOjE1LCJmbGFncyI6WyJ0cmlhbCIsIm5vLXVpLXdhcm5zIl19fX0061fb508cce2411f2221e4218b2e05e791db52682a6997d885f9769f997027c52cdd87c75aab81e9dd670309874b466a87a74f7df268009d4f39acbad1fb3051]`;

/**
 * A perpetual license with the UI silenced, so a lapsed maintenance date shows no bar (example A5).
 *
 * @type {string}
 */
export const PERPETUAL_NO_UI_WARNS_KEY = `This is a Handsontable license key for Test Fixture, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Perpetual license under Handsontable Perpetual License Agreement 2.0 of 2022-05-21, for Handsontable on the Enterprise package, for internal use. Maintenance and access to new versions both end on 2027-08-12. Versions released on or before that date may be used indefinitely. To renew maintenance, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwicmVsZWFzZV91bnRpbCI6IjIwMjctMDgtMTIiLCJub3RpY2UiOjAsImdyYWNlIjowLCJmbGFncyI6WyJuby11aS13YXJucyJdfX19296642b3a49180560f88906b63667c7154581ace23a4a0c014882fde06d6ff034e2d3ccd67612dd46f8796374ade8892a8b6064756b6cb76a7d99891ad3d158c]`;

/**
 * A1 issued to a holder whose name has composed (NFC) characters - "\u00fc", "\u00d6", "\u0141" and
 * others. The checksum covers the prose in NFC, so this key proves that the reader normalizes the
 * prose the same way the generator does, and that a decomposed (NFD) copy still reads.
 *
 * @type {string}
 */
export const ACCENTED_HOLDER_KEY = `This is a Handsontable license key for Z\u00fcrich \u00d6d\u00f6n \u0141\u00f3d\u017a Ltd., issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Subscription license under Handsontable Subscription License Agreement 2.0 of 2022-05-21, for Handsontable on the Enterprise package, for internal use, valid until 2027-08-12 (UTC). Use after that date is not permitted. To renew, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI3LTA4LTEyIiwibm90aWNlIjo2MCwiZ3JhY2UiOjkwLCJmbGFncyI6W119fX0f65153334f11db05850685a07ff89f3710dbf46faba3e4cee4bb3a181272a69aea5fd082b85261a79d419c16cfaee5ac1bf1941f386cbbc1c89c41ba11767181]`;

/**
 * A1 issued to a holder whose name is written in Japanese, so the prose has runs of CJK characters
 * with no spaces between them - the text a mail client may break at any character.
 *
 * @type {string}
 */
export const CJK_HOLDER_KEY = `This is a Handsontable license key for \u682a\u5f0f\u4f1a\u793e\u30c6\u30b9\u30c8\u30d5\u30a3\u30af\u30b9\u30c1\u30e3, issued on 2026-08-12 for the "Fixture Project" project. It includes 1 license:

> 1. Subscription license under Handsontable Subscription License Agreement 2.0 of 2022-05-21, for Handsontable on the Enterprise package, for internal use, valid until 2027-08-12 (UTC). Use after that date is not permitted. To renew, contact sales@handsontable.com.

[eyJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsiY2FwYWJpbGl0aWVzIjpbImNvcmUiXSwidXNhZ2VfdW50aWwiOiIyMDI3LTA4LTEyIiwibm90aWNlIjo2MCwiZ3JhY2UiOjkwLCJmbGFncyI6W119fX0eea2196d4da54636b27e38cf5f71588326794d5043beb39d65ec3e88e57a09e89e9772fb8dd44a4d8e928b04303666323e75c42018a035acf06203a481c9cf39]`;
