import {
  arrayAvg,
  arrayEach,
  arrayFilter,
  arrayFlatten,
  arrayMap,
  arrayMax,
  arrayMin,
  arrayReduce,
  arraySum,
  arrayUnique,
  extendArray,
  getDifferenceOfArrays,
  getIntersectionOfArrays,
  getUnionOfArrays,
  pivot,
  stringToArray,
  to2dArray,
} from './array';
import {
  isChrome,
  isChromeWebKit,
  isEdge,
  isEdgeWebKit,
  isFirefox,
  isFirefoxWebKit,
  isIE,
  isIE9,
  isIOS,
  isIpadOS,
  isLinuxOS,
  isMacOS,
  isMobileBrowser,
  isMSBrowser,
  isSafari,
  isWindowsOS,
  setBrowserMeta,
  setPlatformMeta,
} from './browser';
import {
  error,
  info,
  log,
  warn,
} from './console';
import {
  cellMethodLookupFactory,
  countFirstRowKeys,
  createEmptySpreadsheetData,
  createSpreadsheetData,
  createSpreadsheetObjectData,
  dataRowToChangesArray,
  isArrayOfArrays,
  isArrayOfObjects,
  spreadsheetColumnIndex,
  spreadsheetColumnLabel,
  translateRowsToColumns,
} from './data';
import {
  getNormalizedDate,
} from './date';
import {
  cancelAnimationFrame,
  getComparisonFunction,
  hasCaptionProblem,
  isClassListSupported,
  isGetComputedStyleSupported,
  isPassiveEventSupported,
  isTextContentSupported,
  isTouchSupported,
  requestAnimationFrame,
} from './feature';
import {
  curry,
  curryRight,
  debounce,
  fastCall,
  isFunction,
  partial,
  pipe,
  throttle,
  throttleAfterHits,
} from './function';
import {
  isDefined,
  isEmpty,
  isRegExp,
  isUndefined,
  stringify,
} from './mixed';
import {
  isNumeric,
  isNumericLike,
  rangeEach,
  rangeEachReverse,
  valueAccordingPercent,
} from './number';
import {
  clone,
  createObjectPropListener,
  deepClone,
  deepExtend,
  deepObjectSize,
  defineGetter,
  duckSchema,
  extend,
  getProperty,
  hasOwnProperty,
  inherit,
  isObject,
  isObjectEqual,
  mixin,
  objectEach,
  setProperty,
} from './object';
import {
  equalsIgnoreCase,
  isPercentValue,
  randomString,
  sanitize,
  stripTags,
  substitute,
  toUpperCaseFirst,
} from './string';
import {
  toSingleLine,
} from './templateLiteralTag';
import {
  isCtrlKey,
  isCtrlMetaKey,
  isFunctionKey,
  isKey,
  isPrintableChar,
  KEY_CODES,
} from './unicode';

export interface Helper {
  arrayAvg,
  arrayEach,
  arrayFilter,
  arrayFlatten,
  arrayMap,
  arrayMax,
  arrayMin,
  arrayReduce,
  arraySum,
  arrayUnique,
  cancelAnimationFrame,
  cellMethodLookupFactory,
  clone,
  countFirstRowKeys,
  createEmptySpreadsheetData,
  createObjectPropListener,
  createSpreadsheetData,
  createSpreadsheetObjectData,
  curry,
  curryRight,
  dataRowToChangesArray,
  debounce,
  deepClone,
  deepExtend,
  deepObjectSize,
  defineGetter,
  duckSchema,
  equalsIgnoreCase,
  error,
  extend,
  extendArray,
  fastCall,
  getComparisonFunction,
  getDifferenceOfArrays,
  getIntersectionOfArrays,
  getNormalizedDate,
  getProperty,
  getUnionOfArrays,
  hasCaptionProblem,
  hasOwnProperty,
  info,
  inherit,
  isArrayOfArrays,
  isArrayOfObjects,
  isChrome,
  isChromeWebKit,
  isClassListSupported,
  isCtrlKey,
  isCtrlMetaKey,
  isDefined,
  isEdge,
  isEdgeWebKit,
  isEmpty,
  isFirefox,
  isFirefoxWebKit,
  isFunction,
  isFunctionKey,
  isGetComputedStyleSupported,
  isIE,
  isIE9,
  isIOS,
  isIpadOS,
  isKey,
  isLinuxOS,
  isMacOS,
  isMobileBrowser,
  isMSBrowser,
  isNumeric,
  isNumericLike,
  isObject,
  isObjectEqual,
  isPassiveEventSupported,
  isPercentValue,
  isPrintableChar,
  isRegExp,
  isSafari,
  isTextContentSupported,
  isTouchSupported,
  isUndefined,
  isWindowsOS,
  KEY_CODES,
  log,
  mixin,
  objectEach,
  partial,
  pipe,
  pivot,
  randomString,
  rangeEach,
  rangeEachReverse,
  requestAnimationFrame,
  sanitize,
  setBrowserMeta,
  setPlatformMeta,
  setProperty,
  spreadsheetColumnIndex,
  spreadsheetColumnLabel,
  stringify,
  stringToArray,
  stripTags,
  substitute,
  throttle,
  throttleAfterHits,
  to2dArray,
  toSingleLine,
  toUpperCaseFirst,
  translateRowsToColumns,
  valueAccordingPercent,
  warn,
}
