autoInstallPeers: true
linkWorkspacePackages: true
preferWorkspacePackages: true
preferFrozenLockfile: true

packages:
  - handsontable
  - wrappers/*
  - visual-tests
  - examples

hoistPattern:
  - '*'
  - '!@typescript-eslint/*'
  - '!jest*'
  - '!@jest/*'
  - '!vue'
  - '!@vue/*'
  - '!vue-*'
  - '!*vue*'

ignoredBuiltDependencies:
  - nice-napi
  - nx
  - sharp

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild
  - puppeteer

# Force compatible Vue3 sub-dependencies for rc and alpha versions of the wrapper dependencies.
# TODO: Replace with newer version of the wrapper dependencies.
packageExtensions:
  '@vue/test-utils@2.0.0-rc.16':
    dependencies:
      'vue': '3.5.16'
      '@vue/compiler-dom': '3.5.16'
      '@vue/compiler-sfc': '3.5.16'
  'vue-jest@5.0.0-alpha.10':
    dependencies:
      '@vue/compiler-dom': '3.5.16'
      '@vue/compiler-sfc': '3.5.16'

