autoInstallPeers: true
linkWorkspacePackages: true
preferWorkspacePackages: true
preferFrozenLockfile: true

packages:
  - handsontable
  - wrappers/*
  - visual-tests
  - examples

ignoredBuiltDependencies:
  - nice-napi
  - sharp

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild
  - puppeteer
  - nx

# TODO: Replace with newer version of the Vue wrapper dependencies.
packageExtensions:
  '@vue/test-utils@2.0.0-rc.16': # Force compatible Vue3 sub-dependencies for rc and alpha versions of the wrapper dependencies.
    dependencies:
      'vue': '3.5.16'
      '@vue/compiler-dom': '3.5.16'
      '@vue/compiler-sfc': '3.5.16'
  'vue-jest@5.0.0-alpha.10': # Force compatible Vue3 sub-dependencies for rc and alpha versions of the wrapper dependencies.
    dependencies:
      '@vue/compiler-dom': '3.5.16'
      '@vue/compiler-sfc': '3.5.16'
  '@nx/devkit': # Add a missing peer dependency of rxjs used by the Nx devkit.
    peerDependencies:
      'rxjs': '*'
  'jest-preset-angular@14.6.0': # Add a missing peer dependency of zone.js used by the jest preset.
    peerDependencies:
      'zone.js': '*'

