/**
 * Type declarations for custom virtual Vite modules used by the docs build.
 *
 * The virtual:valid-urls module is generated by the plugin in astro.config.mjs.
 * It provides pre-computed sidebar URL arrays (one per framework) baked in at
 * build time so that Astro components can import them as static data without
 * pulling sidebar.mjs — which uses createRequire(import.meta.url) — into the
 * prerender bundle.
 */

declare module 'virtual:valid-urls' {
  /** Per-framework arrays of valid sidebar URL paths (without the /docs base prefix). */
  export const validUrlArrays: Record<string, string[]>;
}
