import { arrayEach } from '../../../helpers/array';
import { createDefaultHeaderSettings, createPlaceholderHeaderSettings } from './utils';
import type TreeNode from '../../../utils/dataStructures/tree';
import type { HeaderNodeData } from './headersTree';

/**
 * A function that dump a tree structure into multidimensional array. That structure is
 * later processed by header renderers to modify TH elements to achieve a proper
 * DOM structure.
 *
 * That structure contains settings object for every TH element generated by Walkontable.
 * The matrix operates on visual column index.
 *
 * Output example:
 *   [
 *     [
 *       { label: 'A1', colspan: 2, origColspan: 2, isHidden: false, ... },
 *       { label: '', colspan: 1, origColspan: 1, isHidden: true, ... },
 *       { label: '', colspan: 1, origColspan: 1, isHidden: false, ... },
 *     ],
 *     [
 *       { label: 'true', colspan: 1, origColspan: 1, isHidden: false, ... },
 *       { label: 'B2', colspan: 1, origColspan: 1, isHidden: false, ... },
 *       { label: '4', colspan: 1, origColspan: 1, isHidden: false, ... },
 *     ],
 *     [
 *       { label: '', colspan: 1, origColspan: 1, isHidden: false, ... },
 *       { label: '', colspan: 1, origColspan: 1, isHidden: false, ... },
 *       { label: '', colspan: 1, origColspan: 1, isHidden: false, ... },
 *     ],
 *   ]
 *
 * @param {TreeNode[]} headerRoots An array of root nodes.
 * @returns {Array[]}
 */
export function generateMatrix(headerRoots: TreeNode[]) {
  const matrix: Array<Array<Record<string, unknown>>> = [];

  arrayEach(headerRoots, (rootNode) => {
    (rootNode as { walkDown: (cb: (node: TreeNode) => void | boolean) => void }).walkDown((node: TreeNode) => {
      const nodeData = node.data as HeaderNodeData;
      const {
        origColspan,
        columnIndex,
        headerLevel,
        crossHiddenColumns,
      } = nodeData;
      const colspanHeaderLayer = createNestedArrayIfNecessary(matrix, headerLevel);
      let isRootSettingsFound = false;

      for (let i = columnIndex; i < columnIndex + origColspan; i++) {
        const isColumnHidden = crossHiddenColumns.includes(i);

        if (isColumnHidden || isRootSettingsFound) {
          colspanHeaderLayer.push(createPlaceholderHeaderSettings());
        } else {
          const headerRootSettings = createHeaderSettings(nodeData);

          headerRootSettings.isRoot = true;
          colspanHeaderLayer.push(headerRootSettings);
          isRootSettingsFound = true;
        }
      }
    });
  });

  applyRowspanToMatrix(matrix);

  return matrix;
}

/**
 * Post-processes the generated matrix to apply rowspan. For each root cell that has
 * `origRowspan > 1`, the cells in the rows below it (within the rowspan range and
 * origColspan width) are marked as rowspan placeholders.
 *
 * @param {Array[]} matrix The generated header matrix to modify in-place.
 */
function applyRowspanToMatrix(matrix: Array<Array<Record<string, unknown>>>) {
  for (let level = 0; level < matrix.length; level++) {
    const row = matrix[level];

    for (let col = 0; col < row.length; col++) {
      const settings = row[col];

      if (!settings || !settings.isRoot || !settings.origRowspan || (settings.origRowspan as number) <= 1) {
        continue; // eslint-disable-line no-continue
      }

      const effectiveRowspan = Math.min(settings.origRowspan as number, matrix.length - level);
      const colspanWidth = (settings.origColspan as number) || 1;

      for (let r = 1; r < effectiveRowspan; r++) {
        const targetLevel = level + r;

        if (!matrix[targetLevel]) {
          continue; // eslint-disable-line no-continue
        }

        for (let c = col; c < col + colspanWidth && c < matrix[targetLevel].length; c++) {
          matrix[targetLevel][c] = {
            label: '',
            isPlaceholder: true,
            isRowspanPlaceholder: true,
          };
        }
      }
    }
  }
}

/**
 * Creates header settings object.
 *
 * @param {object} nodeData The tree data object.
 * @returns {object}
 */
function createHeaderSettings(nodeData: Record<string, unknown>) {
  // The matrix module does not need the "crossHiddenColumns" or "columnDropMode" keys - the former is
  // a visibility detail, the latter a structural input that only affects how the tree is derived.
  const { crossHiddenColumns, columnDropMode, ...headerRootSettings } = createDefaultHeaderSettings(nodeData);

  return headerRootSettings;
}

/**
 * Internal helper which ensures that subarray exists under specified index.
 *
 * @param {Array[]} array An array to check.
 * @param {number} index An array index under the subarray should be checked.
 * @returns {Array}
 */
function createNestedArrayIfNecessary(array: unknown[][], index: number) {
  let subArray: unknown[];

  if (Array.isArray(array[index])) {
    subArray = array[index];
  } else {
    subArray = [];
    array[index] = subArray;
  }

  return subArray;
}
