<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

// Generated by: php bin/console doctrine:migrations:generate
// Run with:     php bin/console doctrine:migrations:migrate
final class Version20240101000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create products table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<SQL
            CREATE TABLE products (
                id         INT AUTO_INCREMENT NOT NULL,
                name       VARCHAR(255)   NOT NULL,
                sku        VARCHAR(255)   NOT NULL,
                category   VARCHAR(255)   NOT NULL,
                price      DECIMAL(10, 2) NOT NULL,
                stock      INT            NOT NULL,
                sort_order INT UNSIGNED   NOT NULL DEFAULT 0,
                INDEX IDX_PRODUCTS_SORT_ORDER (sort_order),
                UNIQUE INDEX UNIQ_PRODUCTS_SKU (sku),
                PRIMARY KEY (id)
            ) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE products');
    }
}
