<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

// Generated by: php artisan make:migration create_products_table
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('products', function (Blueprint $table) {
            $table->id();                               // Auto-increment primary key
            $table->string('name');                     // Product name (filterable via LIKE)
            $table->string('sku')->unique();            // Stock-keeping unit (read-only in UI)
            $table->string('category');                 // Dropdown value (filterable via =)
            $table->decimal('price', 10, 2);           // Numeric — supports gt/lt/between
            $table->unsignedInteger('stock');           // Numeric — supports gt/lt/between
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('products');
    }
};
