<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

// Generated by: php artisan make:seeder ProductSeeder
// Run with:     php artisan db:seed --class=ProductSeeder
class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $categories = ['Electronics', 'Accessories', 'Storage', 'Networking', 'Peripherals'];

        $products = [
            ['name' => 'Laptop Pro 15',              'sku' => 'LAP-001', 'category' => 'Electronics',  'price' => 1299.99, 'stock' => 42],
            ['name' => 'Wireless Mouse',             'sku' => 'MOU-002', 'category' => 'Accessories',  'price' => 29.99,   'stock' => 315],
            ['name' => 'USB-C Hub 7-in-1',           'sku' => 'HUB-003', 'category' => 'Accessories',  'price' => 49.99,   'stock' => 178],
            ['name' => 'NVMe SSD 1 TB',              'sku' => 'SSD-004', 'category' => 'Storage',      'price' => 109.99,  'stock' => 260],
            ['name' => 'Mechanical Keyboard',        'sku' => 'KEY-005', 'category' => 'Peripherals',  'price' => 139.99,  'stock' => 95],
            ['name' => 'Gigabit Switch 8-Port',      'sku' => 'SW8-006', 'category' => 'Networking',   'price' => 59.99,   'stock' => 74],
            ['name' => 'Portable Monitor 15"',       'sku' => 'MON-007', 'category' => 'Electronics',  'price' => 249.99,  'stock' => 38],
            ['name' => 'Webcam 4K',                  'sku' => 'CAM-008', 'category' => 'Peripherals',  'price' => 89.99,   'stock' => 112],
            ['name' => 'External HDD 2 TB',          'sku' => 'HDD-009', 'category' => 'Storage',      'price' => 74.99,   'stock' => 193],
            ['name' => 'Wi-Fi 6 Router',             'sku' => 'RTR-010', 'category' => 'Networking',   'price' => 179.99,  'stock' => 55],
            ['name' => 'Noise-Cancelling Headphones','sku' => 'HP-011',  'category' => 'Accessories',  'price' => 199.99,  'stock' => 67],
            ['name' => 'Thunderbolt Dock',           'sku' => 'DOC-012', 'category' => 'Accessories',  'price' => 219.99,  'stock' => 31],
            ['name' => 'Laptop Stand',               'sku' => 'STD-013', 'category' => 'Accessories',  'price' => 39.99,   'stock' => 220],
            ['name' => 'Gaming Controller',          'sku' => 'CTR-014', 'category' => 'Peripherals',  'price' => 69.99,   'stock' => 148],
            ['name' => 'HDMI Cable 2 m',             'sku' => 'CBL-015', 'category' => 'Accessories',  'price' => 12.99,   'stock' => 500],
            ['name' => 'MicroSD 256 GB',             'sku' => 'MSD-016', 'category' => 'Storage',      'price' => 29.99,   'stock' => 387],
            ['name' => 'PoE Switch 24-Port',         'sku' => 'POE-017', 'category' => 'Networking',   'price' => 299.99,  'stock' => 18],
            ['name' => 'Smart Plug 4-Pack',          'sku' => 'PLG-018', 'category' => 'Electronics',  'price' => 34.99,   'stock' => 142],
            ['name' => 'USB Microphone',             'sku' => 'MIC-019', 'category' => 'Peripherals',  'price' => 79.99,   'stock' => 89],
            ['name' => 'Ergonomic Chair Mat',        'sku' => 'MAT-020', 'category' => 'Accessories',  'price' => 44.99,   'stock' => 61],
            ['name' => 'Tablet 10" Wi-Fi',           'sku' => 'TAB-021', 'category' => 'Electronics',  'price' => 349.99,  'stock' => 27],
            ['name' => 'Power Bank 20000 mAh',       'sku' => 'PBK-022', 'category' => 'Accessories',  'price' => 49.99,   'stock' => 203],
            ['name' => 'OLED Monitor 27"',           'sku' => 'MON-023', 'category' => 'Electronics',  'price' => 699.99,  'stock' => 14],
            ['name' => 'USB-A 4-Port Hub',           'sku' => 'HUB-024', 'category' => 'Accessories',  'price' => 19.99,   'stock' => 341],
            ['name' => 'SSD Enclosure',              'sku' => 'ENC-025', 'category' => 'Storage',      'price' => 24.99,   'stock' => 115],
            ['name' => 'Network Cable Cat 6 10 m',  'sku' => 'CBL-026', 'category' => 'Networking',   'price' => 9.99,    'stock' => 620],
            ['name' => 'Drawing Tablet',             'sku' => 'TAB-027', 'category' => 'Peripherals',  'price' => 189.99,  'stock' => 43],
            ['name' => 'Smart Switch',               'sku' => 'SW2-028', 'category' => 'Electronics',  'price' => 44.99,   'stock' => 78],
            ['name' => 'Desk Lamp LED',              'sku' => 'LMP-029', 'category' => 'Accessories',  'price' => 34.99,   'stock' => 99],
            ['name' => 'RAID Controller',            'sku' => 'RAD-030', 'category' => 'Storage',      'price' => 149.99,  'stock' => 22],
            ['name' => 'VPN Router',                 'sku' => 'VPN-031', 'category' => 'Networking',   'price' => 219.99,  'stock' => 30],
            ['name' => 'Foot Pedal USB',             'sku' => 'FTP-032', 'category' => 'Peripherals',  'price' => 59.99,   'stock' => 47],
            ['name' => 'Mini PC',                    'sku' => 'MPC-033', 'category' => 'Electronics',  'price' => 449.99,  'stock' => 19],
            ['name' => 'Cable Management Kit',       'sku' => 'KIT-034', 'category' => 'Accessories',  'price' => 14.99,   'stock' => 265],
            ['name' => 'M.2 SSD 500 GB',             'sku' => 'SSD-035', 'category' => 'Storage',      'price' => 59.99,   'stock' => 183],
            ['name' => 'Managed Switch 48-Port',     'sku' => 'MSW-036', 'category' => 'Networking',   'price' => 599.99,  'stock' => 8],
            ['name' => 'RGB LED Strip',              'sku' => 'LED-037', 'category' => 'Electronics',  'price' => 24.99,   'stock' => 320],
            ['name' => 'Monitor Arm Single',         'sku' => 'ARM-038', 'category' => 'Accessories',  'price' => 54.99,   'stock' => 73],
            ['name' => 'Barcode Scanner USB',        'sku' => 'SCN-039', 'category' => 'Peripherals',  'price' => 119.99,  'stock' => 56],
            ['name' => 'NAS Enclosure 4-Bay',        'sku' => 'NAS-040', 'category' => 'Storage',      'price' => 329.99,  'stock' => 11],
            ['name' => 'Fiber Converter',            'sku' => 'FBC-041', 'category' => 'Networking',   'price' => 89.99,   'stock' => 25],
            ['name' => 'Wireless Presenter',         'sku' => 'PRE-042', 'category' => 'Peripherals',  'price' => 39.99,   'stock' => 67],
            ['name' => 'UPS 1500 VA',                'sku' => 'UPS-043', 'category' => 'Electronics',  'price' => 259.99,  'stock' => 16],
            ['name' => 'Zip Ties 100-Pack',          'sku' => 'ZTP-044', 'category' => 'Accessories',  'price' => 7.99,    'stock' => 950],
            ['name' => 'HDD 4 TB Desktop',          'sku' => 'HDD-045', 'category' => 'Storage',      'price' => 89.99,   'stock' => 94],
            ['name' => 'Patch Panel 24-Port',        'sku' => 'PNL-046', 'category' => 'Networking',   'price' => 49.99,   'stock' => 35],
            ['name' => 'Numeric Keypad',             'sku' => 'KPD-047', 'category' => 'Peripherals',  'price' => 29.99,   'stock' => 130],
            ['name' => 'Server Rack 12U',            'sku' => 'RCK-048', 'category' => 'Networking',   'price' => 349.99,  'stock' => 7],
            ['name' => 'Thermal Paste 5 g',         'sku' => 'TPT-049', 'category' => 'Accessories',  'price' => 8.99,    'stock' => 480],
            ['name' => 'Flash Drive 128 GB',         'sku' => 'USB-050', 'category' => 'Storage',      'price' => 17.99,   'stock' => 740],
            ['name' => 'HDMI Splitter 4-Port',       'sku' => 'SPL-051', 'category' => 'Electronics',  'price' => 29.99,   'stock' => 88],
            ['name' => 'Smart Card Reader',          'sku' => 'SCR-052', 'category' => 'Peripherals',  'price' => 19.99,   'stock' => 210],
        ];

        foreach ($products as $i => $data) {
            Product::create(array_merge($data, ['sort_order' => $i + 1]));
        }
    }
}
