# Gemfile -- relevant additions only.
# Add these two gems to the Gemfile generated by `rails new orders-api --api`,
# then run `bundle install`.

# Pagination helpers for ActiveRecord.
# Provides .page(n).per(size) on any relation and exposes .total_count,
# which this recipe returns to Handsontable as `total_rows`.
gem "kaminari"

# Cross-origin request support.
# Lets the Rails API accept requests from the frontend dev server
# (for example, Vite on http://localhost:5173).
gem "rack-cors"
