export const A11Y_TABINDEX = (val: number): [string, number] => ['tabindex', val];
export const A11Y_TREEGRID = (): [string, string] => ['role', 'treegrid'];
export const A11Y_PRESENTATION = (): [string, string] => ['role', 'presentation'];
export const A11Y_GRIDCELL = (): [string, string] => ['role', 'gridcell'];
export const A11Y_ROWHEADER = (): [string, string] => ['role', 'rowheader'];
export const A11Y_ROWGROUP = (): [string, string] => ['role', 'rowgroup'];
export const A11Y_COLUMNHEADER = (): [string, string] => ['role', 'columnheader'];
export const A11Y_ROW = (): [string, string] => ['role', 'row'];
export const A11Y_MENU = (): [string, string] => ['role', 'menu'];
export const A11Y_MENU_ITEM = (): [string, string] => ['role', 'menuitem'];
export const A11Y_MENU_ITEM_CHECKBOX = (): [string, string] => ['role', 'menuitemcheckbox'];
export const A11Y_COMBOBOX = (): [string, string] => ['role', 'combobox'];
export const A11Y_LISTBOX = (): [string, string] => ['role', 'listbox'];
export const A11Y_OPTION = (): [string, string] => ['role', 'option'];
export const A11Y_CHECKBOX = (): [string, string] => ['role', 'checkbox'];
export const A11Y_SCOPE_COL = (): [string, string] => ['scope', 'col'];
export const A11Y_SCOPE_ROW = (): [string, string] => ['scope', 'row'];
export const A11Y_TEXT = (): [string, string] => ['type', 'text'];
export const A11Y_LABEL = (val: string): [string, string] => ['aria-label', val];
export const A11Y_HIDDEN = (): [string, string] => ['aria-hidden', 'true'];
export const A11Y_DISABLED = (): [string, string] => ['aria-disabled', 'true'];
export const A11Y_MULTISELECTABLE = (): [string, string] => ['aria-multiselectable', 'true'];
export const A11Y_HASPOPUP = (val: string): [string, string] => ['aria-haspopup', val];
export const A11Y_ROWCOUNT = (val: number): [string, number] => ['aria-rowcount', val];
export const A11Y_COLCOUNT = (val: number): [string, number] => ['aria-colcount', val];
export const A11Y_ROWINDEX = (val: number): [string, number] => ['aria-rowindex', val];
export const A11Y_COLINDEX = (val: number): [string, number] => ['aria-colindex', val];
export const A11Y_EXPANDED = (val: boolean | string): [string, boolean | string] => ['aria-expanded', val];
export const A11Y_SORT = (val: string): [string, string] => ['aria-sort', val];
export const A11Y_READONLY = (): [string, string] => ['aria-readonly', 'true'];
export const A11Y_INVALID = (): [string, string] => ['aria-invalid', 'true'];
export const A11Y_CHECKED = (val: boolean | string): [string, boolean | string] => ['aria-checked', val];
export const A11Y_SELECTED = (): [string, string] => ['aria-selected', 'true'];
export const A11Y_AUTOCOMPLETE = (): [string, string] => ['aria-autocomplete', 'list'];
export const A11Y_CONTROLS = (val: string): [string, string] => ['aria-controls', val];
export const A11Y_ACTIVEDESCENDANT = (val: string): [string, string] => ['aria-activedescendant', val];
export const A11Y_LIVE = (val: string): [string, string] => ['aria-live', val];
export const A11Y_RELEVANT = (val: string): [string, string] => ['aria-relevant', val];
export const A11Y_SETSIZE = (val: number): [string, number] => ['aria-setsize', val];
export const A11Y_POSINSET = (val: number): [string, number] => ['aria-posinset', val];
