/* eslint-disable no-restricted-globals */
/**
 * Polyfill for requestAnimationFrame.
 *
 * @param {Function} callback The function to call when it's time.
 * @returns {number}
 */
export function requestAnimationFrame(callback: () => void): number {
  return window.requestAnimationFrame(callback);
}

/**
 * Polyfill for cancelAnimationFrame.
 *
 * @param {number} id The request Id, generated by `requestAnimationFrame`.
 */
export function cancelAnimationFrame(id: number): void {
  window.cancelAnimationFrame(id);
}

/**
 * Schedules a low-priority task to run when the browser is idle. Uses `requestIdleCallback`
 * when available — with a timeout, so the task still progresses when the browser never idles —
 * and falls back to `requestAnimationFrame` otherwise.
 *
 * Use this for background work that nothing visual waits for (e.g. cache warming); unlike an
 * animation frame, an idle task does not compete with rendering while the user scrolls.
 *
 * @param {Function} callback The function to call during an idle period.
 * @param {number} [timeout=100] The maximum delay (in milliseconds) before the task is forced to run.
 * @returns {number}
 */
export function requestIdleTask(callback: () => void, timeout: number = 100): number {
  if (typeof window.requestIdleCallback === 'function') {
    return window.requestIdleCallback(() => callback(), { timeout });
  }

  return window.requestAnimationFrame(callback);
}

/**
 * Cancels a task scheduled with `requestIdleTask`.
 *
 * @param {number} id The task Id, generated by `requestIdleTask`.
 */
export function cancelIdleTask(id: number): void {
  if (typeof window.cancelIdleCallback === 'function') {
    window.cancelIdleCallback(id);
  } else {
    window.cancelAnimationFrame(id);
  }
}

/**
 * @returns {boolean}
 */
export function isTouchSupported(): boolean {
  return ('ontouchstart' in window);
}

/**
 * Checks if the environment that the code runs in is a browser.
 *
 * @returns {boolean}
 */
export function isCSR(): boolean {
  return typeof window !== 'undefined';
}

let comparisonFunction: ((a: string, b: string) => number) | undefined;

/**
 * Get string comparison function for sorting purposes. It supports multilingual string comparison base on Internationalization API.
 *
 * @param {string} [language] The language code used for phrases sorting.
 * @param {object} [options] Additional options for sort comparator.
 * @returns {*}
 */
export function getComparisonFunction(language?: string, options: object = {}) {
  if (comparisonFunction) {
    return comparisonFunction;
  }

  if (typeof Intl === 'object') {
    comparisonFunction = new Intl.Collator(language, options).compare;

  } else if (typeof String.prototype.localeCompare === 'function') {
    comparisonFunction = (a: string, b: string) => (`${a}`).localeCompare(b);

  } else {
    comparisonFunction = (a: string, b: string) => {
      if (a === b) {
        return 0;
      }

      return a > b ? -1 : 1;
    };
  }

  return comparisonFunction;
}

// DEV-2592 CI-scope probe: temporary, drop this commit before merge.
