export const data = [
  {
    checked: false,
    companyName: "Tagcat",
    country: "United Kingdom",
    name: "Classic Vest",
    sellDate: "11/10/2020",
    orderId: "01-2331942",
    inStock: true,
    quantity: "172",
    progress: 20,
    rating: 2
  },
  {
    checked: true,
    companyName: "Zoomzone",
    country: "Indonesia",
    name: "Cycling Cap",
    sellDate: "03/05/2020",
    orderId: "88-2768633",
    inStock: true,
    quantity: "188",
    progress: 60,
    rating: 2
  },
  {
    checked: true,
    companyName: "Meeveo",
    country: "United States",
    name: "Full-Finger Gloves",
    sellDate: "27/03/2020",
    orderId: "51-6775945",
    inStock: true,
    quantity: "162",
    progress: 10,
    rating: 3
  },
  {
    checked: false,
    companyName: "Buzzdog",
    country: "Philippines",
    name: "HL Mountain Frame",
    sellDate: "29/08/2020",
    orderId: "44-4028109",
    inStock: true,
    quantity: "133",
    progress: 70,
    rating: 1
  },
  {
    checked: true,
    companyName: "Katz",
    country: "India",
    name: "Half-Finger Gloves",
    sellDate: "02/10/2020",
    orderId: "08-2758492",
    inStock: true,
    quantity: "87",
    progress: 10,
    rating: 3
  },
  {
    checked: false,
    companyName: "Jaxbean",
    country: "China",
    name: "HL Road Frame",
    sellDate: "28/09/2020",
    orderId: "84-3557705",
    inStock: false,
    quantity: "26",
    progress: 80,
    rating: 1
  },
  {
    checked: false,
    companyName: "Wikido",
    country: "Brazil",
    name: "HL Touring Frame",
    sellDate: "24/06/2020",
    orderId: "20-9397637",
    inStock: false,
    quantity: "110",
    progress: 40,
    rating: 1
  },
  {
    checked: false,
    companyName: "Browsedrive",
    country: "United States",
    name: "LL Mountain Frame",
    sellDate: "13/03/2020",
    orderId: "36-0079556",
    inStock: true,
    quantity: "50",
    progress: 40,
    rating: 4
  },
  {
    checked: false,
    companyName: "Twinder",
    country: "United Kingdom",
    name: "LL Road Frame",
    sellDate: "06/04/2020",
    orderId: "41-1489542",
    inStock: false,
    quantity: "160",
    progress: 60,
    rating: 1
  },
  {
    checked: false,
    companyName: "Jetwire",
    country: "China",
    name: "LL Touring Frame",
    sellDate: "01/02/2020",
    orderId: "37-1531629",
    inStock: true,
    quantity: "30",
    progress: 80,
    rating: 5
  },
  {
    checked: false,
    companyName: "Chatterpoint",
    country: "China",
    name: "Long-Sleeve Logo Jersey",
    sellDate: "14/07/2020",
    orderId: "25-5083429",
    inStock: true,
    quantity: "39",
    progress: 70,
    rating: 2
  },
  {
    checked: false,
    companyName: "Twinder",
    country: "Egypt",
    name: "Men's Bib-Shorts",
    sellDate: "31/08/2020",
    orderId: "04-4281278",
    inStock: false,
    quantity: "96",
    progress: 60,
    rating: 1
  },
  {
    checked: false,
    companyName: "Midel",
    country: "United States",
    name: "Men's Sports Shorts",
    sellDate: "27/06/2020",
    orderId: "55-1711908",
    inStock: true,
    quantity: "108",
    progress: 100,
    rating: 3
  },
  {
    checked: false,
    companyName: "Yodo",
    country: "India",
    name: "ML Mountain Frame",
    sellDate: "16/03/2020",
    orderId: "58-8360815",
    inStock: false,
    quantity: "46",
    progress: 10,
    rating: 1
  },
  {
    checked: false,
    companyName: "Camido",
    country: "Russia",
    name: "ML Mountain Frame-W",
    sellDate: "13/09/2020",
    orderId: "10-3786104",
    inStock: true,
    quantity: "97",
    progress: 80,
    rating: 3
  },
  {
    checked: false,
    companyName: "Eire",
    country: "Thailand",
    name: "ML Road Frame",
    sellDate: "10/04/2020",
    orderId: "45-1186054",
    inStock: true,
    quantity: "161",
    progress: 10,
    rating: 4
  },
  {
    checked: false,
    companyName: "Vinte",
    country: "United Kingdom",
    name: "ML Road Frame-W",
    sellDate: "22/01/2020",
    orderId: "62-6202742",
    inStock: true,
    quantity: "58",
    progress: 40,
    rating: 3
  },
  {
    checked: false,
    companyName: "Twitterlist",
    country: "China",
    name: "Mountain Bike Socks",
    sellDate: "09/11/2020",
    orderId: "88-9646223",
    inStock: true,
    quantity: "92",
    progress: 80,
    rating: 3
  },
  {
    checked: false,
    companyName: "Eidel",
    country: "Bangladesh",
    name: "Mountain-100",
    sellDate: "19/09/2020",
    orderId: "45-5588112",
    inStock: true,
    quantity: "5",
    progress: 60,
    rating: 5
  },
  {
    checked: false,
    companyName: "Trunyx",
    country: "Nigeria",
    name: "Mountain-200",
    sellDate: "09/03/2020",
    orderId: "66-6271819",
    inStock: true,
    quantity: "158",
    progress: 40,
    rating: 1
  },
  {
    checked: false,
    companyName: "Katz",
    country: "Turkey",
    name: "Mountain-300",
    sellDate: "05/03/2020",
    orderId: "38-9245023",
    inStock: false,
    quantity: "121",
    progress: 50,
    rating: 4
  },
  {
    checked: false,
    companyName: "Kaymbo",
    country: "United States",
    name: "Mountain-400-W",
    sellDate: "24/12/2020",
    orderId: "44-5916927",
    inStock: false,
    quantity: "61",
    progress: 50,
    rating: 4
  },
  {
    checked: false,
    companyName: "Ozu",
    country: "Pakistan",
    name: "Mountain-500",
    sellDate: "13/06/2020",
    orderId: "31-5449914",
    inStock: true,
    quantity: "155",
    progress: 20,
    rating: 2
  },
  {
    checked: false,
    companyName: "Rhynyx",
    country: "India",
    name: "Racing Socks",
    sellDate: "05/12/2020",
    orderId: "19-9413869",
    inStock: true,
    quantity: "162",
    progress: 20,
    rating: 4
  },
  {
    checked: false,
    companyName: "Flashset",
    country: "Iran",
    name: "Road-150",
    sellDate: "14/12/2020",
    orderId: "25-9807605",
    inStock: false,
    quantity: "46",
    progress: 70,
    rating: 1
  },
  {
    checked: false,
    companyName: "Yata",
    country: "Congo (Kinshasa)",
    name: "Road-250",
    sellDate: "12/06/2020",
    orderId: "74-4291983",
    inStock: true,
    quantity: "47",
    progress: 40,
    rating: 4
  },
  {
    checked: false,
    companyName: "Brainlounge",
    country: "Vietnam",
    name: "Road-350-W",
    sellDate: "10/03/2020",
    orderId: "83-0980643",
    inStock: true,
    quantity: "104",
    progress: 20,
    rating: 3
  },
  {
    checked: false,
    companyName: "Babblestorm",
    country: "United States",
    name: "Road-450",
    sellDate: "10/10/2020",
    orderId: "19-2878430",
    inStock: true,
    quantity: "101",
    progress: 60,
    rating: 4
  },
  {
    checked: false,
    companyName: "Youspan",
    country: "Brazil",
    name: "Road-550-W",
    sellDate: "16/12/2020",
    orderId: "19-1838230",
    inStock: true,
    quantity: "150",
    progress: 100,
    rating: 3
  },
  {
    checked: false,
    companyName: "Nlounge",
    country: "China",
    name: "Road-650",
    sellDate: "31/10/2020",
    orderId: "32-2267938",
    inStock: true,
    quantity: "42",
    progress: 40,
    rating: 2
  },
  {
    checked: false,
    companyName: "Twinte",
    country: "India",
    name: "Road-750",
    sellDate: "17/08/2020",
    orderId: "79-2821972",
    inStock: true,
    quantity: "144",
    progress: 90,
    rating: 3
  },
  {
    checked: false,
    companyName: "Oyonder",
    country: "United Kingdom",
    name: "Short-Sleeve Classic Jersey",
    sellDate: "04/12/2020",
    orderId: "46-6597557",
    inStock: true,
    quantity: "195",
    progress: 40,
    rating: 1
  },
  {
    checked: false,
    companyName: "Gigabox",
    country: "Pakistan",
    name: "Sport-100",
    sellDate: "03/02/2020",
    orderId: "15-1793960",
    inStock: true,
    quantity: "199",
    progress: 40,
    rating: 4
  },
  {
    checked: false,
    companyName: "Livetube",
    country: "France",
    name: "Touring-1000",
    sellDate: "16/05/2020",
    orderId: "86-0811003",
    inStock: true,
    quantity: "110",
    progress: 40,
    rating: 5
  },
  {
    checked: false,
    companyName: "Voomm",
    country: "United Kingdom",
    name: "Touring-2000",
    sellDate: "15/07/2020",
    orderId: "95-3068680",
    inStock: true,
    quantity: "51",
    progress: 40,
    rating: 4
  },
  {
    checked: false,
    companyName: "Voonyx",
    country: "China",
    name: "Touring-3000",
    sellDate: "27/11/2020",
    orderId: "35-3085360",
    inStock: false,
    quantity: "69",
    progress: 20,
    rating: 5
  },
  {
    checked: false,
    companyName: "Zoombeat",
    country: "United States",
    name: "Women's Mountain Shorts",
    sellDate: "03/11/2020",
    orderId: "56-8673088",
    inStock: false,
    quantity: "53",
    progress: 20,
    rating: 3
  },
  {
    checked: false,
    companyName: "Roomm",
    country: "China",
    name: "Women's Tights",
    sellDate: "16/03/2020",
    orderId: "76-0085918",
    inStock: true,
    quantity: "168",
    progress: 10,
    rating: 1
  },
  {
    checked: false,
    companyName: "Leenti",
    country: "China",
    name: "Mountain-400",
    sellDate: "16/05/2020",
    orderId: "03-0893276",
    inStock: false,
    quantity: "58",
    progress: 10,
    rating: 4
  },
  {
    checked: false,
    companyName: "Jetpulse",
    country: "United States",
    name: "Road-550",
    sellDate: "08/02/2020",
    orderId: "79-9013306",
    inStock: true,
    quantity: "152",
    progress: 90,
    rating: 3
  },
  {
    checked: false,
    companyName: "Katz",
    country: "Peru",
    name: "Road-350",
    sellDate: "15/02/2020",
    orderId: "55-7799920",
    inStock: true,
    quantity: "66",
    progress: 40,
    rating: 2
  },
  {
    checked: false,
    companyName: "Cogidoo",
    country: "India",
    name: "LL Mountain Front Wheel",
    sellDate: "04/06/2020",
    orderId: "07-0881122",
    inStock: false,
    quantity: "112",
    progress: 90,
    rating: 2
  },
  {
    checked: false,
    companyName: "Divavu",
    country: "Colombia",
    name: "Touring Rear Wheel",
    sellDate: "24/02/2020",
    orderId: "58-6157387",
    inStock: true,
    quantity: "50",
    progress: 100,
    rating: 4
  },
  {
    checked: false,
    companyName: "Mydeo",
    country: "China",
    name: "Touring Front Wheel",
    sellDate: "07/12/2020",
    orderId: "12-2810010",
    inStock: false,
    quantity: "31",
    progress: 30,
    rating: 5
  },
  {
    checked: false,
    companyName: "Browsebug",
    country: "Japan",
    name: "ML Mountain Front Wheel",
    sellDate: "14/01/2020",
    orderId: "64-9249984",
    inStock: true,
    quantity: "132",
    progress: 50,
    rating: 5
  },
  {
    checked: false,
    companyName: "Layo",
    country: "China",
    name: "HL Mountain Front Wheel",
    sellDate: "24/04/2020",
    orderId: "45-0739652",
    inStock: true,
    quantity: "45",
    progress: 10,
    rating: 5
  },
  {
    checked: false,
    companyName: "Snaptags",
    country: "United Kingdom",
    name: "LL Touring Handlebars",
    sellDate: "06/08/2020",
    orderId: "09-5712761",
    inStock: true,
    quantity: "197",
    progress: 40,
    rating: 2
  },
  {
    checked: false,
    companyName: "Cogilith",
    country: "China",
    name: "HL Touring Handlebars",
    sellDate: "31/05/2020",
    orderId: "01-7345008",
    inStock: true,
    quantity: "190",
    progress: 40,
    rating: 3
  },
  {
    checked: false,
    companyName: "Reallinks",
    country: "United Kingdom",
    name: "LL Road Front Wheel",
    sellDate: "14/05/2020",
    orderId: "62-1065350",
    inStock: true,
    quantity: "184",
    progress: 30,
    rating: 4
  },
  {
    checked: false,
    companyName: "Quaxo",
    country: "United States",
    name: "ML Road Front Wheel",
    sellDate: "23/03/2020",
    orderId: "44-7241323",
    inStock: true,
    quantity: "169",
    progress: 30,
    rating: 4
  },
  {
    checked: false,
    companyName: "Devify",
    country: "China",
    name: "HL Road Front Wheel",
    sellDate: "12/12/2020",
    orderId: "52-0295699",
    inStock: false,
    quantity: "152",
    progress: 40,
    rating: 4
  },
  {
    checked: false,
    companyName: "Youopia",
    country: "Angola",
    name: "LL Mountain Handlebars",
    sellDate: "01/04/2020",
    orderId: "52-2650922",
    inStock: false,
    quantity: "182",
    progress: 60,
    rating: 4
  },
  {
    checked: false,
    companyName: "Ainyx",
    country: "China",
    name: "Touring Pedal",
    sellDate: "27/02/2020",
    orderId: "48-3618525",
    inStock: true,
    quantity: "141",
    progress: 60,
    rating: 1
  },
  {
    checked: false,
    companyName: "Browsetype",
    country: "Malaysia",
    name: "ML Mountain Handlebars",
    sellDate: "28/04/2020",
    orderId: "51-8893923",
    inStock: true,
    quantity: "169",
    progress: 70,
    rating: 1
  },
  {
    checked: false,
    companyName: "Muxo",
    country: "China",
    name: "HL Mountain Handlebars",
    sellDate: "22/08/2020",
    orderId: "68-5911361",
    inStock: false,
    quantity: "39",
    progress: 70,
    rating: 1
  },
  {
    checked: false,
    companyName: "Bubbletube",
    country: "China",
    name: "LL Road Handlebars",
    sellDate: "04/10/2020",
    orderId: "41-5880042",
    inStock: true,
    quantity: "71",
    progress: 80,
    rating: 3
  },
  {
    checked: false,
    companyName: "Fadeo",
    country: "Vietnam",
    name: "ML Road Handlebars",
    sellDate: "23/04/2020",
    orderId: "90-5913983",
    inStock: true,
    quantity: "148",
    progress: 100,
    rating: 3
  },
  {
    checked: false,
    companyName: "Yadel",
    country: "United Kingdom",
    name: "HL Road Handlebars",
    sellDate: "18/04/2020",
    orderId: "92-0960699",
    inStock: true,
    quantity: "116",
    progress: 80,
    rating: 1
  },
  {
    checked: false,
    companyName: "Blognation",
    country: "China",
    name: "LL Headset",
    sellDate: "10/01/2020",
    orderId: "06-9493898",
    inStock: true,
    quantity: "96",
    progress: 100,
    rating: 1
  },
  {
    checked: false,
    companyName: "Devpoint",
    country: "China",
    name: "ML Headset",
    sellDate: "25/12/2020",
    orderId: "69-5878565",
    inStock: true,
    quantity: "35",
    progress: 40,
    rating: 2
  },
  {
    checked: false,
    companyName: "Aibox",
    country: "United Kingdom",
    name: "HL Headset",
    sellDate: "18/03/2020",
    orderId: "13-1133017",
    inStock: true,
    quantity: "16",
    progress: 80,
    rating: 2
  },
  {
    checked: false,
    companyName: "Brightdog",
    country: "China",
    name: "LL Mountain Pedal",
    sellDate: "11/09/2020",
    orderId: "39-6530433",
    inStock: true,
    quantity: "194",
    progress: 20,
    rating: 5
  },
  {
    checked: false,
    companyName: "Gabcube",
    country: "Nigeria",
    name: "ML Mountain Pedal",
    sellDate: "22/04/2020",
    orderId: "96-6860388",
    inStock: true,
    quantity: "24",
    progress: 10,
    rating: 3
  },
  {
    checked: false,
    companyName: "Muxo",
    country: "China",
    name: "HL Mountain Pedal",
    sellDate: "05/06/2020",
    orderId: "30-0356137",
    inStock: true,
    quantity: "170",
    progress: 40,
    rating: 4
  },
  {
    checked: false,
    companyName: "Tambee",
    country: "China",
    name: "ML Touring Seat/Saddle",
    sellDate: "22/02/2020",
    orderId: "93-9058255",
    inStock: true,
    quantity: "184",
    progress: 90,
    rating: 5
  },
  {
    checked: false,
    companyName: "Cogilith",
    country: "India",
    name: "LL Touring Seat/Saddle",
    sellDate: "06/04/2020",
    orderId: "82-9268909",
    inStock: false,
    quantity: "153",
    progress: 100,
    rating: 4
  },
  {
    checked: false,
    companyName: "Dynabox",
    country: "Hong Kong",
    name: "HL Touring Seat/Saddle",
    sellDate: "10/01/2020",
    orderId: "20-6913815",
    inStock: false,
    quantity: "88",
    progress: 100,
    rating: 1
  },
  {
    checked: false,
    companyName: "Shuffledrive",
    country: "Sudan",
    name: "LL Road Pedal",
    sellDate: "16/09/2020",
    orderId: "08-8238817",
    inStock: true,
    quantity: "57",
    progress: 90,
    rating: 2
  },
  {
    checked: false,
    companyName: "Fivechat",
    country: "China",
    name: "ML Road Pedal",
    sellDate: "26/08/2020",
    orderId: "44-7370350",
    inStock: false,
    quantity: "62",
    progress: 40,
    rating: 1
  },
  {
    checked: false,
    companyName: "Meembee",
    country: "United States",
    name: "HL Road Pedal",
    sellDate: "27/12/2020",
    orderId: "01-3525949",
    inStock: true,
    quantity: "123",
    progress: 20,
    rating: 4
  },
  {
    checked: false,
    companyName: "Dynazzy",
    country: "United Kingdom",
    name: "LL Mountain Seat/Saddle 1",
    sellDate: "15/12/2020",
    orderId: "04-2414623",
    inStock: true,
    quantity: "77",
    progress: 100,
    rating: 5
  },
  {
    checked: false,
    companyName: "Eare",
    country: "China",
    name: "ML Mountain Seat/Saddle 1",
    sellDate: "04/04/2020",
    orderId: "15-1917509",
    inStock: false,
    quantity: "199",
    progress: 90,
    rating: 4
  },
  {
    checked: false,
    companyName: "Yozio",
    country: "China",
    name: "HL Mountain Seat/Saddle 1",
    sellDate: "15/03/2020",
    orderId: "06-2526845",
    inStock: true,
    quantity: "149",
    progress: 80,
    rating: 2
  },
  {
    checked: false,
    companyName: "Quinu",
    country: "Xi'an",
    name: "425-777-7829",
    sellDate: "22/02/2020",
    orderId: "83-1713558",
    inStock: false,
    quantity: "191",
    progress: 90,
    rating: 5
  },
  {
    checked: false,
    companyName: "Jazzy",
    country: "United Kingdom",
    name: "ML Road Seat/Saddle 1",
    sellDate: "07/08/2020",
    orderId: "00-8892524",
    inStock: true,
    quantity: "150",
    progress: 100,
    rating: 2
  },
  {
    checked: false,
    companyName: "Thoughtsphere",
    country: "China",
    name: "HL Road Seat/Saddle 1",
    sellDate: "28/11/2020",
    orderId: "39-5538991",
    inStock: true,
    quantity: "130",
    progress: 70,
    rating: 3
  },
  {
    checked: false,
    companyName: "Leenti",
    country: "China",
    name: "ML Road Rear Wheel",
    sellDate: "29/12/2020",
    orderId: "06-9002973",
    inStock: true,
    quantity: "179",
    progress: 10,
    rating: 2
  },
  {
    checked: false,
    companyName: "Quaxo",
    country: "United Kingdom",
    name: "HL Road Rear Wheel",
    sellDate: "06/09/2020",
    orderId: "73-6104901",
    inStock: true,
    quantity: "98",
    progress: 50,
    rating: 3
  },
  {
    checked: false,
    companyName: "Tanoodle",
    country: "Chile",
    name: "LL Mountain Seat/Saddle 2",
    sellDate: "24/05/2020",
    orderId: "68-7384479",
    inStock: true,
    quantity: "175",
    progress: 20,
    rating: 3
  },
  {
    checked: false,
    companyName: "Feednation",
    country: "China",
    name: "ML Mountain Seat/Saddle 2",
    sellDate: "21/11/2020",
    orderId: "26-7757763",
    inStock: true,
    quantity: "11",
    progress: 10,
    rating: 3
  },
  {
    checked: false,
    companyName: "Kayveo",
    country: "China",
    name: "HL Mountain Seat/Saddle 2",
    sellDate: "21/06/2020",
    orderId: "07-4873562",
    inStock: false,
    quantity: "184",
    progress: 70,
    rating: 4
  },
  {
    checked: false,
    companyName: "Meevee",
    country: "Saudi Arabia",
    name: "LL Road Seat/Saddle 1",
    sellDate: "16/11/2020",
    orderId: "46-5819554",
    inStock: false,
    quantity: "27",
    progress: 90,
    rating: 3
  },
  {
    checked: false,
    companyName: "Twitterworks",
    country: "China",
    name: "ML Road Seat/Saddle 2",
    sellDate: "19/04/2020",
    orderId: "01-2666826",
    inStock: true,
    quantity: "186",
    progress: 30,
    rating: 2
  },
  {
    checked: false,
    companyName: "Wikizz",
    country: "Tanzania",
    name: "HL Road Seat/Saddle 2",
    sellDate: "08/03/2020",
    orderId: "54-7090503",
    inStock: true,
    quantity: "20",
    progress: 30,
    rating: 3
  },
  {
    checked: false,
    companyName: "Yoveo",
    country: "United States",
    name: "LL Mountain Tire",
    sellDate: "14/10/2020",
    orderId: "78-7658520",
    inStock: false,
    quantity: "153",
    progress: 20,
    rating: 1
  },
  {
    checked: false,
    companyName: "Yakidoo",
    country: "China",
    name: "ML Mountain Tire",
    sellDate: "12/10/2020",
    orderId: "23-9926318",
    inStock: true,
    quantity: "161",
    progress: 80,
    rating: 5
  },
  {
    checked: false,
    companyName: "Oyope",
    country: "China",
    name: "HL Mountain Tire",
    sellDate: "20/09/2020",
    orderId: "20-0179517",
    inStock: true,
    quantity: "98",
    progress: 100,
    rating: 5
  },
  {
    checked: false,
    companyName: "Skipstorm",
    country: "United States",
    name: "LL Road Tire",
    sellDate: "01/10/2020",
    orderId: "02-9543343",
    inStock: true,
    quantity: "30",
    progress: 70,
    rating: 3
  },
  {
    checked: false,
    companyName: "Minyx",
    country: "United States",
    name: "ML Road Tire",
    sellDate: "07/07/2020",
    orderId: "98-3938169",
    inStock: true,
    quantity: "73",
    progress: 100,
    rating: 2
  },
  {
    checked: false,
    companyName: "Miboo",
    country: "China",
    name: "HL Road Tire",
    sellDate: "25/07/2020",
    orderId: "68-5197934",
    inStock: true,
    quantity: "158",
    progress: 90,
    rating: 1
  },
  {
    checked: false,
    companyName: "Realfire",
    country: "United States",
    name: "Touring Tire",
    sellDate: "27/08/2020",
    orderId: "39-8260460",
    inStock: true,
    quantity: "122",
    progress: 50,
    rating: 2
  },
  {
    checked: false,
    companyName: "Shufflester",
    country: "China",
    name: "Mountain Tire Tube",
    sellDate: "08/06/2020",
    orderId: "45-9776170",
    inStock: true,
    quantity: "33",
    progress: 20,
    rating: 4
  },
  {
    checked: false,
    companyName: "Ntag",
    country: "China",
    name: "Road Tire Tube",
    sellDate: "06/12/2020",
    orderId: "45-0858451",
    inStock: true,
    quantity: "107",
    progress: 60,
    rating: 2
  },
  {
    checked: false,
    companyName: "Jabberbean",
    country: "United States",
    name: "Touring Tire Tube",
    sellDate: "26/04/2020",
    orderId: "15-4247305",
    inStock: true,
    quantity: "15",
    progress: 10,
    rating: 2
  },
  {
    checked: false,
    companyName: "Thoughtblab",
    country: "China",
    name: "LL Bottom Bracket",
    sellDate: "21/05/2020",
    orderId: "15-8534931",
    inStock: true,
    quantity: "168",
    progress: 50,
    rating: 2
  },
  {
    checked: false,
    companyName: "Jabbertype",
    country: "China",
    name: "Classic Vest",
    sellDate: "25/07/2020",
    orderId: "23-1251557",
    inStock: true,
    quantity: "135",
    progress: 40,
    rating: 2
  },
  {
    checked: false,
    companyName: "Buzzshare",
    country: "United Kingdom",
    name: "Cycling Cap",
    sellDate: "07/07/2020",
    orderId: "86-5920601",
    inStock: true,
    quantity: "11",
    progress: 10,
    rating: 4
  },
  {
    checked: false,
    companyName: "Roodel",
    country: "United States",
    name: "Full-Finger Gloves",
    sellDate: "13/01/2020",
    orderId: "48-1055459",
    inStock: true,
    quantity: "41",
    progress: 60,
    rating: 4
  },
  {
    checked: false,
    companyName: "Zoovu",
    country: "China",
    name: "Half-Finger Gloves",
    sellDate: "03/06/2020",
    orderId: "12-7842022",
    inStock: true,
    quantity: "144",
    progress: 60,
    rating: 1
  },
  {
    checked: false,
    companyName: "Photofeed",
    country: "China",
    name: "HL Mountain Frame",
    sellDate: "14/07/2020",
    orderId: "94-5088099",
    inStock: true,
    quantity: "106",
    progress: 10,
    rating: 4
  }
];

export const ODD_ROW_CLASS = "odd";

export const MESSAGE = {
  BAD_VALUE: "#bad-value#"
};
