/* eslint-disable no-unused-vars */
import { Config, Context } from '@netlify/edge-functions';
import { getFrameworkFromCookie } from '../cookieHelper.mts';

const redirectsMap = {
  'row-sorting': '/rows-sorting/',
  'column-sorting': '/rows-sorting/',
  'release-notes': '/changelog/',
  accessibility: '/accessibility/',
  'angular-modules': '/angular-modules/',
  api: '/api/',
  'api/base-plugin': '/api/base-plugin/',
  'api/collapsible-columns': '/api/collapsible-columns/',
  'api/comments': '/api/comments/',
  'api/context-menu': '/api/context-menu/',
  'api/core': '/api/core/',
  'api/custom-borders': '/api/custom-borders/',
  'api/hooks': '/api/hooks/',
  'api/index-mapper': '/api/index-mapper/',
  'api/manual-column-freeze': '/api/manual-column-freeze/',
  'api/multi-column-sorting': '/api/multi-column-sorting/',
  'api/nested-rows': '/api/nested-rows/',
  'api/options': '/api/options/',
  'api/plugins': '/api/plugins/',
  'api/shortcut-manager': '/api/shortcut-manager',
  'api/undo-redo': '/api/undo-redo/',
  'autocomplete-cell-type': '/autocomplete-cell-type/',
  'autofill-values': '/autofill-values/',
  'basic-clipboard': '/basic-clipboard/',
  'batch-operations': '/batch-operations/',
  'binding-to-data': '/binding-to-data/',
  building: '/custom-builds/',
  'bundle-size': '/bundle-size/',
  'cell-editor': '/cell-editor/',
  'cell-function': '/cell-function/',
  'cell-renderer': '/cell-renderer/',
  'cell-type': '/cell-type/',
  'cell-validator': '/cell-validator/',
  changelog: '/changelog',
  'checkbox-cell-type': '/checkbox-cell-type/',
  'column-filter': '/column-filter/',
  'column-freezing': '/column-freezing',
  'column-groups': '/column-groups/',
  'column-header': '/column-header/',
  'column-hiding': '/column-hiding/',
  'column-menu': '/column-menu/',
  'column-moving': '/column-moving/',
  'column-summary': '/column-summary/',
  'column-virtualization': '/column-virtualization/',
  'column-width': '/column-width/',
  comments: '/comments/',
  'conditional-formatting': '/conditional-formatting/',
  'configuration-options': '/configuration-options/',
  'context-menu': '/context-menu',
  'custom-builds': '/custom-builds/',
  'custom-plugins': '/custom-plugins/',
  'custom-shortcuts': '/custom-shortcuts/',
  'date-cell-type': '/date-cell-type/',
  'demo': '/demo/',
  'deprecation-policy': '/deprecation-policy/',
  'dialog': '/dialog/',
  'disabled-cells': '/disabled-cells/',
  'documentation-license': '/documentation-license/',
  'dropdown-cell-type': '/dropdown-cell-type/',
  'events-and-hooks': '/events-and-hooks/',
  examples: '/',
  'export-to-csv': '/export-to-csv/',
  'formatting-cells': '/formatting-cells/',
  'formula-calculation': '/formula-calculation/',
  'grid-size': '/grid-size/',
  'handsontable-cell-type': '/handsontable-cell-type/',
  'handsontable-design-system': '/handsontable-design-system/',
  'hello-world': '/demo/',
  'icon-pack': '/icon-pack/',
  'ime-support': '/ime-support/',
  installation: '/installation/',
  'keyboard-shortcuts': '/keyboard-shortcuts',
  language: '/language/',
  'layout-direction': '/layout-direction',
  'legacy-style': '/legacy-style/',
  'license-key': '/license-key',
  'loading': '/loading/',
  locale: '/locale/',
  'long-term-support': '/long-term-support/',
  'merge-cells': '/merge-cells/',
  'migration-from-10.0-to-11.0': '/migration-from-10.0-to-11.0/',
  'migration-from-11.1-to-12.0': '/migration-from-11.1-to-12.0',
  'migration-from-12.4-to-13.0': '/migration-from-12.4-to-13.0/',
  'migration-from-13.1-to-14.0': '/migration-from-13.1-to-14.0/',
  'migration-from-14.6-to-15.0': '/migration-from-14.6-to-15.0/',
  'migration-from-15.3-to-16.0': '/migration-from-15.3-to-16.0/',
  'migration-from-16.0-to-16.1': '/migration-from-16.0-to-16.1/',
  'migration-from-7.4-to-8.0': '/migration-from-7.4-to-8.0/',
  'migration-from-8.4-to-9.0': '/migration-from-8.4-to-9.0/',
  'migration-from-9.0-to-10.0': '/migration-from-9.0-to-10.0/',
  modules: '/modules/',
  'numeric-cell-type': '/numeric-cell-type/',
  packages: '/packages/',
  'password-cell-type': '/password-cell-type/',
  performance: '/performance/',
  plugins: '/custom-plugins/',
  'row-freezing': '/row-freezing/',
  'row-header': '/row-header/',
  'row-height': '/row-height/',
  'row-hiding': '/row-hiding/',
  'row-moving': '/row-moving/',
  'row-parent-child': '/row-parent-child/',
  'row-prepopulating': '/row-prepopulating/',
  'row-trimming': '/row-trimming/',
  'row-virtualization': '/row-virtualization/',
  'rows-pagination': '/rows-pagination/',
  'rows-sorting': '/rows-sorting',
  'saving-data': '/saving-data/',
  'searching-values': '/searching-values/',
  security: '/security/',
  'select-cell-type': '/select-cell-type/',
  selection: '/selection/',
  'setting-options': '/configuration-options/',
  'software-license': '/software-license/',
  'supported-browsers': '/supported-browsers/',
  'testing': '/testing/',
  'text-alignment': '/text-alignment/',
  'theme-customization': '/theme-customization/',
  themes: '/themes',
  'third-party-licenses': '/third-party-licenses/',
  'time-cell-type': '/time-cell-type/',
  'undo-redo': '/undo-redo/',
  'versioning-policy': '/versioning-policy/',
  'vue-basic-example': '/vue-basic-example/',
  'vue-custom-context-menu-example': '/vue-custom-context-menu-example/',
  'vue-custom-editor-example': '/vue-custom-editor-example/',
  'vue-custom-id-class-style': '/vue-custom-id-class-style/',
  'vue-custom-renderer-example': '/vue-custom-renderer-example/',
  'vue-hot-column': '/vue-hot-column/',
  'vue-hot-reference': '/vue-hot-reference/',
  'vue-installation': '/vue-installation/',
  'vue-language-change-example': '/vue-language-change-example/',
  'vue-modules': '/vue-modules/',
  'vue-setting-up-a-translation': '/vue-setting-up-a-translation/',
  'vue-simple-example': '/vue-basic-example/',
  'vue-vuex-example': '/vue-vuex-example/',
  'vue3-basic-example': '/vue3-basic-example/',
  'vue3-custom-context-menu-example': '/vue3-custom-context-menu-example/',
  'vue3-custom-editor-example': '/vue3-custom-editor-example/',
  'vue3-custom-id-class-style': '/vue3-custom-id-class-style/',
  'vue3-custom-renderer-example': '/vue3-custom-renderer-example/',
  'vue3-hot-column': '/vue3-hot-column/',
  'vue3-hot-reference': '/vue3-hot-reference/',
  'vue3-installation': '/vue3-installation/',
  'vue3-language-change-example': '/vue3-language-change-example/',
  'vue3-modules': '/vue3-modules/',
  'vue3-setting-up-a-translation': '/vue3-setting-up-a-translation/',
  'vue3-simple-example': '/vue3-basic-example/',
  'vue3-vuex-example': '/vue3-vuex-example/'
};

export default async(req: Request, context: Context) => {

  const framework = getFrameworkFromCookie(context.cookies.get('docs_fw'));
  const page = context.params[0];
  const redirectPath = redirectsMap[page];

  const url = new URL(`/docs/${framework}${redirectPath}`, req.url);

  return Response.redirect(url);
};

export const config: Config = {
  path: `/docs/(${Object.keys(redirectsMap).join('|')}){/}?`
};
