import './autocompleteType';
import './checkboxType';
import './dateType';
import './dropdownType';
import './handsontableType';
import './numericType';
import './passwordType';
import './textType';
import './timeType';
