import '../../';
import { getPluginsNames } from '../';

describe('built-in plugins', () => {
  it('should auto-register build-in plugins in the proper order in full build', () => {
    expect(getPluginsNames()).toEqual([
      'AutoColumnSize',
      'Autofill',
      'SelectionHandles',
      'MoveCells',
      'ManualRowResize',
      'AutoRowSize',
      'AutoRowHeaderSize',
      'ColumnSorting',
      'Comments',
      'ContextMenu',
      'CopyPaste',
      'CustomBorders',
      'DragToScroll',
      'ManualColumnFreeze',
      'ManualColumnMove',
      'ManualColumnResize',
      'ManualRowMove',
      'MergeCells',
      'StretchColumns',
      'MultipleSelectionHandles',
      'MultiColumnSorting',
      'Search',
      'TouchScroll',
      'BindRowsWithHeaders',
      'ColumnSummary',
      'DropdownMenu',
      'ExportFile',
      'Filters',
      'Formulas',
      'FormulaBuilder',
      'NestedHeaders',
      'CollapsibleColumns',
      'NestedRows',
      'HiddenColumns',
      'HiddenRows',
      'TrimRows',
      'Loading',
      'Dialog',
      'EmptyDataState',
      'Notification',
      'Pagination',
      'DataProvider',
      'UndoRedo',
    ]);
  });
});
