
[build]
  base = "docs/netlify"
  command = "echo 'default context'"
  publish = "docs"
  #functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"
[functions]
  node_bundler = "esbuild"