import type { HotInstance } from '../core/types';
import type { SanitizerContext, SanitizerFn } from '../core/settings';
import { HTML_CHARACTERS, SANITIZER_WARN_KEY, missingSanitizerMessage } from '../helpers/dom/element';
import { warnOnce } from '../helpers/console';

/**
 * Re-exported for the plugins that hold a resolved sanitizer (`dialog`, `notification`).
 *
 * `SanitizerFn` stays internal: the published `exports` map (generated by
 * `scripts/prepare-package-for-publish.mjs`, not the source manifest) has no `./utils/*` entry and no
 * `./*` wildcard, so this module is unreachable from an installed package. `SanitizerContext` is the
 * type users are given, from `handsontable` itself.
 */
export type { SanitizerContext, SanitizerFn } from '../core/settings';

/**
 * Reads the grid-level `sanitizer` option in the form `fastInnerHTML` expects.
 *
 * Every call site that writes cell or header content through `fastInnerHTML` goes through this
 * helper, so they cannot drift apart on the fallback value or on how the option is looked up.
 * `true` is the fallback, which makes `fastInnerHTML` write raw HTML and warn once.
 *
 * The `html` cell type and `allowHtml` autocomplete sources deliberately do not use this helper:
 * they render raw HTML by design (see PR #7368) and pass `false` instead.
 *
 * @param {object} hot The Handsontable instance.
 * @returns {boolean|Function} The configured sanitizer, or `true` when none is set.
 */
export function getSanitizer(hot: HotInstance): boolean | SanitizerFn {
  return hot.getSettings().sanitizer ?? true;
}

/**
 * Sanitizes an HTML string for surfaces that build markup as a string instead of writing it
 * into an element through `fastInnerHTML` — the clipboard paste path and the nested-header
 * ghost table.
 *
 * A configured sanitizer sees every payload, markup or not, which is what the clipboard path has
 * always done. Only the missing-sanitizer warning is gated on markup. A caller that must match
 * `fastInnerHTML` exactly, where plain text never reaches the sanitizer at all, has to apply that
 * test itself before calling this. The nested-header ghost table does, so the label it measures is
 * treated the same way as the header that renders it.
 *
 * The warning is bound to `hot.rootElement`, the scope every other surface uses, so all of them
 * collapse into a single message per Handsontable instance.
 *
 * @param {object} hot The Handsontable instance.
 * @param {string} html The HTML string to sanitize.
 * @param {SanitizerContext} context The write surface, passed to the sanitizer and named in the warning.
 * @returns {string} The sanitized string, or the input unchanged when no sanitizer is configured.
 */
export function sanitizeHTML(hot: HotInstance, html: string, context: SanitizerContext): string {
  // An absent clipboard flavour reads as `''`. There is nothing to sanitize and nothing to warn
  // about, and calling the sanitizer would add a spurious entry to an auditing one on every paste.
  if (!html) {
    return html;
  }

  const { sanitizer } = hot.getSettings();

  // A configured sanitizer sees every payload, markup or not. Both callers behaved that way before
  // this helper existed, and a sanitizer is not always an XSS filter - it may cap length, normalize
  // whitespace, or record an audit entry, none of which it can do for input it never receives.
  if (typeof sanitizer === 'function') {
    return sanitizer(html, context) ?? '';
  }

  // The warning is the only part gated on markup: plain text cannot inject anything, so warning
  // about it would be noise on every grid that writes an ordinary label.
  if (HTML_CHARACTERS.test(html)) {
    warnOnce(hot.rootElement, SANITIZER_WARN_KEY, missingSanitizerMessage(context));
  }

  return html;
}
