export default {
  fontSize: "14px",
  fontSizeSmall: "12px",
  lineHeight: "20px",
  lineHeightSmall: "18px",
  fontWeight: "400",
  letterSpacing: "0px",
  gapSize: "density.gap",
  iconSize: "sizing.size_4",
  tableTransition: "0.2s",
  borderColor: ["colors.palette.100", "colors.palette.800"],
  accentColor: ["colors.primary.500", "colors.primary.200"],
  foregroundColor: ["colors.palette.600", "colors.palette.300"],
  foregroundSecondaryColor: ["colors.palette.700", "colors.palette.400"],
  backgroundColor: ["colors.white", "colors.palette.950"],
  backgroundSecondaryColor: ["colors.palette.50", "colors.palette.900"],
  placeholderColor: ["colors.palette.400", "colors.palette.500"],
  readOnlyColor: ["colors.palette.600", "colors.palette.300"],
  disabledColor: ["colors.palette.400", "colors.palette.500"],
  shadowColor: ["colors.palette.600", "colors.palette.300"],
  shadowX: "sizing.size_0",
  shadowY: "sizing.size_2",
  shadowBlur: "sizing.size_4",
  shadowOpacity: "6%",
  barForegroundColor: "themes.foregroundColor",
  barBackgroundColor: "themes.backgroundSecondaryColor",
  barHorizontalPadding: "density.barsHorizontal",
  barVerticalPadding: "density.barsVertical",
  cellHorizontalBorderColor: "colors.transparent",
  cellVerticalBorderColor: "themes.borderColor",
  wrapperBorderWidth: "0px",
  wrapperBorderRadius: "sizing.size_3",
  wrapperBorderColor: "themes.borderColor",
  rowHeaderOddBackgroundColor: "themes.backgroundColor",
  rowHeaderEvenBackgroundColor: "themes.backgroundSecondaryColor",
  rowCellOddBackgroundColor: "themes.backgroundColor",
  rowCellEvenBackgroundColor: "themes.backgroundSecondaryColor",
  cellHorizontalPadding: "density.cellHorizontal",
  cellVerticalPadding: "density.cellVertical",
  cellEditorBorderWidth: "2px",
  cellEditorBorderColor: "themes.accentColor",
  cellEditorForegroundColor: ["colors.palette.950", "colors.white"],
  cellEditorBackgroundColor: "themes.backgroundColor",
  cellEditorShadowBlurRadius: "8px",
  cellEditorShadowColor: "themes.accentColor",
  cellSuccessBackgroundColor: "#37bc6c4d",
  cellErrorBackgroundColor: "#fa4d324d",
  cellReadOnlyBackgroundColor: "themes.backgroundSecondaryColor",
  cellSelectionBorderColor: "themes.accentColor",
  cellSelectionBackgroundColor: "themes.accentColor",
  cellAutofillSize: "sizing.size_1_5",
  cellAutofillHitAreaSize: "sizing.size_3",
  cellAutofillBorderWidth: "sizing.size_0_25",
  cellAutofillBorderRadius: "sizing.size_1",
  cellAutofillBorderColor: "themes.backgroundColor",
  cellAutofillBackgroundColor: "themes.accentColor",
  cellAutofillFillBorderColor: "themes.foregroundColor",
  cellMobileHandleSize: "sizing.size_3",
  cellMobileHandleBorderWidth: "sizing.size_0_25",
  cellMobileHandleBorderRadius: "sizing.size_3",
  cellMobileHandleBackgroundOpacity: "40%",
  resizeIndicatorColor: ["colors.palette.400", "colors.palette.500"],
  moveBacklightColor: ["colors.palette.800", "colors.palette.200"],
  moveBacklightOpacity: "6%",
  moveIndicatorColor: "themes.accentColor",
  hiddenIndicatorColor: ["colors.palette.400", "colors.palette.500"],
  scrollbarBorderRadius: "sizing.size_2",
  scrollbarTrackColor: "themes.backgroundSecondaryColor",
  scrollbarThumbColor: ["colors.palette.400", "colors.palette.500"],
  headerFontWeight: "themes.fontWeight",
  headerForegroundColor: "themes.foregroundColor",
  headerBackgroundColor: "themes.backgroundSecondaryColor",
  headerHighlightedShadowSize: "1px",
  headerHighlightedForegroundColor: "themes.foregroundColor",
  headerHighlightedBackgroundColor: ["colors.palette.100", "colors.palette.800"],
  headerActiveBorderColor: ["colors.palette.800", "colors.primary.100"],
  headerActiveForegroundColor: "themes.backgroundColor",
  headerActiveBackgroundColor: ["colors.palette.950", "colors.primary.200"],
  headerFilterBackgroundColor: "themes.cellSuccessBackgroundColor",
  headerRowForegroundColor: "themes.foregroundColor",
  headerRowBackgroundColor: "themes.backgroundColor",
  headerRowHighlightedForegroundColor: "themes.foregroundColor",
  headerRowHighlightedBackgroundColor: ["colors.palette.100", "colors.palette.800"],
  headerRowActiveForegroundColor: "themes.backgroundColor",
  headerRowActiveBackgroundColor: ["colors.palette.950", "colors.primary.200"],
  checkboxSize: "themes.iconSize",
  checkboxBorderRadius: "sizing.size_1_5",
  checkboxBorderColor: ["colors.palette.400", "colors.palette.500"],
  checkboxBackgroundColor: "themes.backgroundColor",
  checkboxIconColor: "colors.transparent",
  checkboxFocusBorderColor: ["colors.palette.400", "colors.palette.500"],
  checkboxFocusBackgroundColor: "themes.backgroundColor",
  checkboxFocusIconColor: "colors.transparent",
  checkboxFocusRingColor: "themes.accentColor",
  checkboxDisabledBorderColor: ["colors.palette.400", "colors.palette.500"],
  checkboxDisabledBackgroundColor: ["colors.palette.50", "colors.palette.900"],
  checkboxDisabledIconColor: "colors.transparent",
  checkboxCheckedBorderColor: ["colors.primary.400", "colors.primary.300"],
  checkboxCheckedBackgroundColor: "themes.accentColor",
  checkboxCheckedIconColor: "themes.backgroundColor",
  checkboxCheckedFocusBorderColor: "themes.backgroundColor",
  checkboxCheckedFocusBackgroundColor: "themes.accentColor",
  checkboxCheckedFocusIconColor: "themes.backgroundColor",
  checkboxCheckedDisabledBorderColor: ["colors.palette.400", "colors.palette.500"],
  checkboxCheckedDisabledBackgroundColor: ["colors.palette.50", "colors.palette.900"],
  checkboxCheckedDisabledIconColor: "themes.disabledColor",
  checkboxIndeterminateBorderColor: ["colors.primary.400", "colors.primary.300"],
  checkboxIndeterminateBackgroundColor: "themes.accentColor",
  checkboxIndeterminateIconColor: "themes.backgroundColor",
  checkboxIndeterminateFocusBorderColor: "themes.backgroundColor",
  checkboxIndeterminateFocusBackgroundColor: "themes.accentColor",
  checkboxIndeterminateFocusIconColor: "themes.backgroundColor",
  checkboxIndeterminateDisabledBorderColor: ["colors.palette.400", "colors.palette.500"],
  checkboxIndeterminateDisabledBackgroundColor: ["colors.palette.50", "colors.palette.900"],
  checkboxIndeterminateDisabledIconColor: "themes.disabledColor",
  radioSize: "themes.iconSize",
  radioBorderColor: ["colors.palette.400", "colors.palette.500"],
  radioBackgroundColor: "themes.backgroundColor",
  radioIconColor: "colors.transparent",
  radioFocusBorderColor: ["colors.palette.400", "colors.palette.500"],
  radioFocusBackgroundColor: "themes.backgroundColor",
  radioFocusIconColor: "colors.transparent",
  radioFocusRingColor: "themes.accentColor",
  radioDisabledBorderColor: ["colors.palette.400", "colors.palette.500"],
  radioDisabledBackgroundColor: "themes.backgroundSecondaryColor",
  radioDisabledIconColor: "colors.transparent",
  radioCheckedBorderColor: "themes.accentColor",
  radioCheckedBackgroundColor: "themes.backgroundColor",
  radioCheckedIconColor: "themes.accentColor",
  radioCheckedFocusBorderColor: ["colors.primary.400", "colors.primary.300"],
  radioCheckedFocusBackgroundColor: "themes.backgroundColor",
  radioCheckedFocusIconColor: "themes.accentColor",
  radioCheckedDisabledBorderColor: ["colors.palette.400", "colors.palette.500"],
  radioCheckedDisabledBackgroundColor: "themes.backgroundSecondaryColor",
  radioCheckedDisabledIconColor: "themes.disabledColor",
  iconButtonBorderRadius: "sizing.size_4",
  iconButtonLargeBorderRadius: "sizing.size_1",
  iconButtonLargePadding: "sizing.size_1",
  iconButtonBorderColor: ["colors.palette.50", "colors.palette.900"],
  iconButtonBackgroundColor: "themes.backgroundSecondaryColor",
  iconButtonIconColor: ["colors.palette.400", "colors.palette.500"],
  iconButtonHoverBorderColor: ["colors.palette.200", "colors.palette.700"],
  iconButtonHoverBackgroundColor: ["colors.palette.200", "colors.palette.700"],
  iconButtonHoverIconColor: "themes.foregroundColor",
  iconButtonActiveBorderColor: "colors.transparent",
  iconButtonActiveBackgroundColor: "colors.transparent",
  iconButtonActiveIconColor: "themes.backgroundColor",
  iconButtonActiveHoverBorderColor: "colors.transparent",
  iconButtonActiveHoverBackgroundColor: ["colors.palette.950", "colors.primary.200"],
  iconButtonActiveHoverIconColor: "themes.backgroundColor",
  collapseButtonBorderRadius: "sizing.size_4",
  collapseButtonOpenBorderColor: "colors.transparent",
  collapseButtonOpenBackgroundColor: "colors.transparent",
  collapseButtonOpenIconColor: ["colors.palette.700", "colors.palette.400"],
  collapseButtonOpenIconActiveColor: ["colors.palette.400", "colors.palette.500"],
  collapseButtonOpenHoverBorderColor: "colors.transparent",
  collapseButtonOpenHoverBackgroundColor: "colors.transparent",
  collapseButtonOpenHoverIconColor: ["colors.palette.800", "colors.palette.200"],
  collapseButtonOpenHoverIconActiveColor: ["colors.white", "colors.palette.950"],
  collapseButtonCloseBorderColor: "colors.transparent",
  collapseButtonCloseBackgroundColor: "colors.transparent",
  collapseButtonCloseIconColor: ["colors.palette.700", "colors.palette.400"],
  collapseButtonCloseIconActiveColor: ["colors.palette.400", "colors.palette.500"],
  collapseButtonCloseHoverBorderColor: "colors.transparent",
  collapseButtonCloseHoverBackgroundColor: "colors.transparent",
  collapseButtonCloseHoverIconColor: ["colors.palette.800", "colors.palette.200"],
  collapseButtonCloseHoverIconActiveColor: ["colors.white", "colors.palette.950"],
  buttonBorderRadius: "sizing.size_4",
  buttonHorizontalPadding: "density.buttonHorizontal",
  buttonVerticalPadding: "density.buttonVertical",
  primaryButtonBorderColor: "colors.transparent",
  primaryButtonForegroundColor: "themes.backgroundColor",
  primaryButtonBackgroundColor: "themes.accentColor",
  primaryButtonDisabledBorderColor: "colors.transparent",
  primaryButtonDisabledForegroundColor: "themes.disabledColor",
  primaryButtonDisabledBackgroundColor: ["colors.palette.200", "colors.palette.700"],
  primaryButtonHoverBorderColor: "colors.transparent",
  primaryButtonHoverForegroundColor: "themes.backgroundColor",
  primaryButtonHoverBackgroundColor: ["colors.primary.600", "colors.primary.100"],
  primaryButtonFocusBorderColor: "themes.backgroundColor",
  primaryButtonFocusForegroundColor: "themes.backgroundColor",
  primaryButtonFocusBackgroundColor: "themes.accentColor",
  secondaryButtonBorderColor: "themes.borderColor",
  secondaryButtonForegroundColor: "themes.foregroundColor",
  secondaryButtonBackgroundColor: "themes.backgroundColor",
  secondaryButtonDisabledBorderColor: "themes.borderColor",
  secondaryButtonDisabledForegroundColor: "themes.disabledColor",
  secondaryButtonDisabledBackgroundColor: ["colors.palette.50", "colors.palette.900"],
  secondaryButtonHoverBorderColor: "themes.borderColor",
  secondaryButtonHoverForegroundColor: "themes.foregroundColor",
  secondaryButtonHoverBackgroundColor: ["colors.palette.50", "colors.palette.900"],
  secondaryButtonFocusBorderColor: "themes.borderColor",
  secondaryButtonFocusForegroundColor: "themes.foregroundColor",
  secondaryButtonFocusBackgroundColor: "themes.backgroundColor",
  commentsTextareaHorizontalPadding: "density.cellHorizontal",
  commentsTextareaVerticalPadding: "density.cellVertical",
  commentsTextareaBorderWidth: "1px",
  commentsTextareaBorderColor: "colors.transparent",
  commentsTextareaForegroundColor: "themes.foregroundColor",
  commentsTextareaBackgroundColor: "themes.backgroundSecondaryColor",
  commentsTextareaFocusBorderWidth: "1px",
  commentsTextareaFocusBorderColor: "themes.accentColor",
  commentsTextareaFocusForegroundColor: "themes.foregroundColor",
  commentsTextareaFocusBackgroundColor: "themes.backgroundColor",
  commentsIndicatorSize: "sizing.size_1_5",
  commentsIndicatorColor: "themes.accentColor",
  licenseHorizontalPadding: "themes.barHorizontalPadding",
  licenseVerticalPadding: "themes.barVerticalPadding",
  licenseForegroundColor: "themes.barForegroundColor",
  licenseBackgroundColor: "themes.barBackgroundColor",
  linkColor: "themes.accentColor",
  linkHoverColor: ["colors.primary.600", "colors.primary.100"],
  inputBorderWidth: "1px",
  inputBorderRadius: "themes.checkboxBorderRadius",
  inputHorizontalPadding: "density.inputHorizontal",
  inputVerticalPadding: "density.inputVertical",
  inputBorderColor: "themes.borderColor",
  inputForegroundColor: "themes.foregroundColor",
  inputBackgroundColor: "themes.backgroundColor",
  inputHoverBorderColor: "themes.borderColor",
  inputHoverForegroundColor: "themes.foregroundColor",
  inputHoverBackgroundColor: "themes.backgroundColor",
  inputDisabledBorderColor: "themes.borderColor",
  inputDisabledForegroundColor: "themes.disabledColor",
  inputDisabledBackgroundColor: "themes.backgroundColor",
  inputFocusBorderColor: "themes.accentColor",
  inputFocusForegroundColor: "themes.foregroundColor",
  inputFocusBackgroundColor: "themes.backgroundColor",
  menuBorderWidth: "0px",
  menuBorderRadius: "sizing.size_3",
  menuHorizontalPadding: "density.menuHorizontal",
  menuVerticalPadding: "density.menuVertical",
  menuItemHorizontalPadding: "density.menuItemHorizontal",
  menuItemVerticalPadding: "density.menuItemVertical",
  menuBorderColor: "themes.borderColor",
  menuShadowX: "themes.shadowX",
  menuShadowY: "themes.shadowY",
  menuShadowBlur: "themes.shadowBlur",
  menuShadowColor: "themes.shadowColor",
  menuShadowOpacity: "6%",
  menuItemHoverColor: "themes.accentColor",
  menuItemHoverColorOpacity: "8%",
  menuItemActiveColor: "themes.accentColor",
  menuItemActiveColorOpacity: "12%",
  dialogSemiTransparentBackgroundColor: ["colors.white", "colors.palette.950"],
  dialogSemiTransparentBackgroundOpacity: "80%",
  dialogSolidBackgroundColor: ["colors.white", "colors.palette.950"],
  dialogContentPaddingHorizontal: "density.dialogHorizontal",
  dialogContentPaddingVertical: "density.dialogVertical",
  dialogContentBorderRadius: "sizing.size_4",
  dialogContentBackgroundColor: "themes.backgroundColor",
  paginationBarForegroundColor: "themes.barForegroundColor",
  paginationBarBackgroundColor: "themes.barBackgroundColor",
  paginationBarHorizontalPadding: "themes.barHorizontalPadding",
  paginationBarVerticalPadding: "themes.barVerticalPadding"
}