/**
 * Typed license key fixtures for the reader/classifier/grants unit tests.
 *
 * These keys are generated by the AUTHORITATIVE license-key package generator
 * (a different codebase from the reader under test), so they prove
 * cross-implementation format compatibility: if the reader and a hand-rolled
 * builder shared the same misunderstanding of the format, only fixtures from
 * the real generator would catch it. For adversarial and edge cases, forge keys
 * with the in-test builder (`./buildTestKey`) instead.
 *
 * The holder is the obviously-fake "Test Fixture" on purpose. A [FREE] key never
 * expires, so a committed real one would be a directly usable free key - the
 * test holder makes its origin unambiguous.
 *
 * All expiry-carrying keys use exp 2026-08-27 (UTC midnight = 1787788800000).
 * Pin `Date.now` in tests; never rely on the real clock.
 */

/* eslint-disable max-len */

/**
 * The UTC-midnight epoch of the fixtures' shared expiry date (2026-08-27).
 *
 * @type {number}
 */
export const FIXTURE_EXPIRY_TIMESTAMP = Date.UTC(2026, 7, 27);

/**
 * Trial, HT enterprise/internal, grace 15.
 *
 * @type {string}
 */
export const TRIAL_KEY = '[TRIAL]_this_{Handsontable}_key_is_granted_for_evaluation_only___Use_in_production_is_not_permitted___Please_report_misuse_to_legal@handsontable.com___For_purchasing_contact_sales@handsontable.com___Scope_{Enterprise}_only___This_key_will_deactivate_on_{27_August_2026}_for_{Test_Fixture}____eyJ2IjoxLCJob2xkZXIiOiJUZXN0IEZpeHR1cmUiLCJpc3MiOiIyMDI2LTA3LTIwIiwicHJvZHVjdHMiOnsiaGFuZHNvbnRhYmxlIjp7InRpZXIiOiJlbnRlcnByaXNlIiwibW9kZSI6ImludGVybmFsIiwiZXhwIjoiMjAyNi0wOC0yNyIsImdyYWNlIjoxNX19fQ2e0d5df54c159657a7fb00ea5947863798b2c21afea2b1df1fec4d267874026fa4e716e5129ad1c4d1a6b74c15401f69667526c4177e84f13d001b15fee005ac';

/**
 * Trial, HT enterprise/saas, grace 15.
 *
 * @type {string}
 */
export const TRIAL_SAAS_KEY = '[TRIAL]_this_{Handsontable}_key_is_granted_for_evaluation_only___Use_in_production_is_not_permitted___Please_report_misuse_to_legal@handsontable.com___For_purchasing_contact_sales@handsontable.com___Scope_{Enterprise_SaaS}_only___This_key_will_deactivate_on_{27_August_2026}_for_{Test_Fixture}____eyJ2IjoxLCJob2xkZXIiOiJUZXN0IEZpeHR1cmUiLCJpc3MiOiIyMDI2LTA3LTIwIiwicHJvZHVjdHMiOnsiaGFuZHNvbnRhYmxlIjp7InRpZXIiOiJlbnRlcnByaXNlIiwibW9kZSI6InNhYXMiLCJleHAiOiIyMDI2LTA4LTI3IiwiZ3JhY2UiOjE1fX1909fcbad3ff0cb4ff452f120ab118bf981e24a114c46bf2cc608a0b125c7fef97bfded95f040b4ea7066781ebc36d837587cdd1541487b28f825926676c0bf727';

/**
 * Freemium, HT + HF freemium, never expires.
 *
 * @type {string}
 */
export const FREEMIUM_KEY = '[FREE]_this_{Handsontable}_key_is_granted_under_the_Free_plan___Use_is_subject_to_the_Handsontable_Free_License_Terms___Features_beyond_the_Free_plan_require_a_commercial_license___To_upgrade_contact_sales@handsontable.com___Scope_{Free}_with_{HyperFormula_Free}___This_key_does_not_expire_for_{Test_Fixture}____eyJ2IjoxLCJob2xkZXIiOiJUZXN0IEZpeHR1cmUiLCJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsidGllciI6ImZyZWVtaXVtIn0sImh5cGVyZm9ybXVsYSI6eyJ0aWVyIjoiZnJlZW1pdW0ifX191f31d33c6c1d45709574d0eb833080ce51fb861c5f9c009dc527fc5524861338cd3946188716352e2e3cdab55fdc208b5f249e627626ef37b21ee83f4f62fc2b';

/**
 * Subscription, HT enterprise/internal, grace 90.
 *
 * @type {string}
 */
export const SUBSCRIPTION_KEY = '[SUB]_this_{Handsontable}_key_is_granted_under_a_subscription_license___Use_after_expiry_is_not_permitted_per_the_subscription_agreement___To_renew_contact_sales@handsontable.com___Scope_{Enterprise}_only___This_key_will_deactivate_on_{27_August_2026}_for_{Test_Fixture}____eyJ2IjoxLCJob2xkZXIiOiJUZXN0IEZpeHR1cmUiLCJpc3MiOiIyMDI2LTA3LTIwIiwicHJvZHVjdHMiOnsiaGFuZHNvbnRhYmxlIjp7InRpZXIiOiJlbnRlcnByaXNlIiwibW9kZSI6ImludGVybmFsIiwiZXhwIjoiMjAyNi0wOC0yNyIsImdyYWNlIjo5MH19fQdb8f6eb7e487f228ce1e9d5d5a9ba969d61fe739295391d75bd10e051393955c90be8a1449da3ae9306208db837b4a2ce2f4fadc15c63ed6ab33598bce45fab4';

/**
 * Subscription, HT enterprise/saas, grace 90.
 *
 * @type {string}
 */
export const SUBSCRIPTION_SAAS_KEY = '[SUB]_this_{Handsontable}_key_is_granted_under_a_subscription_license___Use_after_expiry_is_not_permitted_per_the_subscription_agreement___To_renew_contact_sales@handsontable.com___Scope_{Enterprise_SaaS}_only___This_key_will_deactivate_on_{27_August_2026}_for_{Test_Fixture}____eyJ2IjoxLCJob2xkZXIiOiJUZXN0IEZpeHR1cmUiLCJpc3MiOiIyMDI2LTA3LTIwIiwicHJvZHVjdHMiOnsiaGFuZHNvbnRhYmxlIjp7InRpZXIiOiJlbnRlcnByaXNlIiwibW9kZSI6InNhYXMiLCJleHAiOiIyMDI2LTA4LTI3IiwiZ3JhY2UiOjkwfX1992fc4640248581c8cda83402232f8da358fe83e55a21e812aeefa77dd865867f9c017afcff62f4ac9cb0c4da076bccbeccfe7a53da6d563963ec3976f9719943';

/**
 * Perpetual, HT enterprise, maintenance ends 2026-08-27.
 *
 * @type {string}
 */
export const PERPETUAL_KEY = '[PERP]_this_{Handsontable}_key_is_granted_under_a_perpetual_license___Access_to_new_versions_ends_when_maintenance_expires___Versions_released_before_that_date_may_be_used_indefinitely___To_renew_maintenance_contact_sales@handsontable.com___Scope_{Enterprise}_only___Maintenance_ends_on_{27_August_2026}_for_{Test_Fixture}____eyJ2IjoxLCJob2xkZXIiOiJUZXN0IEZpeHR1cmUiLCJwcm9kdWN0cyI6eyJoYW5kc29udGFibGUiOnsidGllciI6ImVudGVycHJpc2UiLCJleHAiOiIyMDI2LTA4LTI3In19fQdb1c28e4fbbe96530fae7860ec32d167054fa114e197014aad0beb8baff81c2149f1392ae7b4cc1938bce352d30313d7220dacf825b82543e064b10fc039c3a4';

/**
 * Subscription granting HF data_grid + spreadsheet & import_export add-ons.
 *
 * @type {string}
 */
export const HF_ADDONS_KEY = '[SUB]_this_{Handsontable}_key_is_granted_under_a_subscription_license___Use_after_expiry_is_not_permitted_per_the_subscription_agreement___To_renew_contact_sales@handsontable.com___Scope_{Enterprise}_with_{HyperFormula_Data_Grid}_and_{Spreadsheet_addon}_and_{Import_Export_addon}___This_key_will_deactivate_on_{27_August_2026}_for_{Test_Fixture}____eyJ2IjoxLCJob2xkZXIiOiJUZXN0IEZpeHR1cmUiLCJpc3MiOiIyMDI2LTA3LTIwIiwicHJvZHVjdHMiOnsiaGFuZHNvbnRhYmxlIjp7InRpZXIiOiJlbnRlcnByaXNlIiwibW9kZSI6ImludGVybmFsIiwiZXhwIjoiMjAyNi0wOC0yNyIsImdyYWNlIjo5MH0sImh5cGVyZm9ybXVsYSI6eyJ0aWVyIjoiZGF0YV9ncmlkIiwiYWRkb25zIjpbInNwcmVhZHNoZWV0IiwiaW1wb3J0X2V4cG9ydCJdfX191b127ce249a90abb06568b5583c67ead62564bf79cd0450eb19f84748a1c99a5f769de50a07a22012a3efd03435a4dcb7b6dc3b4f812c463e395814869be073a';

/**
 * Subscription granting only HyperFormula - no Handsontable grant.
 *
 * @type {string}
 */
export const HF_ONLY_KEY = '[SUB]_this_{HyperFormula}_key_is_granted_under_a_subscription_license___Use_after_expiry_is_not_permitted_per_the_subscription_agreement___To_renew_contact_sales@handsontable.com___Scope_{HyperFormula_CRM}_only___This_key_will_deactivate_on_{27_August_2026}_for_{Test_Fixture}____eyJ2IjoxLCJob2xkZXIiOiJUZXN0IEZpeHR1cmUiLCJpc3MiOiIyMDI2LTA3LTIwIiwicHJvZHVjdHMiOnsiaHlwZXJmb3JtdWxhIjp7InRpZXIiOiJjcm0iLCJleHAiOiIyMDI2LTA4LTI3IiwiZ3JhY2UiOjkwfX19bdfe0828541374a28580b3f81b77ca805e0547d04d9d443d307f63098712a69c76e5f688b6bb2612b56b20cf8b100cf203aefb3a21e892ee1ddc16928ca7944a';
