[build]
    edge_functions = "netlify/edge-functions"
    command = "echo no build"

[[redirects]]
    from = "/docs/*"
    to = "/docs/:splat"
    status = 200
    force = true

[[redirects]]
    from = "/*"
    to = "/docs/404.html"
    status = 404
    force = true
