<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

// Generated by: php artisan make:seeder ProductSeeder
// Run with:     php artisan db:seed --class=ProductSeeder
class ProductSeeder extends Seeder
{
    public function run(): void
    {
        if (Product::count() > 0) {
            $this->command->info('Products table already seeded -- skipping.');
            return;
        }

        $products = [
            ['name' => 'Laptop Pro 15',              'sku' => 'LAP-001', 'category' => 'Electronics',  'price' => 1299.99, 'stock' => 42,  'sort_order' => 1],
            ['name' => 'Wireless Mouse',             'sku' => 'MOU-002', 'category' => 'Accessories',  'price' => 29.99,   'stock' => 315, 'sort_order' => 2],
            ['name' => 'USB-C Hub 7-in-1',           'sku' => 'HUB-003', 'category' => 'Accessories',  'price' => 49.99,   'stock' => 178, 'sort_order' => 3],
            ['name' => 'NVMe SSD 1 TB',              'sku' => 'SSD-004', 'category' => 'Storage',      'price' => 109.99,  'stock' => 260, 'sort_order' => 4],
            ['name' => 'Mechanical Keyboard',        'sku' => 'KEY-005', 'category' => 'Peripherals',  'price' => 139.99,  'stock' => 95,  'sort_order' => 5],
            ['name' => 'Gigabit Switch 8-Port',      'sku' => 'SW8-006', 'category' => 'Networking',   'price' => 59.99,   'stock' => 74,  'sort_order' => 6],
            ['name' => 'Portable Monitor 15"',       'sku' => 'MON-007', 'category' => 'Electronics',  'price' => 249.99,  'stock' => 38,  'sort_order' => 7],
            ['name' => 'Webcam 4K',                  'sku' => 'CAM-008', 'category' => 'Peripherals',  'price' => 89.99,   'stock' => 112, 'sort_order' => 8],
            ['name' => 'External HDD 2 TB',          'sku' => 'HDD-009', 'category' => 'Storage',      'price' => 74.99,   'stock' => 193, 'sort_order' => 9],
            ['name' => 'Wi-Fi 6 Router',             'sku' => 'RTR-010', 'category' => 'Networking',   'price' => 179.99,  'stock' => 55,  'sort_order' => 10],
            ['name' => 'Noise-Cancelling Headphones','sku' => 'HP-011',  'category' => 'Accessories',  'price' => 199.99,  'stock' => 67,  'sort_order' => 11],
            ['name' => 'Thunderbolt Dock',           'sku' => 'DOC-012', 'category' => 'Accessories',  'price' => 219.99,  'stock' => 31,  'sort_order' => 12],
            ['name' => 'Laptop Stand',               'sku' => 'STD-013', 'category' => 'Accessories',  'price' => 39.99,   'stock' => 220, 'sort_order' => 13],
            ['name' => 'Gaming Controller',          'sku' => 'CTR-014', 'category' => 'Peripherals',  'price' => 69.99,   'stock' => 148, 'sort_order' => 14],
            ['name' => 'HDMI Cable 2 m',             'sku' => 'CBL-015', 'category' => 'Accessories',  'price' => 12.99,   'stock' => 500, 'sort_order' => 15],
            ['name' => 'MicroSD 256 GB',             'sku' => 'MSD-016', 'category' => 'Storage',      'price' => 29.99,   'stock' => 387, 'sort_order' => 16],
            ['name' => 'PoE Switch 24-Port',         'sku' => 'POE-017', 'category' => 'Networking',   'price' => 299.99,  'stock' => 18,  'sort_order' => 17],
            ['name' => 'Smart Plug 4-Pack',          'sku' => 'PLG-018', 'category' => 'Electronics',  'price' => 34.99,   'stock' => 142, 'sort_order' => 18],
            ['name' => 'USB Microphone',             'sku' => 'MIC-019', 'category' => 'Peripherals',  'price' => 79.99,   'stock' => 89,  'sort_order' => 19],
            ['name' => 'Ergonomic Chair Mat',        'sku' => 'MAT-020', 'category' => 'Accessories',  'price' => 44.99,   'stock' => 61,  'sort_order' => 20],
            ['name' => 'Tablet 10" Wi-Fi',           'sku' => 'TAB-021', 'category' => 'Electronics',  'price' => 349.99,  'stock' => 27,  'sort_order' => 21],
            ['name' => 'Power Bank 20000 mAh',       'sku' => 'PBK-022', 'category' => 'Accessories',  'price' => 49.99,   'stock' => 203, 'sort_order' => 22],
            ['name' => 'OLED Monitor 27"',           'sku' => 'MON-023', 'category' => 'Electronics',  'price' => 699.99,  'stock' => 14,  'sort_order' => 23],
            ['name' => 'USB-A 4-Port Hub',           'sku' => 'HUB-024', 'category' => 'Accessories',  'price' => 19.99,   'stock' => 341, 'sort_order' => 24],
            ['name' => 'SSD Enclosure',              'sku' => 'ENC-025', 'category' => 'Storage',      'price' => 24.99,   'stock' => 115, 'sort_order' => 25],
            ['name' => 'Network Cable Cat 6 10 m',  'sku' => 'CBL-026', 'category' => 'Networking',   'price' => 9.99,    'stock' => 620, 'sort_order' => 26],
            ['name' => 'Drawing Tablet',             'sku' => 'TAB-027', 'category' => 'Peripherals',  'price' => 189.99,  'stock' => 43,  'sort_order' => 27],
            ['name' => 'Smart Switch',               'sku' => 'SW2-028', 'category' => 'Electronics',  'price' => 44.99,   'stock' => 78,  'sort_order' => 28],
            ['name' => 'Desk Lamp LED',              'sku' => 'LMP-029', 'category' => 'Accessories',  'price' => 34.99,   'stock' => 99,  'sort_order' => 29],
            ['name' => 'RAID Controller',            'sku' => 'RAD-030', 'category' => 'Storage',      'price' => 149.99,  'stock' => 22,  'sort_order' => 30],
        ];

        foreach ($products as $data) {
            Product::create($data);
        }
    }
}
