export const data = [
  {
    isActive: true,
    name: 'John Doe',
    password: 'mysecretpassword',
    age: 30,
    interest: 'Electronics',
    country: 'USA',
    city: 'New York',
    lastLoginDate: '2023-08-25',
    lastLoginTime: '8:30:00 AM',
    favoriteProduct: 'iPhone 13 Pro',
  },
  {
    isActive: false,
    name: 'Jane Smith',
    password: 'anotherpassword',
    age: 28,
    interest: 'Fashion',
    country: 'Canada',
    city: 'Toronto',
    lastLoginDate: '2023-09-01',
    lastLoginTime: '2:15:00 PM',
    favoriteProduct: 'MacBook Air',
  },
  {
    isActive: true,
    name: 'Robert Johnson',
    password: 'secure123',
    age: 35,
    interest: 'Tech Gadgets',
    country: 'UK',
    city: 'London',
    lastLoginDate: '2023-08-30',
    lastLoginTime: '8:45:00 PM',
    favoriteProduct: 'Apple Watch Series 7',
  },
  {
    isActive: true,
    name: 'Emily Wilson',
    password: 'password123',
    age: 27,
    interest: 'Home Decor',
    country: 'Australia',
    city: 'Sydney',
    lastLoginDate: '2023-09-02',
    lastLoginTime: '12:00:00 PM',
    favoriteProduct: 'iPad Pro',
  },
  {
    isActive: false,
    name: 'Michael Brown',
    password: 'michael123',
    age: 42,
    interest: 'Sports & Fitness',
    country: 'USA',
    city: 'Los Angeles',
    lastLoginDate: '2023-08-22',
    lastLoginTime: '10:20:00 AM',
    favoriteProduct: 'Fitness Tracker',
    __children: [
      {
        isActive: true,
        name: 'Robert Johnson',
        password: 'secure123',
        age: 35,
        interest: 'Tech Gadgets',
        country: 'UK',
        city: 'London',
        lastLoginDate: '2023-08-30',
        lastLoginTime: '8:45:00 PM',
        favoriteProduct: 'Apple Watch Series 7',
      },
      {
        isActive: true,
        name: 'Emily Wilson',
        password: 'password123',
        age: 27,
        interest: 'Home Decor',
        country: 'Australia',
        city: 'Sydney',
        lastLoginDate: '2023-09-02',
        lastLoginTime: '12:00:00 PM',
        favoriteProduct: 'iPad Pro',
      },
      {
        isActive: false,
        name: 'Michael Brown',
        password: 'michael123',
        age: 42,
        interest: 'Sports & Fitness',
        country: 'USA',
        city: 'Los Angeles',
        lastLoginDate: '2023-08-22',
        lastLoginTime: '10:20:00 AM',
        favoriteProduct: 'Fitness Tracker',
      },
      {
        isActive: true,
        name: 'Maria Garcia',
        password: 'maria456',
        age: 33,
        interest: 'Books & Literature',
        country: 'Spain',
        city: 'Barcelona',
        lastLoginDate: '2023-09-05',
        lastLoginTime: '4:45:00 PM',
        favoriteProduct: 'Kindle Paperwhite',
      },
    ],
  },
  {
    isActive: true,
    name: 'Maria Garcia',
    password: 'maria456',
    age: 33,
    interest: 'Books & Literature',
    country: 'Spain',
    city: 'Barcelona',
    lastLoginDate: '2023-09-05',
    lastLoginTime: '4:45:00 PM',
    favoriteProduct: 'Kindle Paperwhite',
  },
  {
    isActive: false,
    name: 'Hiroshi Tanaka',
    password: 'hiroshi789',
    age: 29,
    interest: 'Tech Gadgets',
    country: 'Japan',
    city: 'Tokyo',
    lastLoginDate: '2023-08-27',
    lastLoginTime: '3:10:00 PM',
    favoriteProduct: 'Nintendo Switch',
  },
  {
    isActive: true,
    name: 'Emma Johnson',
    password: 'emma123',
    age: 24,
    interest: 'Beauty & Personal Care',
    country: 'UK',
    city: 'Manchester',
    lastLoginDate: '2023-09-03',
    lastLoginTime: '9:50:00 AM',
    favoriteProduct: 'Makeup Set',
  },
  {
    isActive: true,
    name: 'Lucas Oliveira',
    password: 'lucas456',
    age: 38,
    interest: 'Food & Cooking',
    country: 'Brazil',
    city: 'Sao Paulo',
    lastLoginDate: '2023-08-29',
    lastLoginTime: '1:30:00 PM',
    favoriteProduct: "Chef's Knife Set",
  },
  {
    isActive: false,
    name: 'Ava Smith',
    password: 'ava789',
    age: 22,
    interest: 'Travel & Adventure',
    country: 'USA',
    city: 'Miami',
    lastLoginDate: '2023-09-04',
    lastLoginTime: '5:55:00 PM',
    favoriteProduct: 'Travel Backpack',
  },
  {
    isActive: true,
    name: 'Miguel Rodriguez',
    password: 'miguel123',
    age: 45,
    interest: 'Art & Collectibles',
    country: 'Spain',
    city: 'Madrid',
    lastLoginDate: '2023-08-28',
    lastLoginTime: '7:25:00 PM',
    favoriteProduct: 'Oil Painting',
  },
  {
    isActive: true,
    name: 'Sophia Kim',
    password: 'sophia456',
    age: 31,
    interest: 'Electronics',
    country: 'South Korea',
    city: 'Seoul',
    lastLoginDate: '2023-08-26',
    lastLoginTime: '11:10:00 AM',
    favoriteProduct: 'Smartphone',
  },
  {
    isActive: false,
    name: 'Liam Chen',
    password: 'liam789',
    age: 26,
    interest: 'Fashion',
    country: 'Canada',
    city: 'Vancouver',
    lastLoginDate: '2023-08-31',
    lastLoginTime: '6:40:00 PM',
    favoriteProduct: 'Designer Handbag',
  },
  {
    isActive: true,
    name: 'Elena Fernandez',
    password: 'elena123',
    age: 29,
    interest: 'Tech Gadgets',
    country: 'Spain',
    city: 'Valencia',
    lastLoginDate: '2023-09-01',
    lastLoginTime: '10:15:00 AM',
    favoriteProduct: 'Wireless Earbuds',
  },
  {
    isActive: true,
    name: 'Oliver Johnson',
    password: 'oliver456',
    age: 34,
    interest: 'Home Decor',
    country: 'USA',
    city: 'Chicago',
    lastLoginDate: '2023-08-30',
    lastLoginTime: '3:40:00 PM',
    favoriteProduct: 'Home Lighting',
  },
  {
    isActive: false,
    name: 'Luna Martinez',
    password: 'luna789',
    age: 23,
    interest: 'Sports & Fitness',
    country: 'Mexico',
    city: 'Mexico City',
    lastLoginDate: '2023-09-02',
    lastLoginTime: '2:05:00 PM',
    favoriteProduct: 'Yoga Mat',
  },
  {
    isActive: true,
    name: 'Ethan Wang',
    password: 'ethan123',
    age: 27,
    interest: 'Books & Literature',
    country: 'Canada',
    city: 'Toronto',
    lastLoginDate: '2023-08-29',
    lastLoginTime: '12:20:00 PM',
    favoriteProduct: 'Bestseller Novel',
  },
  {
    isActive: true,
    name: 'Isabella Davis',
    password: 'isabella456',
    age: 32,
    interest: 'Beauty & Personal Care',
    country: 'USA',
    city: 'Houston',
    lastLoginDate: '2023-08-27',
    lastLoginTime: '8:55:00 AM',
    favoriteProduct: 'Skincare Set',
  },
  {
    isActive: false,
    name: 'Liam Chen',
    password: 'liam789',
    age: 26,
    interest: 'Travel & Adventure',
    country: 'Canada',
    city: 'Vancouver',
    lastLoginDate: '2023-08-31',
    lastLoginTime: '6:40:00 PM',
    favoriteProduct: 'Travel Backpack',
  },
  {
    isActive: true,
    name: 'John Doe',
    password: 'mysecretpassword',
    age: 30,
    interest: 'Electronics',
    country: 'USA',
    city: 'New York',
    lastLoginDate: '2023-08-25',
    lastLoginTime: '8:30:00 AM',
    favoriteProduct: 'iPhone 13 Pro',
  },
  {
    isActive: false,
    name: 'Jane Smith',
    password: 'anotherpassword',
    age: 28,
    interest: 'Fashion',
    country: 'Canada',
    city: 'Toronto',
    lastLoginDate: '2023-09-01',
    lastLoginTime: '2:15:00 PM',
    favoriteProduct: 'MacBook Air',
  },
  {
    isActive: true,
    name: 'Robert Johnson',
    password: 'secure123',
    age: 35,
    interest: 'Tech Gadgets',
    country: 'UK',
    city: 'London',
    lastLoginDate: '2023-08-30',
    lastLoginTime: '8:45:00 PM',
    favoriteProduct: 'Apple Watch Series 7',
  },
  {
    isActive: true,
    name: 'Emily Wilson',
    password: 'password123',
    age: 27,
    interest: 'Home Decor',
    country: 'Australia',
    city: 'Sydney',
    lastLoginDate: '2023-09-02',
    lastLoginTime: '12:00:00 PM',
    favoriteProduct: 'iPad Pro',
  },
  {
    isActive: false,
    name: 'Michael Brown',
    password: 'michael123',
    age: 42,
    interest: 'Sports & Fitness',
    country: 'USA',
    city: 'Los Angeles',
    lastLoginDate: '2023-08-22',
    lastLoginTime: '10:20:00 AM',
    favoriteProduct: 'Fitness Tracker',
  },
  {
    isActive: true,
    name: 'Maria Garcia',
    password: 'maria456',
    age: 33,
    interest: 'Books & Literature',
    country: 'Spain',
    city: 'Barcelona',
    lastLoginDate: '2023-09-05',
    lastLoginTime: '4:45:00 PM',
    favoriteProduct: 'Kindle Paperwhite',
  },
  {
    isActive: false,
    name: 'Hiroshi Tanaka',
    password: 'hiroshi789',
    age: 29,
    interest: 'Tech Gadgets',
    country: 'Japan',
    city: 'Tokyo',
    lastLoginDate: '2023-08-27',
    lastLoginTime: '3:10:00 PM',
    favoriteProduct: 'Nintendo Switch',
  },
  {
    isActive: true,
    name: 'Emma Johnson',
    password: 'emma123',
    age: 24,
    interest: 'Beauty & Personal Care',
    country: 'UK',
    city: 'Manchester',
    lastLoginDate: '2023-09-03',
    lastLoginTime: '9:50:00 AM',
    favoriteProduct: 'Makeup Set',
  },
  {
    isActive: true,
    name: 'Lucas Oliveira',
    password: 'lucas456',
    age: 38,
    interest: 'Food & Cooking',
    country: 'Brazil',
    city: 'Sao Paulo',
    lastLoginDate: '2023-08-29',
    lastLoginTime: '1:30:00 PM',
    favoriteProduct: "Chef's Knife Set",
  },
  {
    isActive: false,
    name: 'Ava Smith',
    password: 'ava789',
    age: 22,
    interest: 'Travel & Adventure',
    country: 'USA',
    city: 'Miami',
    lastLoginDate: '2023-09-04',
    lastLoginTime: '5:55:00 PM',
    favoriteProduct: 'Travel Backpack',
  },
  {
    isActive: true,
    name: 'Miguel Rodriguez',
    password: 'miguel123',
    age: 45,
    interest: 'Art & Collectibles',
    country: 'Spain',
    city: 'Madrid',
    lastLoginDate: '2023-08-28',
    lastLoginTime: '7:25:00 PM',
    favoriteProduct: 'Oil Painting',
  },
  {
    isActive: true,
    name: 'Sophia Kim',
    password: 'sophia456',
    age: 31,
    interest: 'Electronics',
    country: 'South Korea',
    city: 'Seoul',
    lastLoginDate: '2023-08-26',
    lastLoginTime: '11:10:00 AM',
    favoriteProduct: 'Smartphone',
  },
  {
    isActive: false,
    name: 'Liam Chen',
    password: 'liam789',
    age: 26,
    interest: 'Fashion',
    country: 'Canada',
    city: 'Vancouver',
    lastLoginDate: '2023-08-31',
    lastLoginTime: '6:40:00 PM',
    favoriteProduct: 'Designer Handbag',
  },
  {
    isActive: true,
    name: 'Elena Fernandez',
    password: 'elena123',
    age: 29,
    interest: 'Tech Gadgets',
    country: 'Spain',
    city: 'Valencia',
    lastLoginDate: '2023-09-01',
    lastLoginTime: '10:15:00 AM',
    favoriteProduct: 'Wireless Earbuds',
  },
  {
    isActive: true,
    name: 'Oliver Johnson',
    password: 'oliver456',
    age: 34,
    interest: 'Home Decor',
    country: 'USA',
    city: 'Chicago',
    lastLoginDate: '2023-08-30',
    lastLoginTime: '3:40:00 PM',
    favoriteProduct: 'Home Lighting',
  },
  {
    isActive: false,
    name: 'Luna Martinez',
    password: 'luna789',
    age: 23,
    interest: 'Sports & Fitness',
    country: 'Mexico',
    city: 'Mexico City',
    lastLoginDate: '2023-09-02',
    lastLoginTime: '2:05:00 PM',
    favoriteProduct: 'Yoga Mat',
  },
  {
    isActive: true,
    name: 'Ethan Wang',
    password: 'ethan123',
    age: 27,
    interest: 'Books & Literature',
    country: 'Canada',
    city: 'Toronto',
    lastLoginDate: '2023-08-29',
    lastLoginTime: '12:20:00 PM',
    favoriteProduct: 'Bestseller Novel',
  },
  {
    isActive: true,
    name: 'Isabella Davis',
    password: 'isabella456',
    age: 32,
    interest: 'Beauty & Personal Care',
    country: 'USA',
    city: 'Houston',
    lastLoginDate: '2023-08-27',
    lastLoginTime: '8:55:00 AM',
    favoriteProduct: 'Skincare Set',
  },
  {
    isActive: false,
    name: 'Liam Chen',
    password: 'liam789',
    age: 26,
    interest: 'Travel & Adventure',
    country: 'Canada',
    city: 'Vancouver',
    lastLoginDate: '2023-08-31',
    lastLoginTime: '6:40:00 PM',
    favoriteProduct: 'Travel Backpack',
  },
];
