name: Docs Linter

on:
  push:
    paths:
      - 'docs/**'
  pull_request:
    paths:
      - 'docs/**'
    types: [ opened, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: JS & CSS & VUE
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # https://github.com/actions/checkout/releases/tag/v4.1.1

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        name: Install pnpm

      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # https://github.com/actions/setup-node/releases/tag/v4.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: docs/package-lock.json

      - name: Install Documentation dependencies
        run: |
          cd docs/ && npm ci --no-audit

      - name: Install Handsontable dependencies
        run: |
          pnpm install

      - name: Lint
        run: |
          cd docs/ && npm run docs:lint
