name: Docs Staging Deployment

on:
  pull_request:
    types: [ labeled, synchronize ]
  push:
    branches-ignore:
      - 'prod-docs/**'
      - 'master'
    paths:
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./docs/

jobs:
  preview:
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'ci:docs-deploy') }}
    name: Build and push Preview to Netlify (on pull request label)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # https://github.com/actions/checkout/releases/tag/v6.0.2

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # https://github.com/pnpm/action-setup/releases/tag/v4.2.0
        name: Install pnpm

      - name: Use Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # https://github.com/actions/setup-node/releases/tag/v6.2.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Find PR
        uses: jwalton/gh-find-current-pr@89ee5799558265a1e0e31fab792ebb4ee91c016b # https://github.com/jwalton/gh-find-current-pr/tree/v1.3.3
        id: pr-finder

      - name: Get PR details
        id: get-pr
        if: ${{ steps.pr-finder.outputs.pr }}
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # https://github.com/actions/github-script/releases/tag/v8.0.0
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number ||  ${{ steps.pr-finder.outputs.pr }}
            });

            console.log(`PR #${context.issue.number} details fetched`);
            console.log(`Source branch: ${pullRequest.head.ref}`);
            console.log(`Target branch: ${pullRequest.base.ref}`);

            // Set outputs to use in subsequent steps
            core.setOutput('source_branch', pullRequest.head.ref);
            core.setOutput('target_branch', pullRequest.base.ref);
            core.setOutput('pr_owner', pullRequest.head.repo.owner.login);
            core.setOutput('pr_repo', pullRequest.head.repo.name);

            return pullRequest;
          result-encoding: string

      - name: Install Netlify dependencies
        run: |
           cd netlify
           npm i
           npm install netlify-cli -g

      - name: Run the create or get Netlify Page process. Save the Netlify vars in a file
        run: |
          cd netlify
          node createOrGet.mjs
          cat NETLIFY_VARS >> $GITHUB_ENV
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PREVIEW_AUTH_TOKEN }}
          NETLIFY_ACCOUNT_SLUG: ${{ secrets.NETLIFY_ACCOUNT_SLUG }}
          BRANCH_NAME_PREFIX: dev-handsontable-
          BRANCH_NAME: ${{ steps.get-pr.outputs.source_branch || github.ref_name }}

      - name: Publish sticky comment in PR. Docs are being built
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # https://github.com/marocchino/sticky-pull-request-comment/tree/v2.9.4
        if: ${{ steps.pr-finder.outputs.pr }}
        with:
          number: ${{ steps.pr-finder.outputs.pr }}
          message: |
            🏗️ Preview documentation is being built/rebuilt.
            Current staging version of documentation will be available at: [${{ env.NETLIFY_SITE_URL }}/docs](${{ env.NETLIFY_SITE_URL }}/docs)

      - name: Install the documentation dependencies
        run: |
          npm ci --legacy-peer-deps

      - name: Install the monorepo dependencies and build the packages
        run: |
          cd ..
          pnpm install
          npm run all build -- --e examples visual-tests

      - name: Build docs (for staging preview)
        run: |
          npm run build

      - name: Build and deploy the preview to Netlify
        run: |
          cd netlify
          mkdir -p deploy/docs

          cp -r ../dist/. deploy/docs/

          cp _dev_headers deploy/_headers
          cp _redirects deploy/_redirects

      - name: Publish preview to Netlify
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # https://github.com/nick-fields/retry/releases/tag/v3.0.2
        with:
          timeout_seconds: 1600
          max_attempts: 3
          retry_on: error
          command: |
            cd docs/netlify
            netlify deploy --prod --dir deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PREVIEW_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ env.NETLIFY_SITE_ID }}

      - name: Publish sticky comment in PR
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # https://github.com/marocchino/sticky-pull-request-comment/tree/v2.9.4
        if: ${{ steps.pr-finder.outputs.pr }}
        with:
          number: ${{ steps.pr-finder.outputs.pr }}
          message: |
            ✅ Preview documentation is is available now
            Current staging version of documentation is available at: [${{ env.NETLIFY_SITE_URL }}/docs](${{ env.NETLIFY_SITE_URL }}/docs)
