name: Docs Staging Deployment. Documentation Review Delete (if exist).

on:
  pull_request:
    types: [closed]

defaults:
  run:
    working-directory: ./docs/

jobs:
  delete-preview-on-pull-request:
    name: Delete Netlify Site if exist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # https://github.com/actions/checkout/releases/tag/v4.1.1

      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # https://github.com/actions/setup-node/releases/tag/v4.4.0
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: docs/package-lock.json

      - name: Get PR details
        id: get-pr
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number ||  ${{ github.event.pull_request.number }}
            });

            console.log(`PR #${context.issue.number} details fetched`);
            console.log(`Source branch: ${pullRequest.head.ref}`);
            console.log(`Target branch: ${pullRequest.base.ref}`);

            // Set outputs to use in subsequent steps
            core.setOutput('source_branch', pullRequest.head.ref);
            core.setOutput('target_branch', pullRequest.base.ref);
            core.setOutput('pr_owner', pullRequest.head.repo.owner.login);
            core.setOutput('pr_repo', pullRequest.head.repo.name);

            return pullRequest;
          result-encoding: string

      - name: Install Netlify dependencies
        run: |
          cd netlify
          npm i

      - name: Run the delete process
        run: |
          cd netlify
          node deleteIfExist.mjs
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PREVIEW_AUTH_TOKEN }}
          BRANCH_NAME_PREFIX: dev-handsontable-
          BRANCH_NAME: ${{ steps.get-pr.outputs.source_branch }}
