name: Docs Linter

on:
  push:
    paths:
      - 'docs/**'
  pull_request:
    types: [ opened, synchronize, reopened ]

env:
  NODE_VERSION: 20

jobs:
  lint:
    name: JS & CSS & VUE
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # https://github.com/actions/checkout/releases/tag/v4.1.1

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # https://github.com/actions/setup-node/releases/tag/v4.0.2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: docs/package-lock.json

      - name: Install Documentation dependencies
        run: |
          cd docs/ && npm ci --no-audit

      - name: Install Handsontable dependencies
        run: |
          npm ci --no-audit

      - name: Lint
        run: |
          cd docs/ && npm run docs:lint
