name: Docs Staging Deployment (OVH)

env:
  GHA_DOCKER_TAG_NEXT: docker.pkg.github.com/${{ github.repository }}/handsontable-documentation:next
  GHA_DOCKER_TAG_SHA: docker.pkg.github.com/${{ github.repository }}/handsontable-documentation:${{ github.sha }}

on:
  workflow_dispatch:
    inputs:
      run_tests_job:
        description: 'Run the "Test examples" job?'
        required: false
        default: 'true'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./docs/

jobs:
  docker:
    name: Build and push Docker image
    if: ${{ github.ref != 'refs/heads/prod-docs/latest' }} # Exclude the prod-docs-latest branch from triggering the workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # https://github.com/actions/checkout/releases/tag/v4.1.1

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        name: Install pnpm
        with:
          version: 10

      - name: Use Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # https://github.com/actions/setup-node/releases/tag/v4.0.2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Docker login into GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u ${GITHUB_ACTOR} --password-stdin https://docker.pkg.github.com

      - name: Install the documentation dependencies
        run: |
          npm ci

      - name: Install the monorepo dependencies and build the packages
        run: |
          cd ..
          pnpm install
          npm run all build -- --e examples visual-tests

      - name: Generate API references
        run: |
          npm run docs:api

      - name: Docker build (for staging deployment)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          npm run docs:docker:build:staging

      - name: Docker build (for local testing)
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          npm run docs:docker:build:testing

      - name: Test examples
        if: ${{ github.event.inputs.run_tests_job == 'true' }}
        run: |
          npm run docs:test:example-checker

      - name: Docker tags
        run: |
          docker tag docs-md $GHA_DOCKER_TAG_NEXT
          docker tag docs-md $GHA_DOCKER_TAG_SHA

      - name: Docker push "next" into GHCR and deploy to the staging (only when manually dispatched)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          docker push ${GHA_DOCKER_TAG_NEXT}

      - name: Docker push SHA tagged into GHCR
        run: |
          docker push ${GHA_DOCKER_TAG_SHA}
