name: Check docs examples (JS version vs TS version)

on:
  pull_request:
    paths:
      - 'docs/**'
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs_examples:
    name: Docs Examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the pull request merge commit
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # https://github.com/actions/checkout/releases/tag/v6.0.2

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # https://github.com/pnpm/action-setup/releases/tag/v4.2.0
        name: Install pnpm

      - name: Use Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # https://github.com/actions/setup-node/releases/tag/v6.2.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: docs/package-lock.json

      - name: Install Documentation dependencies
        run: |
          cd docs/ && npm ci --no-audit

      - name: Install Handsontable dependencies
        run: |
          pnpm install

      - name: Generate JS code examples
        run: |
          cd docs/ && npm run docs:code-examples:generate-all-js

      - name: Check if generated examples made any changes
        run: |
          if git diff --exit-code && git diff --cached --exit-code; then
            echo "No changes detected"
          else
            exit 1
          fi

      - name: Report status
        if: failure()
        run: |
          echo "Changes were detected. This check has failed."
          exit 1
