name: Docs Visual Tests

on:
  workflow_dispatch:
    inputs:
      update-snapshots:
        description: "Update snapshots"
        type: boolean
      test_env:
        type: choice
        description: Test enviroment
        default: 'http://localhost:4321/docs'
        options:
          - https://dev.handsontable.com/docs
          - https://handsontable.com/docs
          - http://localhost:4321/docs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./docs/

jobs:
  run-tests:
    name: Visual tests for ${{ github.event.inputs.test_env }}
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      PASS_COOKIE: ${{ secrets.PASS_COOKIE }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # https://github.com/actions/checkout/releases/tag/v6.0.2

      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
        name: Install pnpm

      - name: Set up Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # https://github.com/actions/setup-node/releases/tag/v6.2.0
        with:
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
          node-version: "22"
          check-latest: true

      - name: Install monorepo dependencies (including docs)
        working-directory: .
        run: pnpm install

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Install the monorepo dependencies and build the packages
        if: ${{inputs.test_env == 'http://localhost:4321/docs'}}
        working-directory: .
        run: npm run all build -- --e examples visual-tests

      - name: Generate API refs
        if: ${{inputs.test_env == 'http://localhost:4321/docs'}}
        run: |
          npm run docs:api

      - name: Build documentation
        if: ${{inputs.test_env == 'http://localhost:4321/docs'}}
        run: |
          npm run build

      - name: Restore snapshot cache
        id: cache
        uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # https://github.com/actions/cache/releases/tag/v5.0.3
        with:
          key: plawyright-cache/${{github.repository}}/${{github.ref}}-${{ github.run_id }}
          restore-keys: |
            plawyright-cache/${{github.repository}}/${{github.ref}}
            plawyright-cache/${{github.repository}}/refs/heads/develop
          path: docs/tests/test-artifacts

      - name: Check if cache was restored
        id: check-cache
        run: |
          if [[ -n "$(find . -name 'test-artifacts' -type d -not -path '*/node_modules/*' -print0 | xargs -0 -I {} find {} -type f -print -quit)" ]]; then
            echo "cache-restored=true" >> $GITHUB_ENV
          else
            echo "cache-restored=false" >> $GITHUB_ENV
          fi

      - name: Initialize snapshots
        if: ${{env.cache-restored != 'true' || github.event.inputs.update-snapshots == 'true'}}
        run: BASE_URL=${{ github.event.inputs.test_env }} npx playwright test --update-snapshots

      - name: Test
        if: ${{env.cache-restored == 'true' && github.event.inputs.update-snapshots != 'true'}}
        run: BASE_URL=${{ github.event.inputs.test_env }} npx playwright test

      - name: Save snapshot cache
        if: ${{!cancelled() && (env.cache-restored != 'true' || github.event.inputs.update-snapshots == 'true')}}
        uses: actions/cache/save@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # https://github.com/actions/cache/releases/tag/v5.0.3
        with:
          key: plawyright-cache/${{github.repository}}/${{github.ref}}-${{ github.run_id }}
          path: docs/tests/test-artifacts

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # https://github.com/actions/upload-artifact/releases/tag/v7.0.0
        with:
          name: playwright-report
          path: ./docs/tests/test-artifacts/results
          retention-days: 30
          overwrite: true
