name: Check docs examples (JS version vs TS version)

on:
  pull_request:
    paths:
      - 'docs/**'
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs_examples:
    name: Docs Examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the pull request merge commit
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # https://github.com/actions/checkout/releases/tag/v4.1.1

      - name: Use Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # https://github.com/actions/setup-node/releases/tag/v4.0.2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: docs/package-lock.json

      - name: Install Documentation dependencies
        run: |
          cd docs/ && npm ci --no-audit

      - name: Install Handsontable dependencies
        run: |
          npm ci --no-audit

      - name: Generate JS code examples
        run: |
          cd docs/ && npm run docs:code-examples:generate-all-js

      - name: Check if generated examples made any changes
        run: |
          if git diff --exit-code && git diff --cached --exit-code; then
            echo "No changes detected"
          else
            exit 1
          fi

      - name: Report status
        if: failure()
        run: |
          echo "Changes were detected. This check has failed."
          exit 1
